### ISSUE TITLE
Fix zlux-grid so that scrollableVertical and paginator features work correctly

### ISSUE THREAD

**Issue by NolanRogers** [zowe/zlux#111]
Fix zlux-grid so that scrollableVertical and paginator features work correctly.

Currently, when the default zlux-grid component is presented with data that is larger than can be displayed in the application's view

**Comment by NolanRogers** [comment]
Had to remove 19-04-02 1.0.2 milestone, Issue is being moved back to backlog as efforts are being refocused

**Comment by NolanRogers** [comment]
@reetchow - didn't @DivergentEuropeans compete this?

**Comment by DivergentEuropeans** [comment]
This is very old and if my memory is right, I did
