### ISSUE TITLE
Embed OWASP dependency scan into pipeline

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zlux#119]
As sub-issue of https://github.com/zowe/zowe-install-packaging/issues/406:

The changes should allow the pipeline:

- to run OWASP dependency scan per commit on every branch,
- to run OWASP dependency scan on daily basis if the repository is not actively developing.

**Comment by NolanRogers** [comment]
@1000TurquoisePogs  did we do this?

**Comment by jackjia-ibm** [comment]
Closing this issue with a side Jenkins job created to generate OWASP report. The main reason is the scanning is slow and if we add to each pipeline, it will slow down the build process a lot.
