### ISSUE TITLE
Better authentication handling for Desktop Login

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#125]
Today, Zowe Desktop Login is not capable of
- telling you the reason for login failure (Password wrong versus ZSS down versus account disabled)
- allowing you to reset your password
- multi-factor authentication
- any back-and-forth, multi-step process to login... such as the above MFA & reset password steps.

**Comment by NolanRogers** [comment]
@1000TurquoisePogs this seems like this could be an epic? MFA and password reset are already other epics too.

**Comment by jordanCain** [comment]
@John-A-Davies This is the issue I was talking about

**Comment by John-A-Davies** [comment]
Hi Jordan,

Thanks for remembering and finding this.

Regards,

John A Davies, z/OS IBM Systems | zSystems Software, Hursley, UK. Tel 
37245623.  (+)44 (0)1962 815623.  daviesja@uk.ibm.com

"If you don't know how much of your code has been tested, why are you 
releasing it?"  Ask me about code coverage or click on this link
Code coverage on IBM Connections

**Comment by DivergentEuropeans** [comment]
I believe @sakshibobade21 completed this with enhanced Desktop error message formatting
