### ISSUE TITLE
Switch zlux cookies from timed to untimed

### ISSUE THREAD

**Issue by NolanRogers** [zowe/zlux#132]
Right now zlux cookies are set to expire in one hour from their creation. The IBM security team has requested that we switch them from timed to untimed since they can sit on disk after their expiration and malware can potentially find interesting information from the cookie.

Acceptance Criteria:

Change session cookie in zlux to untimed
QA to ensure that no unexpected changes in behavior occur

**Comment by 1000TurquoisePogs** [comment]
Tracking over here https://github.com/zowe/zlux-server-framework/issues/81
