### ISSUE TITLE
If I type something fast in the editor it slows down

### ISSUE THREAD

**Issue by NolanRogers** [zowe/zlux#134]
As a user of the code editor, when I type new text into the editor it runs slowly. Typing fast will trigger this error.

**Comment by 1000TurquoisePogs** [comment]
This has been mostly solved by dataset & file browser enhancements, as the list quantity caused slowdown. Closing this as having been mitigated, but performance is something we can strive to improve further. See 1.5.0 for the latest in dataset fixes (It missed 1.4.0)
