### ISSUE TITLE
Implement a dataset browser using the Zowe dataset API

### ISSUE THREAD

**Issue by NolanRogers** [zowe/zlux#137]
Implement a dataset browser using the Zowe dataset API

**Comment by DivergentEuropeans** [comment]
We have a Dataset browser via the Editor. With the addition of the File Explorer into Editor and the latest merge to 'staging', I have made them separate modules, so you can view USS files and Datasets separately. Is this it or do we want a whole separate app just for Datasets?

@NolanRogers

**Comment by NolanRogers** [comment]
@1000TurquoisePogs @reetchow  Can we help define better acceptance criteria for this story wirh Leanid?

**Comment by DivergentEuropeans** [comment]
This has been done/outdated. Further bugs and enhancements should have their own issues
