### ISSUE TITLE
Hotkey implementations for Code Editor

### ISSUE THREAD

**Issue by NolanRogers** [zowe/zlux#140]
As a user of the code editor I want hotkeys so that I can use common features without searching through the menus

Acceptance Criteria:

We should have the following hotkeys:
New File
Open File
New Tab
Copy
Paste

**Comment by DivergentEuropeans** [comment]
Pending PR: https://github.com/zowe/zlux-editor/pull/90

**Comment by DivergentEuropeans** [comment]
This was completed (at least what's in the criteria)
