### ISSUE TITLE
Unable to access zLux (port 8544) with cipher error

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zlux#144]
From Zowe nightly build https://gizaartifactory.jfrog.io/gizaartifactory/libs-snapshot-local/com/project/zowe/1.2.0-STAGING/zowe-1.2.0-20190514.035416-56.pax, which is picking up libs-snapshot-local/org/zowe/zlux/zlux-core/1.1.0-STAGING/zlux-core-1.1.0-20190429.203350.pax, the zLux service is failed to be accessed with cipher error.

If access zlux with Chrome v74, we receive an error of:

```
river.zowe.org uses an unsupported protocol.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH
```

If access zlux with Firefox v60, we receive an error of:

```
An error occurred during a connection to river.zowe.org:8544. Cannot communicate securely with peer: no common encryption algorithm(s). Error code: SSL_ERROR_NO_CYPHER_OVERLAP
```

And curl also receive error of:

```
curl: (35) error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
```

Test console log can be found at https://wash.zowe.org:8443/job/zowe-install-test/job/staging/60/console. And this is console log of staging build #56 https://wash.zowe.org:8443/job/zowe-install-packaging/job/staging/56/console.

**Comment by 1000TurquoisePogs** [comment]
What version of Chrome are you using?
What version of nodejs are you using?

**Comment by jackjia-ibm** [comment]
It's Chrome v74 and Node.JS on server is v6.14.4.

I believe this error is related to special settings on zD&T testing. We reset the image yesterday, so maybe someone had some changes on the server which make it was working ok, but after we reset to original image, the error pops. If you need access to the server, please let me know. We had similar errors on APIML before v1.2.0 release.

**Comment by 1000TurquoisePogs** [comment]
Those versions seem fine. The logs don't include the server log so not sure if something went wrong, when was the last time that this worked? There hasn't been a change to the cipher settings of zlux since 1.0.1, so maybe a system configuration change is the cause.
Here's output comparing river to a Rocket system running 1.2.0:
```
> curl --output /dev/null --silent --show-error --insecure --request GET --fail --connect-timeout 20 https://river.zowe.org:8544/
curl: (35) error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
> curl --output /dev/null --silent --show-error --insecure --request GET --fail --connect-timeout 20 https://mylpar.rocketsoftware.com:8544/
> curl --show-error --insecure --request GET --fail --connect-timeout 20 https://mylpar.rocketsoftware.com:8544/
Found. Redirecting to /ZLUX/plugins/org.zowe.zlux.bootstrap/web/
```

**Comment by 1000TurquoisePogs** [comment]
Other troubleshooting thought: zlux uses nodejs which uses openssl. If zlux requests ciphers that can't be fulfilled by node/openssl, maybe this happens, but I'm not sure why that would be.

**Comment by jackjia-ibm** [comment]
After some investigations, I believe the issue is not related to zLux, but caused by https://github.com/zowe/zowe-install-packaging/pull/491, and results in an incorrect certificates generated.

So false alarm, and closing the issue.

**Comment by John-A-Davies** [comment]
I got this too on ZPDT system using zowe v1.3.0+20190607.

**Comment by John-A-Davies** [comment]
Comment to me from @jordanCain 

> The ACDC image that the zD&T images we build off of have GCM cipher suites disabled which is what most browsers want to use today, they're currently building the next ACDC image that will resolve that

**Comment by John-A-Davies** [comment]
From Zowe v1.3.0 onwards, we restricted the acceptable ciphers, and the GCM cipher was removed.  So unless and until ZPDT systems from ADCD support this, we have to undo the restriction in Zowe.

Jack told me how to do this.

Message from @jackjia-ibm 

> on river, the file is located at `/Z23B/usr/lpp/java/J8.0_64/lib/security/java.security`, search for `jdk.certpath.disabledAlgorithms` entry, you will find `, GCM`, remove and save.  then need to restart Zowe

**Comment by ehrocha** [comment]
I am experiencing the same thing, I have checked and I do not have GCM on my java.security :(

**Comment by MichaelErichsen** [comment]
There parameter to change is
jdk.tls.disabledAlgorithms
Not
jdk.certpath.disabledAlgorithms

This allows Firefox and Chrome to connect to Zowe.
