### ISSUE TITLE
Provide option to customize a default/home directory or discover via OMVS RACF segment

### ISSUE THREAD

**Issue by jordanCain** [zowe/zlux#145]
Currently the USS tree does not default to any path, I think defaulting to the users home directory would be beneficial and could be done by a user preference or by inspecting what is set as the HOME value in a users OMVS RACF segment

**Comment by 1000TurquoisePogs** [comment]
So, looks like the API we can use here just isn't exposed today, but we should be exposing it.
On zss, doing a GET to /omvs returns:
```
{
    "uid": stringNumber,
    "home": stringPath,
    "program": stringPath,
    "cpuTimeMax": stringNumberOrNone,
    "assizeMax": stringNumberOrNone",
    "fileProcMax": stringNumberOrNone,
    "procUserMax": stringNumberOrNone,
    "threadsMax": stringNumberOrNone,
    "mMapAreaMax": stringNumberOrNone
}
```

ex:
```
{
    "uid": "0000001001",
    "home": " /u/me",
    "program": "/bin/sh",
    "cpuTimeMax": "NONE",
    "assizeMax": "NONE",
    "fileProcMax": "NONE",
    "procUserMax": "NONE",
    "threadsMax": "NONE",
    "mMapAreaMax": "NONE"
}
```

First thing to do is to expose this & make a swagger doc for it. Then call it to bootstrap editor.

**Comment by 1000TurquoisePogs** [comment]
Took that first step as a test for if the DCO signer (https://addons.mozilla.org/en-US/firefox/addon/scott-rigby/?src=search) was working correctly... https://github.com/zowe/zlux-app-server/commit/6b5f8c64a1de02ffc3f739fe7e79f7249548ef09

**Comment by 1000TurquoisePogs** [comment]
Need to check on if this API works for TS and ACF2, and have a fallback in case we need an enhancement there too.

**Comment by jordanCain** [comment]
I had a first stab at this, here's the resulting PR's - I've only added the functionality to default to a users home directory if available
https://github.com/zowe/zlux-platform/pull/28
https://github.com/zowe/zlux-app-manager/pull/116
https://github.com/zowe/zlux-file-explorer/pull/16
