### ISSUE TITLE
Code Editor: improve file / DS browser UI

### ISSUE THREAD

**Issue by NolanRogers** [zowe/zlux#149]
As a user of the Editor app, I would expect the following while working with file / DS browser:

It's not clear which of the categories (USS, Datasets) is selected.
An active one is expected to be highlighted somehow
The "Select viewing..." label doesn't seem to be adequate:
a) USS is selected by default
b) It is OK for initial screen but not permanently
Intuitively expected UI that may solve the both is tab view or something like that.

**Comment by NolanRogers** [comment]
@DivergentEuropeans was this completed for 1.3.0?

**Comment by DivergentEuropeans** [comment]
@NolanRogers Yes it was.

**Comment by NolanRogers** [comment]
Awesome thanks @DivergentEuropeans

**Comment by DivergentEuropeans** [comment]
Np! @NolanRogers

**Comment by NolanRogers** [comment]
@DivergentEuropeans I added the 1.3.0 milestone
