### ISSUE TITLE
Unable to display full name of plugin on Zowe launch-bar

### ISSUE THREAD

**Issue by sillysayali** [zowe/zlux#162]
Complete name of plugin cannot be displayed on Zowe launh-bar menu.
Plugin name is: "IBM Z Service Management Explorer"

Notes:
- Tested on Zowe 1.0.1 and Zowe 1.10

**Comment by DivergentEuropeans** [comment]
I believe this was fixed last year. Feel free to re-open if still an active issue 🐙
