### ISSUE TITLE
In-UI (inband) Multifactor authentication

### ISSUE THREAD

**Issue by NolanRogers** [zowe/zlux#164]
What this is:

Modify login screen of Zowe Desktop to support dynamic amount of fields & conversational behavior, as required by any multi-factor authentication solution
Also include passtickets.
Open issue for reset password functionality from Web UI

What this isn't:

Support for any MFA product under the sun.

**Comment by 1000TurquoisePogs** [comment]
I think this should also include passtickets.

**Comment by NolanRogers** [comment]
@1000TurquoisePogs I updated the description / acceptance criteria
