### ISSUE TITLE
Separate the ATTLS documentation for developers

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#169]
ATTLS documentation on the doc site is administrator focused, such that it documents all steps required. However, if you're a developer of the app server, and ZSS is already set up with ATTLS, then you only need a subset of the entire documentation - just the part about configuration the app server. 
Basically, developers only need step 4 of this: https://zowe.github.io/docs-site/latest/user-guide/mvd-configuration.html#configuring-zss-for-https
So, could this be made more clear so it can be linked in isolation?

**Comment by Martin-Zeithaml** [comment]
There can be added a note to skip unneeded steps and continue with step 4 only. The suggested change to make it isolated for developers is nice, but this will require to review and change the rest of the documentation and make it for "developers" as well.

**Comment by 1000TurquoisePogs** [comment]
I dont believe this is needed anymore in light of zss just having native https.
