### ISSUE TITLE
BUG: File tabs in zlux-editor are vertically scrollable

### ISSUE THREAD

**Issue by jordanCain** [zowe/zlux#170]
Currently you can accidentally vertically scroll on the file tabs of editor,

![Screen Shot 2019-06-11 at 4.22.06 PM.png](https://images.zenhubusercontent.com/5c93e87bb54d4b45005c1360/e3f979d9-8c0f-40a3-9306-ca7fde2d92ed)

**Comment by 1000TurquoisePogs** [comment]
I believe this is now done! Thank you.
