### ISSUE TITLE
Create new Install API for Desktop Plugins as an alternative to having access to Filesystem

### ISSUE THREAD

**Issue by hogstrom** [zowe/zlux#171]
I was recently listening to a team that was creating a set of REST services for Netview.  They were showing the install procedure they were using (all command line).  It occurred to me that if we had a REST API to install the plugin we would have a more manageble way to ensure the integrity of the Zowe filesystem and permissions and it would simplify plugin management.

@1000TurquoisePogs I suspect you've already thought about this.  Is this on your list of things or is this a bad idea.

**Comment by 1000TurquoisePogs** [comment]
It's on the list, but it can't be done without first ensuring the security restricts such a network API to only administrators of that Zowe instance.
I have https://github.com/zowe/zlux-app-server/pull/55 for making app installation a little simpler, and have https://github.com/1000TurquoisePogs/zlux-server-framework/tree/prototype/server-mgmt to try out some ideas on REST APIs that manage Plugins

**Comment by 1000TurquoisePogs** [comment]
This is currently being worked on again. We are adding an API to allow admins to trigger server refresh of filesystem contents. Next step would be to tie-in some file transfer logic to write to disk prior to the refresh.

**Comment by 1000TurquoisePogs** [comment]
Hi Matt, so I think this is done now in 1.5.0.
The API is here: 
https://raw.githubusercontent.com/zowe/zlux-app-server/rc/doc/swagger/server-plugins-api.yaml

But, it cannot be used without activating & configuring RBAC, which is described here: 
https://docs.zowe.org/stable/user-guide/mvd-configuration.html#enabling-rbac

Judging from this https://github.com/zowe/zss-auth/blob/rc/lib/safprofile.js I think the profile needed  in the Zowe class would be:
ZLUX.0.COR.*
Which would give an admin access to all CORe APIs.
