### ISSUE TITLE
Code Editor doesn't save state of editor tabs

### ISSUE THREAD

**Issue by mwroffo** [zowe/zlux#177]
<p>Code Editor doesn't save state of tabs of open files when I switch between them which is really annoying:</p>
<ul>
	<li>it loses position of cursor</li>
	<li>it loses scroll results</li>
	<li>it loses text selection</li>
	<li>etc.</li>
</ul>

**Comment by 1000TurquoisePogs** [comment]
May be a matter of utilizing save & restore states: https://github.com/microsoft/vscode/blob/master/src/vs/editor/browser/widget/codeEditorWidget.ts
