### ISSUE TITLE
Implement File Properties in File Explorer Right Click Menu

### ISSUE THREAD

**Issue by mwroffo** [zowe/zlux#180]
<p>The File Explorer should be able to right click on a file, directory, or dataset to get actions to take. These actions include the typical actions you see in file explorers on windows &amp; mac, but for the purpose of this ticket we will just start with 1 menu item, which is to display a popup that shows the properties of the object. So, we would expect to see the name, path, size, and permissions for files &amp; directories, but for datasets we would expect to see the record length, and volser, etc.</p>

<p>Start with properties, do not yet worry about delete, copy, paste, cut... these will be future tickets.</p>

<p> </p>

**Comment by DivergentEuropeans** [comment]
This has been merged to 'staging'
