### ISSUE TITLE
Restrict/Warn users when editing dataset with a fixed block length when line length exceeds FB length

### ISSUE THREAD

**Issue by jordanCain** [zowe/zlux#182]
In a scenario when a user is editing a Fixed Block (FB) dataset/member they should be warned when they exceed the record length.

The record length would have to be surfaced

This could be implemented by drawing a ruler in the editor widget and when a user types over that ruler text is shown with a red underline (similar to spell check showing incorrect spelling).

**Comment by 1000TurquoisePogs** [comment]
I have a branch which does this, but it isnt finished yet. A combination of the column marker and validation upon save attempt will warn the user.

**Comment by 1000TurquoisePogs** [comment]
Closed due to inactivity
