### ISSUE TITLE
When opening the code editor in the simple window viewer url query parameters can direct tabs to auto open

### ISSUE THREAD

**Issue by jordanCain** [zowe/zlux#185]
A scenario where a user is editing a file/dataset and wants to create a link to that file they can share with a colleague. 

The code editor could be interpret url query params, or the simple window viewer could process them and make available via inter app communication in order to open content automatically.

Along with just a file name the option to go to a specific line could also be beneficial

**Comment by 1000TurquoisePogs** [comment]
I would say this would be best implemented as trying to best of abilities to put an app2app launch context into query parameter, and have the simple window manager take query parameter to feed into apps as if it were app2app.

**Comment by NolanRogers** [comment]
@lchudinov is this something that you have already implemented? @1000TurquoisePogs  also mentioned that a need for a button or menu option for ease of use would be beneficial

**Comment by lchudinov** [comment]
I did this for MVD Window Manager(not for Simple Window Manager): https://github.com/zowe/zlux-app-manager/pull/234

The link to open a file with Code Editor looks like this: `https://localhost:8544/ZLUX/plugins/org.zowe.zlux.bootstrap/web/?app2app=org.zowe.editor:launch:create:data:{"type":"openFile","name":"/usr/include/stdio.h"}`

**Comment by DivergentEuropeans** [comment]
And I made this work w/ all by making Simple Window Manager obsolete, so this should now be done

https://localhost:8544/ZLUX/plugins/org.zowe.zlux.bootstrap/web/?app2app=org.zowe.editor:launch:create:data:{"type":"openFile","name":"/usr/include/stdio.h"}
works for me
