### ISSUE TITLE
Keytool error:1 while trusting z/OSMF certificate

### ISSUE THREAD

**Issue by GuillaumeLouis** [zowe/zlux#188]
Hello

because we don't use the default z/OSMF userid (ZOSMF instead of IZUSVR) we had to issue the command below. But at the end we obtain a keytool error 1 although we have a message "Certificate was added to keystore"

Certificate was added to keystore                                               
keytool error (likely untranslated): java.io.FileNotFoundException: keystore/loc
alhost/localhost.truststore.p12 (EDC5129I No such file or directory.)           
keytool returned: 1    

I Understand I don't set  APIML truststore properly.

/usr/lpp/zowe/api-mediation/scripts > apiml_cm.sh --action trust-zosmf --zosmf-u
serid ZOSMF --zosmf-keyring IZUKeyring.IZUDFLT                                  
Listing entries in the z/OSMF keyring (IZUKeyring.IZUDFLT):                     
                                                                                
Keystore type: JCERACFKS                                                        
Keystore provider: IBMJCE                                                       
                                                                                
Your keystore contains 4 entries                                                
                                                                                
UCDNC20A, Sep 11, 2019, keyEntry,                                               
Certificate fingerprint (SHA1): DD:45:EB:8E:65:E1:5C:F3:C0:46:7D:11:73:B8:E7:CE:
E0:DA:7D:C5                                                                     
UINTD28B, Sep 11, 2019, trustedCertEntry,                                       
Certificate fingerprint (SHA1): 48:7C:77:14:79:C7:ED:69:CA:91:59:17:5B:7F:AA:8A:
75:E7:BC:04                                                                     
UINTD28A, Sep 11, 2019, trustedCertEntry,                                       
Certificate fingerprint (SHA1): 87:82:AB:2E:D4:76:FB:0A:86:AA:52:44:47:ED:1F:DD:
C6:10:EA:42                                                                     
URACD28A, Sep 11, 2019, trustedCertEntry,                                       
Certificate fingerprint (SHA1): 0B:EA:24:1A:35:07:1F:39:9B:EE:DD:EC:DF:54:4D:B3:
9E:C3:4F:0B                                                                     
Exporting certificate 'UCDNC20A' from z/OSMF:                                   
Certificate stored in file </tmp/zosmf_cert_1.cer>                              
Import a certificate to the truststore:                                         
Calling keytool -importcert -trustcacerts -noprompt -file /tmp/zosmf_cert_1.cer 
-alias UCDNC20A -keystore keystore/localhost/localhost.truststore.p12 -storepass
 password -storetype PKCS12                                                     
Certificate was added to keystore                                               
keytool error (likely untranslated): java.io.FileNotFoundException: keystore/loc
alhost/localhost.truststore.p12 (EDC5129I No such file or directory.)           
keytool returned: 1

**Comment by NolanRogers** [comment]
Please redirect this issue to the API-ML group in slack. The repo to best suit the issue would be called API-Layer. Thank you!
