### ISSUE TITLE
MVDZOS=>Cleanup apps which misuse config service

### ISSUE THREAD

**Issue by jplinardon** [zowe/zlux#19]
Hardcoding, wrong scopes, wrong aggregation types, user instead of internal configuration... check that our core plugins are doing the right things.

**Comment by 1000TurquoisePogs** [comment]
This is not relevant to the code in zowe. Code in zowe however should certainly make use of the dataservice according to the wiki https://github.com/zowe/zlux/wiki/Configuration-Dataservice
