### ISSUE TITLE
Dataset Editor does not list all datasets unless you use `.*` or `.**`

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zlux#192]
The Zowe Dataset Editor follows the dataset selection criteria used by ISPF 3.4 when its `Include Additional Qualifiers` option is deselcted.  Most people do not use ISPF 3.4 in this way - they usually have `Include Additional Qualifiers` selected.

In the Zowe Dataset Editor, if you want to list all datasets starting with your HLQ, you must use the format `HLQ.**`.  If you want to see all datasets starting with your HLQ, followed by exactly one level,  you must use the format `HLQ.*`.  For exactly two levels,  you must use the format `HLQ.*.*` and so  on.

Since this behaviour is different from the ISPF 3.4 convention, we should document this, saying something like the contents of the paragraph above.

Note that the original MVD MVS Explorer does follow the convention as if `Include Additional Qualifiers` were selected.  So you see two different behaviours in different windows of the same MVD.

**Comment by NolanRogers** [comment]
Closing as this was added into 1.11.
