### ISSUE TITLE
npm install fails (internal-ip)

### ISSUE THREAD

**Issue by eamondawes** [zowe/zlux#194]
The webClient's package.json requests _@angular-devkit/build-angular_ which requests _webpack-dev-server_ which requests _internal-ip_ which [recently implemented](https://github.com/sindresorhus/internal-ip/commit/586ae808bf1942cd5e85a34f41f5a98f944979ed#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) a whitelist of OSs omitting os390, this causes the `npm install` to fail.

**Comment by piculet** [comment]
Is this issue still open? The install seems to be working fine.
