### ISSUE TITLE
No debug msg when TN3270 or VT fails to connect

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zlux#195]
On ukzowe3 ZPDT system, I tried to use TN3270 and VT inside the desktop.  I made about 50 attempts to connect but only a few succeeded.  The problem is, I see a log message when the connection succeeds, but when it fails there is no message, so I can't debug the problem.

I'm looking in the SYSLOG of ZOWESVR on z/OS.

I always see the connection attempt:

```
[66351] [2019-07-01 11:05:26.529 org.zowe.terminal.proxy.tn3270data INFO] - Saw Websocket request, method=GET     
```
That one failed, so there is no further message.

Here's one that worked
```
19-07-02 10:13:49.314 org.zowe.terminal.proxy.tn3270data INFO] - Saw Websocket request, method=GET                                                             
19-07-02 10:13:49.329 org.zowe.terminal.proxy.tn3270data INFO] - [Host=127.0.0.1, Port=23, ClientIP=9.140.98.142] Connected. Total terminals connected: 1      
19-07-02 10:13:49.331 org.zowe.terminal.proxy.tn3270data INFO] - Total TN3270 terminals connected: 1                                                           
19-07-02 10:13:49.746 _zsf.child INFO] - [Path=/zaas1/zowe/1.3.0/zlux-app-server/bin/zssServer.sh stdout]: done with system response                           
```

**Comment by NakulManchanda** [comment]
@1000TurquoisePogs we noticed a thing, which you may find interesting,  
what we found is, after login into zowe desktop,

if we open vt-terminal app first and wait, and then open tn3270 it works. 

And vice versa - if we open tn3270 first and then vt terminal connects. 

So over same machines and infrastructure it do connect. 

My case is to connect windows mozilla/chrome browser to backend ubuntu hosted ZD&T machine. But it happens with **only one particular windows machine**, but if i use same other windows machine, it works normally with same back-end.

**Comment by 1000TurquoisePogs** [comment]
Update: Nakul & Jack seem to have traced this down to inconsistent behavior about IPC between node cluster & workers. Strangely, it seems to work better after dropping the initial message as far as I have heard. So a quick fix may be to reply the first message until it works. A fix for the underlying cause is ideal for 3rd party development however.

**Comment by NakulManchanda** [comment]
the underlying issue found was:
- websocket connections do not get registered properly when in cluster mode
- it found to be a timing issue
- when websocket connection establishes, it sends a ack to client browser

Issue resolved: 
- issue resolved by retrying unless 
   - keep trying to get websocket connection unless ack is received

Server behaves like no websocket request is received,
but to debug issue we can see websocket reply-response happening in client browser

**Comment by NakulManchanda** [comment]
@NolanRogers @1000TurquoisePogs 
We can close this issue

**Comment by NakulManchanda** [comment]
Successful Exchange:

![image.png](https://images.zenhubusercontent.com/5cacf8caef5a5209eacab3ea/79ee4a1a-ddfc-4c19-8576-13a8ae62a0cc)
