### ISSUE TITLE
ZOWE : EUREKA : COnnection Refused.

### ISSUE THREAD

**Issue by yugeshpothuru** [zowe/zlux#196]
Receiving the below error while starting zowe in ZPDT system.

Problem making eureka request { Error: connect ECONNREFUSED 10.242.55.48:10011  
    at Object.exports._errnoException (util.js:1020:11)                         
    at exports._exceptionWithHostPort (util.js:1043:20)                         
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)             
  code: 'ECONNREFUSED',                                                         
  errno: 'ECONNREFUSED',                                                        
  syscall: 'connect',                                                           
  address: '10.242.55.48',                                                      
  port: 10011 }                                                                 

not able to access the mainpage.

https://<appservername_port>/ZLUX/plugins/org.zowe.zlux.bootstrap/web/index.html

**Comment by NolanRogers** [comment]
Please reopen if 1000TurquoisePogs response did not solve the issue. Thank you!
