### ISSUE TITLE
nodeServer don't need userid/password to login

### ISSUE THREAD

**Issue by rjmaomao** [zowe/zlux#197]
Hi,

I followed https://developer.ibm.com/tutorials/zowe-step-by-step-tutorial/ 
at step 5. Run the server
executed
 zlux/zlux-app-server/bin/nodeServer.sh -h 9.114.33.20 -P 8542 -s 14549

In /Z2/var/zowert/1.2.0/zlux-app-server/deploy/instance/ZLUX/serverConfig/zluxserver.json, updated ip to 0.0.0.0. 
_"agent": {
    //host is for zlux to know, not zss
    "host": "localhost",
    "http": {
      "ipAddresses": ["0.0.0.0"],
      //to be a replacement for zssPort
      "port": 8542
    }_

If I use default value 127.0.0.1, I would fail to start server with message

_[2019-06-12 13:45:03.329 _zsf.child INFO] - [Path=/Users/renjing/Documents/Work/Zowe/github/zlux/zlux-app-server/bin/zssServer.sh stdout]: /Users/renjing/Documents/Work/Zowe/github/zlux/zlux-app-server/bin/zssServer.sh: line 127: ./zssServer: No such file or directory

[2019-06-12 13:45:03.331 _zsf.child INFO] - [Path=/Users/renjing/Documents/Work/Zowe/github/zlux/zlux-app-server/bin/zssServer.sh] exited, code: 0
[2019-06-12 13:45:03.533 _zsf.proxy WARNING] - Failed to reach the auth services host for address 9.114.33.20:8542
could not start the server:  Communication with 9.114.33.20:8542 failed: Error: connect ECONNREFUSED 9.114.33.20:8542_

When I access https://localhost:14549/ZLUX/plugins/org.zowe.zlux.bootstrap/web/index.html

I found I don't need to input any userid or password, then I can logon. Could you please help to see what is wrong here? Thanks.

**Comment by DivergentEuropeans** [comment]
To build slightly on @1000TurquoisePogs answer, your authentication isn't set up. So it's allowing you to log in without a username or password but no authenticated services are available to you, for example: like accessing files or datasets. Following the instructions above me will help you to set up the zssServer (by compiling it from the /zss/ repo) that will make your first step no longer show that error. Let us know if you have any other issues.
