### ISSUE TITLE
Extensible resource access framework

### ISSUE THREAD

**Issue by jgellin** [zowe/zlux#2]
Sometimes z Systems developers may need access to source code that is in an SCM (so - neither in MVS nor Unix) - for example, to view the code in the editor.  It would be nice to have a common way in Zowe to access these resources. 

What I have in mind is a URI resolver component (perhaps implemented as a Node module?), where Zowe-based tooling in zLux can simply refer to source files using a URI, and the URI resolver component can do things like get the contents of the resource so that it can be opened in the editor. SCM providers can then extend Zowe to resolve URI's that are particular to their SCM.

![uri-resolver](https://user-images.githubusercontent.com/26168391/45040009-edd7db00-b032-11e8-8883-5a6d2d99e92d.png)

**Comment by lilcubby** [comment]
Like the concept, is the intent to just get the file contents? Or should we think of other use cases that fall into the same category?

**Comment by jplinardon** [comment]
This item was discussed during the squad meeting and approved onto the backlog. Jon will propose a technical design for review during an upcoming meeting.

**Comment by 1000TurquoisePogs** [comment]
Maybe this already does what you need or nearly so: https://github.com/zowe/zlux/wiki/URI-Broker

**Comment by 1000TurquoisePogs** [comment]
Example here: https://github.com/zowe/sample-app/blob/master/webClient/src/app/app.component.ts#L36

**Comment by NolanRogers** [comment]
@1000TurquoisePogs is this still applicable today?
