### ISSUE TITLE
running a full screen does not require authentication

### ISSUE THREAD

**Issue by vvvlc** [zowe/zlux#200]
Hi

when I open https://host:port/ZLUX/plugins/org.zowe.zlux.bootstrap/web/?pluginId=org.zowe.editor in browser (ie outside desktop)  in incognito mode (ie. I'm not authenticated) 
Editor shows up but no login window is displayed as a result of this I cannot use editor.
I cannot edit my uss files, ...

**Comment by 1000TurquoisePogs** [comment]
I just made a pull request which solves this for apps that aren't iframes, as with iframes there are two ways: via the ?pluginID method, or going right to their URL to skip the whole iframe mechanism. If using the ?pluginID method this also supports iframes.

**Comment by 1000TurquoisePogs** [comment]
OK, this is now merged with 162. Old bookmarks will still have the behavior described, but opening in a new tab from the desktop will utilize this new query parameter to show a login screen.
