### ISSUE TITLE
Env var for building UI is "MVD_DESKTOP_DIR"

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#203]
The env var for finding the webpack and typescript config files has a misleading name. It should perhaps be "ZLUX_UI_SCRIPTS_DIR"

**Comment by DivergentEuropeans** [comment]
Still relevant? @1000TurquoisePogs

**Comment by travatine** [comment]
yes, its also unclear how exactly the MVD_DESKTOP_DIR variable is used. 
e.g. if I want to build an angular app off zos , what should the variable be set to?
