### ISSUE TITLE
Improve exception handling during build, it breaks when any plugin fails to build

### ISSUE THREAD

**Issue by NakulManchanda** [zowe/zlux#206]
When using build.bat to do build for zlux+plugins, *any bad plugin can break the build*,
plugin are build using npm script - `npm run build`
Individual plugin build can break fro number of reason, like incorrect webpack.json or syntax error in plugin code. _Build process should just log message, failed to build plugin and continue to build rest_, Basically, better exception handling during build process can improve the build experience.

**Comment by 1000TurquoisePogs** [comment]
Seems no longer true.
