### ISSUE TITLE
Fail to create workflow by User Tasks/Workflows in zLUX

### ISSUE THREAD

**Issue by rjmaomao** [zowe/zlux#207]
Running with 1.2.0, failed to use User Tasks/Workflows in desktop to create workflow.

![workflow create](https://user-images.githubusercontent.com/44960894/57287056-480ccc80-70e9-11e9-92af-d12133c9b28a.png)

Could you please help to take a look ? Thanks!

**Comment by DivergentEuropeans** [comment]
Workflows app has been discontinued from core
