### ISSUE TITLE
Show a file as modified once a user has made changes but not saved the file

### ISSUE THREAD

**Issue by jordanCain** [zowe/zlux#209]
A common pattern editors follow is to show an '*' next to the name of a file tab once the file has in flight changes (the file has been modified but not yet saved) 

The editor should also have this functionality

**Comment by 1000TurquoisePogs** [comment]
This looks like a regression. Could swear that we used to have this.
I used to get a little blue circle on the tab when there were unsaved changes... dont see that now.
![image.png](https://images.zenhubusercontent.com/5ca760660102ad60918e8aa1/f4ae75ec-7533-4ed9-a75c-d53cd282cffa)

**Comment by DivergentEuropeans** [comment]
@1000TurquoisePogs Yes, I remember something like that too.

**Comment by DivergentEuropeans** [comment]
I made the blue circle work again as intended
