### ISSUE TITLE
nodejs fails with 0C4 after restart of zowe

### ISSUE THREAD

**Issue by VitekVlcek-Broadcom** [zowe/zlux#211]
Nodejs8 on z/OS fails with SYSTEM COMPLETION CODE=0C4 compile unit TLBA99ME

![image002](https://user-images.githubusercontent.com/43439912/65606251-cf7cae80-dfaa-11e9-8ff9-4705aab2f351.jpg)

Zowe was installed correctly and desktop started properly, then zowe was recycled and Nodejs8 failed.

**Comment by 1000TurquoisePogs** [comment]
That's a nearly instant 0c4. Do you have any nodejs logs (CEE dump maybe?) We should notify the IBM nodejs group with the logs.

**Comment by VitekVlcek-Broadcom** [comment]
Unfortunately I don't any dump but I have asked customer to provide joblog and dumps.
In the meantime we proposed:
-  to review IEFUSI, IEALIMIT or REGION 
- to try an older version of nodejs (we are running 6)

**Comment by Joe-Winchester** [comment]
@NayerNajafi - I recall you said there some node PTFs that need to be applied that mean there are no ghost node processes left around, and from the description of this it may be related as the Oc4 occurred after Zowe STC was ended and restarted

**Comment by NayerNajafi** [comment]
@VitekVlcek-Broadcom Can you please ask customer for z/OS version and z/OS service level?

**Comment by NayerNajafi** [comment]
In troubleshooting document for Node.js V6 the issue CEE3204S with Abend SC04 exists:
https://www.ibm.com/support/knowledgecenter/en/SSTRRS_6.0.0/com.ibm.nodejs.zos.v6.doc/troubleshoot.htm

**Comment by NayerNajafi** [comment]
@Joe-Winchester @VitekVlcek-Broadcom I talked to Igor Todorovski from Node.js team about this issue. Here is his suggestion:
**the customer can do this: export __MEM_ACCOUNT=1 and send us the output. This way we can verify if it is indeed the same issue.
We are in the process of testing a fix for this and will ship a PTF soon.  Also, can you verify if the customer has enough above the bar storage:
/bin/ulimit -a**

**Comment by VitekVlcek-Broadcom** [comment]
should I instruct user to update `scripts/internal/run-zowe.sh` 
to add 
```sh
...
export __MEM_ACCOUNT=1   #added
/bin/ulimit -a     #added
cd $DIR/../../zlux-app-server/bin && _BPX_JOBNAME=$ZOWE_DESKTOP ./nodeCluster.sh --allowInvalidTLSProxy=true &
_BPX_JOBNAME=$ZOWE_API_DS $DIR/../../api-mediation/scripts/api-mediation-start-discovery.sh
_BPX_JOBNAME=$ZOWE_API_CT $DIR/../../api-mediation/scripts/api-mediation-start-catalog.sh
_BPX_JOBNAME=$ZOWE_API_GW $DIR/../../api-mediation/scripts/api-mediation-start-gateway.sh
_BPX_JOBNAME=$ZOWE_EXPL_JOBS $DIR/../../explorer-jobs-api/scripts/jobs-api-server-start.sh
_BPX_JOBNAME=$ZOWE_EXPL_DATA $DIR/../../explorer-data-sets-api/scripts/data-sets-api-server-start.sh
_BPX_JOBNAME=$ZOWE_EXPL_UI_JES $DIR/../../jes_explorer/scripts/start-explorer-jes-ui-server.sh
_BPX_JOBNAME=$ZOWE_EXPL_UI_MVS $DIR/../../mvs_explorer/scripts/start-explorer-mvs-ui-server.sh
_BPX_JOBNAME=$ZOWE_EXPL_UI_USS $DIR/../../uss_explorer/scripts/start-explorer-uss-ui-server.sh
```
and restart zowe?

**Comment by Joe-Winchester** [comment]
@VitekVlcek-Broadcom - I suggest you get the customer to do as you suggest.

**Comment by NayerNajafi** [comment]
@VitekVlcek-Broadcom I asked @jackjia-ibm about this way of update to generate the output. He confirms this way.

**Comment by IgorTodorovskiIBM** [comment]
Node.js v8 on z/OS has been updated with the fix.  However, there may be other reasons contributing to this failure, such as not enough above the bar storage.

/bin/ulimit -a
```
core file         8192b
cpu time          unlimited
data size         unlimited
file size         17179869176b
stack size        unlimited
file descriptors  64000
address space     unlimited
memory above bar  6144m
```

memory above the bar should be at least 2gb and address space should be unlimited.

**Comment by NayerNajafi** [comment]
@VitekVlcek-Broadcom The fix for this issue has been provided by IBM Node.js team and PTF has been shipped. 
PTF Info: (APAR: PH17747 - PTF: UI65737)

**Comment by VitekVlcek-Broadcom** [comment]
Thank you I will pass information to customer

**Comment by NolanRogers** [comment]
Closing as fixed completed
