### ISSUE TITLE
Make the /plugin API semi-authenticated

### ISSUE THREAD

**Issue by NolanRogers** [zowe/zlux#214]
In order to make plugins accessible according to role, the /plugin server API must distinguish between users, once login has been done.

Acceptance Criteria:

When there is no user session for a request (session expired, or person hasnt logged in yet), then a GET to /plugins returns the JSON
If there is a session, instead, the response to GET /plugins is a possibly NON-default JSON in the structure 
Server is able to lookup the JSON when given a user (user info stored in session object)
You should not be able to get the /plugins of ANOTHER user... the server should faithfully be able to return results particular to 1 user for 1 session.

**Comment by 1000TurquoisePogs** [comment]
Resolved in zowe/zlux-server-framework#153
