### ISSUE TITLE
Customization of clock on launchbar

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#220]
Rather than just use localization detection to determine clock format, people may want to:
1) choose a different format perhaps from a different localization
2) show or hide seconds
3) show or hide date
4) show or hide day
5) open a calendar

**Comment by DivergentEuropeans** [comment]
I have prototype code for some of this, that will sit in the Personalization & Settings area where the Language menu is

**Comment by 1000TurquoisePogs** [comment]
Closed due to inactivity
