### ISSUE TITLE
Zowe plugin repository

### ISSUE THREAD

**Issue by NolanRogers** [zowe/zlux#223]
Develop a repository design such that Zowe App Framework Plugins can be searched and downloaded from a repository whether the repository is on the internet or within a company LAN.

The act of downloading a plugin from the repository can optionally trigger an installation process which sets up the plugin for use without any prompting. Later, we can tie in the install wizard epic to prompt for a degree of initial setup customization.

The deliverable is a repository structure + a set of zowe plugin management tools which is capable of the following:

Searching for plugins by description, ID, name
Seeing metadata about the plugin such as author & version & type
Being able to query the repository to see if updates are available for installed plugins
Being able to download plugins from the repository
Being able to install downloaded plugins into zowe (and have the success marked for future update checks)
Create packaging instructions & tools to allow plugin developers to publish repository-compatible plugin packages
The tooling & repository must be capable of running on z/os as well as windows, linux, unix.
Therefore, the tooling should be nodejs, and the repo conda, as they fit our existing design and are portable 

The repository technology is to be based on conda, due to its flexibility. However, we must evaluate what conda can / cant do in regards to what we want to do.

**Comment by 1000TurquoisePogs** [comment]
Obsoleted by #449
