### ISSUE TITLE
Out of band MFA

### ISSUE THREAD

**Issue by NolanRogers** [zowe/zlux#225]
In order for Zowe to support IBM's MFA product out of band, we must correct two Zowe components which do not work when MFA is enabled.

The way that MFA will be used is ether, user enters in derived token from MFA credentials (passphrase) OR you get a CTC from IBM MFA server website. Then, you put the data into the passphrase field of any login prompt, and that should give you the same access to Zowe as you would have had without MFA.

 

The two components which do not work currently when you do this are: The entire Zowe CLI, because it stores passwords in a way that isnt aware that they will expire, as well as the /omvs REST API, which gives an error code 500 for MFA accounts.

 

The team needs to figure out WHY the OMVS service fails, so that it can be enhanced to work with and without MFA-enabled accounts

And, the team needs to figure out how to work with the CLI squad to get the CLI to support MFA in a way that will be aware of the MFA lifecycle.

You can use the following IBM MFA server for testing: https://rs21:6789/mfa/TOTPONLY

You need to bug Sean to get access to the MFA user.

**Comment by 1000TurquoisePogs** [comment]
This technically is supported for the Desktop (when using zss, apiml, and/or explorers) now, but needs documentation first.
