### ISSUE TITLE
Provide the Zowe Editor app a refresh button

### ISSUE THREAD

**Issue by FreekCornelis** [zowe/zlux#231]
The Zowe Editor app lacks a refresh button similar to the refresh button of the MVS Explorer and USS Explorer.

**Comment by 1000TurquoisePogs** [comment]
In 1.19.0 you will see refresh buttons in the side panel as well as the ability to refresh open files by right clicking on their tab.
1.19.0 is nearly released, and release candidate 2 is here: https://zowe.jfrog.io/zowe/libs-release-local/org/zowe/1.19.0-RC2/zowe-1.19.0-RC2.pax
Please reopen if you still see this issue. Thanks!
