### ISSUE TITLE
Zowe Editor keeps prompting with 'Untagged File Found' when saving an initially untagged file

### ISSUE THREAD

**Issue by FreekCornelis** [zowe/zlux#232]
When an untagged file is opened and edited in the Editor app, saving it causes the Editor to prompt for an encoding. Subsequent saves again cause the Editor to prompt for an encoding.
Initially:
![image](https://user-images.githubusercontent.com/55885539/66408506-5a1fcd80-e9ef-11e9-89ef-0976cd8c10da.png)
Saving the file shows:
![image](https://user-images.githubusercontent.com/55885539/66408558-71f75180-e9ef-11e9-8911-bd0ead913193.png)
File is saved as IBM-1047. Result:
![image](https://user-images.githubusercontent.com/55885539/66408620-8f2c2000-e9ef-11e9-9f6c-ac479ca58b9f.png)
Saving it again in the Editor:
![image](https://user-images.githubusercontent.com/55885539/66408696-b256cf80-e9ef-11e9-897e-261c91e85ebe.png)
Looks like the new encoding is not refreshed in the Editors cache.

The prompting is not done anymore when the file is closed and re-opened.

**Comment by NolanRogers** [comment]
@1000TurquoisePogs  I added the review label to this, as it is my understanding that this may longer be an issue?

**Comment by 1000TurquoisePogs** [comment]
This is no longer an issue. It's been fixed for quite some time.

**Comment by DivergentEuropeans** [comment]
that issue is still not solved for me partially. My test case is creating a file that's untagged in Putty, then opening it untagged in the Editor, then clicking Save, tagging it as UTF-8 and saving it again

**Comment by AdarshdeepCheema** [comment]
Fixed
