### ISSUE TITLE
When saving a new file in Zowe Editor, use the opened directory in the dialog

### ISSUE THREAD

**Issue by FreekCornelis** [zowe/zlux#233]
When a new file is opened in the Editor, the Save dialog always shows an empty Directory field in the Save As dialog, instead of suggesting the currently opened directory

**Comment by 1000TurquoisePogs** [comment]
Background for whoever implements this: We need to enhance the file explorer widget to allow it to be called to know what the current directory is, so the editor can utilize that to pre-populate the dialogue.

**Comment by DivergentEuropeans** [comment]
This is now fixed, added in the 'staging' branch and should make it into 1.8 if I remember...

**Comment by NolanRogers** [comment]
Thanks for closing this Lenny.
