### ISSUE TITLE
The Save dialog in the Zowe Editor does not enforce specification of all 3 fields

### ISSUE THREAD

**Issue by FreekCornelis** [zowe/zlux#234]
When saving a new file in the Zowe Editor, the Save As dialog requests 3 fields to be filled in (Directory, File name, Encoding), but it allows any of these fields to left blank, thus causing an error with a message like
![image](https://user-images.githubusercontent.com/55885539/66410425-62c5d300-e9f2-11e9-85b8-10211f52e71d.png)
The Save As dialog should check first that all required fields are filled in before enabling the Save button.

**Comment by 1000TurquoisePogs** [comment]
This is still valid on 1.18.0
