### ISSUE TITLE
After saving a new file in Zowe Editor, a new save again shows the Save As dialog

### ISSUE THREAD

**Issue by FreekCornelis** [zowe/zlux#235]
A new file is opened in the Zowe Editor, edited and saved via the Save As dialog:
![image](https://user-images.githubusercontent.com/55885539/66411101-7aea2200-e9f3-11e9-874c-d910330f4ad3.png)
![image](https://user-images.githubusercontent.com/55885539/66411149-8d645b80-e9f3-11e9-9ce5-5eeaa6f99a95.png)
Saving it again (via Ctrl-S) again shows the Save As dialog:
![image](https://user-images.githubusercontent.com/55885539/66411238-b7b61900-e9f3-11e9-9532-164a9228133c.png)
whereas it should simply save it. 
A closing of  the file and re-opening it is required to  fix this.

**Comment by FreekCornelis** [comment]
Hi @1000TurquoisePogs, I am in the process of obtaining 1.5.0 and will report what I see when I have it installed. I did look at all open and closed issues for the Editor but did not find any that was similar, so I raised this and other issues

**Comment by NolanRogers** [comment]
Hello Freek,

Are you still having this issue?

**Comment by FreekCornelis** [comment]
> Hello Freek,
> 
> Are you still having this issue?

Hi Nolan, I have not yet been able to find time to install and test 1.5.0...

**Comment by NolanRogers** [comment]
> > Hello Freek,
> > Are you still having this issue?
> 
> Hi Nolan, I have not yet been able to find time to install and test 1.5.0...

OK no worries, when you do let us know if you are facing the same issue.

**Comment by FreekCornelis** [comment]
Hello @NolanRogers , I have installed Zowe 1.7.1 and do not have the issue anymore.
Thanks!
Closing issue

**Comment by NolanRogers** [comment]
@FreekCornelis ,
Awesome! If you find anything else please do raise another issue or if you have requests for enhancements to the web UI feel free to join our weekly squad call friday mornings 9am EST which can be found on the Zowe Dev Calendar here: https://lists.openmainframeproject.org/g/zowe-dev/calendar
