### ISSUE TITLE
Zowe Editor saves every new file with 700, not possible to change file mode

### ISSUE THREAD

**Issue by FreekCornelis** [zowe/zlux#236]
Enable the Zowe Editor to specify a file mode in the Save As dialog for a new USS file while saving, and provide an option to change the file mode for an existing file.   
When saving a new file in the Zowe Editor, the file seems to always get file mode 700.

**Comment by 1000TurquoisePogs** [comment]
While still true that the default is 700, it's now the case (has been for a few releases) that you can change permissions of files.
Right click -> "change mode/permissions..." will allow it.
