### ISSUE TITLE
Create message IDs for logs

### ISSUE THREAD

**Issue by NolanRogers** [zowe/zlux#238]
The required logging method is specified here:

https://github.com/zowe/zlux/wiki/Logging

and here

https://github.com/zowe/zlux-server-framework/pull/8

We need to go through our core framework and core plugins and revisit the logs so that we can create log IDs, and the english translation files.

**Comment by DivergentEuropeans** [comment]
Anything left from core to do? @1000TurquoisePogs  Otherwise, we should close this
