### ISSUE TITLE
Update server log levels

### ISSUE THREAD

**Issue by NolanRogers** [zowe/zlux#240]
Enhance server api to allow an admin to change server log verbosity utilizing the syntax of loglevels here: https://github.com/zowe/zlux/wiki/Logging#server-startup-logging-configuration

You should also write a message in the log declaring what log levels have been changed when they are, so people understand what they see later on.

**Comment by 1000TurquoisePogs** [comment]
Need to consult with ZSS writers to see what the status of this is for ZSS. This work is done for ZLUX I believe.
