### ISSUE TITLE
Add lifecycle hook for apps to update browser title

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#242]
Anything can set the browser tab title via `document.title`, but it can be chaotic to do this without knowing that your UI is in focus versus some other UI that may do the same.

If apps were informed of if they were in single-app-mode, or had been given focus or had focus removed, then they could know when it was appropriate to set the browser title.

Consider creating 4 objects:
1. A constructor object or global stating if single app mode is in use: That app can safely set the tab title at any time.
2. An event saying that the app has entered or left focus: It would be safe for the app to set the title.
3. An enhancement to the window setTitle action that takes that info to add to the tab's title... the Desktop could have a title such as "Zowe Desktop | 4 Apps | Editor - MY.DATASET(mem)"
4. The setTitle action could cache each Apps last title, so it can be restored upon event in 2

**Comment by std4lqi** [comment]
To add some information about how it would improve our app's user experience.

Our app's user will very likely open the app in multiple single-app windows to view/analyze multiple files at the same time. So it would be helpful to show the file name as part of browser title, with which user can jump to the correct tab from one to another quickly.

**Comment by 1000TurquoisePogs** [comment]
Also, aside from events, we should be adding some documentation that explains under what circumstances it is good user experience to be setting the browser title.

**Comment by NakulManchanda** [comment]
hi @std4lqi , 

if you are looking to implement this for your app

Please see PR for example
https://github.com/zowe/zlux-editor/pull/112/files

Please see how its implemented for code editor, we injected Angular2PluginWindowActions , and used this.windowActions.setTitle(newTitle);

Its documented here:
https://docs.zowe.org/stable/extend/extend-desktop/mvd-desktopandwindowmgt.html#window-actions

**Comment by NakulManchanda** [comment]
What we are planning is app developers are responsible for updating title for their window, and we will make browser tab title same as app in focus, let us know @std4lqi  if this will address your issue? 

To detect single app mode, right now we are using if(this.windowActions), to simplify this we will add new attribute in zoweZlux global - isSingleAppMode as my understanding of @1000TurquoisePogs  suggestion, this way in single app mode, app developers can simply use this conditional and use document.title to change their browser tab title.

**Comment by DivergentEuropeans** [comment]
I agree with @NakulManchanda and @1000TurquoisePogs here. Not a huge fan of including the currently open app count (because horizontal space is so limited) but something like

"Zowe Desktop | App name - optional info here"
or
"Zowe | App name - optional info here"
or
"Zowe | optional info here - App name"

sounds great to me. As @NakulManchanda mentioned, checking for single app mode is very easy now. I don't see the point in a global but we can do it this way if we want it cleaner and more future-proof.

**Comment by NakulManchanda** [comment]
hi @std4lqi , 

This is react app - check this commit especially - webClient/src/App.js for example
https://github.com/zowe/sample-trial-app/commit/dccd3e75a29fb6d6116a5fd29c3cc6106c03603b

Got pointed out to https://github.com/zowe/zlux-app-manager/blob/master/virtual-desktop/src/pluginlib/react-inject-resources.ts by @1000TurquoisePogs 

Thanks!

**Comment by NakulManchanda** [comment]
![image](https://user-images.githubusercontent.com/4791635/68043956-df279b00-fcac-11e9-8588-d162ccbd730b.png)

**Comment by std4lqi** [comment]
Hi @NakulManchanda, 

I checked out the code from Zowe `staging` branch, and `zlux-app-manager` from`set-desktop-title` branch in your repository.  It looks good.

Captured from Firefox. The first tab is from the regular Zowe Desktop, while the second is single-app mode.

<img width="553" alt="image" src="https://user-images.githubusercontent.com/31643673/68068425-8aa91c00-fd8f-11e9-8b7b-d0cfa61e3f1e.png">

Captured from Chome 78.0.3904.70 on macOS, the first one is from the regular Zowe Desktop too, which is good. However, the single-app mode didn't open my app in new tab, but Desktop. I can see the plugin ID is in URL. Is it a known issue with Chrome?

`https://localhost:5000/ZLUX/plugins/org.zowe.zlux.bootstrap/web/#?pluginId=my.app.id&showLogin=1`

<img width="553" alt="image" src="https://user-images.githubusercontent.com/31643673/68068440-bfb56e80-fd8f-11e9-985c-5f5169abd198.png">

Anyway, the browser title update works as expected. Many thanks for your working on this!
