### ISSUE TITLE
Verify and enable code linter

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zlux#25]
As part of CII Badge requirement:

The project MUST enable one or more compiler warning flags, a "safe" language mode, or use a separate "linter" tool to look for code quality errors or common simple mistakes, if there is at least one FLOSS tool that can implement this criterion in the selected language. [warnings] 
Examples of compiler warning flags include gcc/clang "-Wall". Examples of a "safe" language mode include JavaScript "use strict" and perl5's "use warnings". A separate "linter" tool is simply a tool that examines the source code to look for code quality errors or common simple mistakes. These are typically enabled within the source code or build instructions.

**Comment by jackjia-ibm** [comment]
The project MUST address warnings. [warnings_fixed] 
These are the warnings identified by the implementation of the warnings criterion. The project should fix warnings or mark them in the source code as false positives. Ideally there would be no warnings, but a project MAY accept some warnings (typically less than 1 warning per 100 lines or less than 10 warnings).

**Comment by 1000TurquoisePogs** [comment]
Each app (and the core code) implements the base Typescript lint rules: https://github.com/zowe/sample-angular-app/blob/master/webClient/tslint.json

Where, the Typescript base lint rules are at: https://github.com/zowe/zlux-app-manager/blob/master/virtual-desktop/plugin-config/tslint.base.json
