### ISSUE TITLE
UI: Introduce the ability to close and open and resize the JES tree view 

### ISSUE THREAD

**Issue by jordanCain** [zowe/zlux#259]
A user should be able to collapse the JES tree in order to see a full screen spool output file
A user should be able to go from a full screen spool output file back to the JES tree and apply filters only to show that job

A user should be able to drag and shrink side panel

**Comment by skurnevich** [comment]
Hi, I would like to take this one, thanks!

**Comment by NakulManchanda** [comment]
Feature is part of all explorers Zowe v1.15+
