### ISSUE TITLE
Job status field missing white space between id and status

### ISSUE THREAD

**Issue by jordanCain** [zowe/zlux#265]
For some cases the single white space character between a jobs ID and the status is missing.

see:
ZOWEZXC:STC31444 [ABEND S222]
ZOWEJC:STC32108[ACTIVE]

This is caused by a missing white space in the rendering of job status when jo job return code is available, specifically in the following else if block 
```
else if (job.get('status')) {
            return <div style={statusStyleActive}>[{job.get('status')}]</div>;
        }
```
In the JobInstance.js component file, renderJobStatus function

**Comment by Harry-Jia** [comment]
The PR is created for review.
