### ISSUE TITLE
Warning message in console "Unknown event handler property `onRequestClose`

### ISSUE THREAD

**Issue by jordanCain** [zowe/zlux#267]
The snackbar component is still using the onRequestClose prop which is no longer supported in material 1 and therefore is causing a warning in the web console.

**Comment by NakulManchanda** [comment]
@jordanCain can we close this? atleast in jes there is no ability to close notification now, so not able to reproduce this

**Comment by jordanCain** [comment]
@NakulManchanda yes no longer able to reproduce this so closing
