### ISSUE TITLE
New Interaction: Add ability to select multiple jobs in the job tree

### ISSUE THREAD

**Issue by jordanCain** [zowe/zlux#274]
Requires design but essential a user should be able to select multiple jobs so they can purge multiple jobs at once.

We could change the single click behaviour of a job label to be the select and then double click to expand and show the spool files. Alternatively we could introduce a collapse/expand button which controls the showing of spool files

**Comment by NakulManchanda** [comment]
this can be done across explorers
in mvs , uss also we should add the same capability

**Comment by NakulManchanda** [comment]
backend support is availble for jobs now 
https://github.com/zowe/jobs/pull/105
