### ISSUE TITLE
Notifications: Improve user information when authentication fails

### ISSUE THREAD

**Issue by jordanCain** [zowe/zlux#280]
Currently we just show the message "Authentication Failed" which is not very helpful, We should take the response from the validation API call and show that

**Comment by sladyn98** [comment]
Hello,  I would love to solve this issue, any tips on how can I proceed, this is my first contribution to the repository, Thanks

**Comment by jordanCain** [comment]
Hi @sladyn98 , this issue is currently blocked by https://github.com/zowe/explorer-api-common/issues/9 . The explorer UI's currently are unable to get sufficient information back from API calls to better improve the error message.

**Comment by sladyn98** [comment]
Thanks @jordanCain

**Comment by jordanCain** [comment]
Closing this as the implementation of SSO has allowed us to include better info from the gateway/auth endpoints
