### ISSUE TITLE
Security: Use of basic authentication is not acceptable in our production environment.

### ISSUE THREAD

**Issue by Wieb-Pilon** [zowe/zlux#281]
**Title:**
Use of basic authentication is not acceptable in our production environment.

**Problem:**
JES and MVS explorer via Zowe desktop currently use basic authentication to login to z/OS.
Our companies Chrome browser policy does not support basic authentication, AuthSchemes = ntlm,negotiate (and not basic).
Starting JES explorer (or MVS explorer) gives a "Unable to Authenticate" in an empty JES explorer frame, 
and an 401 on GET https://pweb0szvipa0.xxxxxxxxxx.nl:7554/api/v1/jobs/username when looking with developer tools.

See also: [https://openmainframeproject.slack.com/archives/CC08782AG/p1564573773018900](url)

**Possible Solution:**
Change the way authentication for JES and MVS explorer is used.
Possible use single sign on in Zowe desktop to insert userid/password or support other auth methods.

**Comment by jordanCain** [comment]
Migrating to use apimlAuthenticationToken has allowed us to remove basic auth
