### ISSUE TITLE
node.js V8 support

### ISSUE THREAD

**Issue by jthyssenrocket** [zowe/zlux#284]
Node V6 is no longer available for download (neither at ibm.com or through IBM ShopZ). 

When running Zowe 1.5 under Node.js V8 some icons are broken, the blue background is missing, and other similar problems. 
![2019-10-25 19_47_28-Zowe](https://user-images.githubusercontent.com/43121703/68457809-7470e500-0201-11ea-8471-f75541bada48.png)

**Comment by 1000TurquoisePogs** [comment]
Looks like this has to do with 8.16.1 specifically, but we support all the other versions of 8.
