### ISSUE TITLE
Navigator pane not sizeable

### ISSUE THREAD

**Issue by juergen-holtz** [zowe/zlux#286]
The navigator pane cannot be resized (Mac w/ Chrome) which leads to some ugly presentation (see attached screenshot) when dataset names are long.  The panes should be resizeable so that both the navigator and the editor can be enlarged.  A nice feature would be, if the navigator can be collapsed to leave the rest of the window for the editor.
<img width="444" alt="image" src="https://user-images.githubusercontent.com/28218471/46649229-97f9d400-cb98-11e8-9466-574b9dc10af0.png">

**Comment by NakulManchanda** [comment]
feature is added all three explorers since zowe v1.15
