### ISSUE TITLE
Unable to open member content after creating new member

### ISSUE THREAD

**Issue by jordanCain** [zowe/zlux#292]
Have some content open in editor
Create a new PDS member 
Try to open new newly created member
Content does not update

Seems to be fixed by opening content of a PS and then opening the new member but this may have an affect on save functionality

**Comment by skurnevich** [comment]
Hi Jordan, I would like to take this one, I can see stable reproduction of this behaviour in case of automatic syntax change on switching to newly created member.

**Comment by skurnevich** [comment]
Hi @jordanCain , 
It seems that I found the root issue, unfortunately it's in the **Orion Editior** 
_orion-editor-component/src/OrionEditor.js_ 

_changeSyntax_ function is checking editor content and gets it from the state if it is empty. 

`changeSyntax(syntax, content) {`
`if (!content) {`
`this.state.editorViewer.setContents(this.state.editorViewer.editor.getTextView().getText(), syntax);`
`<...>`
`}`

I can suggest that it has been done in case if this that function is called without a content, however, it is better to compare to undefined and null, or check if it is not a string then. 

Steps to reproduce: 
 - Open any dataset with content, just make sure that syntax is set to _Text_ then open any empty dataset member which name contains 'JCL', so the syntax will be automatically changed to JCL and this _changeSyntax_ function will take the previous content from state and replace real empty content. 
- Same bug could be reproduced by just deleting member content and changing the syntax without saving - previous content will be restored.

So anyway we have two ways from here 
Fix the MVS Explorer only by adding check to the  Editor.js and automatically change syntax only if there is any content. It will fix the initial issue only (second reproduce scenario will remain, however it looks not so harmful)
Or I could fix it in the Orion Editor by fixing condition of empty content (and maybe btw I can get rid of last componentWillReceiveProps there)

What do you suggest as a preferable way?

Thanks in advance.

**Comment by jordanCain** [comment]
Thanks for the investigation @skurnevich , The Orion editor is used in all 3 explorer apps so I think it would be most beneficial to fix in that. If you need assistance developing with the Orion Editor please reach out to me on slack

**Comment by skurnevich** [comment]
Hi Jordan, 

I have created a [PR](https://github.com/zowe/orion-editor-component/pull/35)
Please review if it is fine. Thanks.

**Comment by NakulManchanda** [comment]
trid these in 1.13 rc1
Have some content open in editor
Create a new PDS member
Try to open new newly created member

seems to work now
