### ISSUE TITLE
MVS Explorer url encoding issue - valid Z filename symbols like #, semicolon rejected by backend

### ISSUE THREAD

**Issue by NakulManchanda** [zowe/zlux#300]
While trying to open member **#INFO",#01PAGE** of pds zowe.jcl  , liberty API return with status code 500 and error message
*"The request was rejected because the URL contained a potentially malicious String "%25" "*
and upon sending **#** instead or **%25**, receive blank **[]** as response

**Comment by AdarshdeepCheema** [comment]
This issue is fixed
