### ISSUE TITLE
Pathname is displayed with double-slash

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zlux#319]
If you select pathname `/` i.e. root, then click on directory S0W1, the pathname display changes to `//S0W1`

The same thing happens for any directory under root.

**Comment by Martin-Zeithaml** [comment]
Hi, this is general behavior, if you manually type the path with trailing slash, clicking on subdirectory causes appending the slash and name of the directory. Same thing will happen if you click on file.
It seems, that small change in RenderUSSChild is needed only, just append slash only if the path does not end with slash.
If no objections to solution, assign this issue to me.
