### ISSUE TITLE
Update NPM packages

### ISSUE THREAD

**Issue by jordanCain** [zowe/zlux#326]
Some NPM packages have become out of date/stale versions, we need to review and update necessary packages.

**Comment by grlwholifts** [comment]
Hi, can I take this up? @jordanCain 
Also, I would need a little more details about the same. For eg: which all zlux sub-folders do I need to consider?

**Comment by jordanCain** [comment]
Hi @grlwholifts , thanks for your interest in this item, I want to be clear here that the explorer-uss app is not based on zlux, it is delivered and surfaced as an IFrame app, this means that it has no dependancy on zlux. This issues is focusing only on the dependecies in the explorer-uss package.json (https://github.com/zowe/explorer-uss/blob/zosmf_convert/package.json). The explorer-mvs and explorer-jes apps have already been updated, an example of this recently would be the update of the react dependency from 15 to 16, https://github.com/zowe/explorer-mvs/pull/97/files . You should note that this is quite a substantial task and perhaps not a great first issue.

**Comment by grlwholifts** [comment]
Okay @jordanCain thankyou for mentioning this. Could you point me to some of the other good first issues?

**Comment by jordanCain** [comment]
@grlwholifts  Sure, here's a link to newly labeled good first issues https://app.zenhub.com/workspaces/community-5c93e02fa70b456d35b8f0ed/board?labels=good%20first%20issue&repos=143049506,141316148,144600062,144599701,166097436,168378275

**Comment by NakulManchanda** [comment]
@jordanCain is it still an issue?

**Comment by jordanCain** [comment]
@NakulManchanda This is an ongoing issue really, you can chose how you want to manage it but it's important to make sure we aren't on multiple year old packages so that we can still apply maintenance if necessary
