### ISSUE TITLE
Allow an App to declare it can't be open more than once

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#332]
Not unheard of on other UIs: some programs don't want to open up multiple instances, either due to limitation or preference.
Allow App to hint at runtime, or default from pluginDef, that it would like to be excluded from the ability to be opened multiple times at once.
In this case, ideally the "open new" menu option is grey instead of missing, so that it is known that it's intentionally not able to be opened multiple times.

**Comment by NolanRogers** [comment]
Cancelling
