### ISSUE TITLE
Extra environment variables (_TAG_REDIR_XXX) required to run Zowe with node.js v12 Beta

### ISSUE THREAD

**Issue by kathysychan** [zowe/zlux#333]
I tested the node.js for Z v12 external beta with Zowe 1.6.0. 

Here's the location of Node.js for Z beta:

https://www.ibm.com/us-en/marketplace/sdk-nodejs-compiler-zos

I found that the Zowe JES/MVS/USS explorer icons do not come up in the Zowe desktop because of encoding problem. 

The Zowe configure code called
EXPLORER_PLUGIN_BASEURI=$($NODE_BIN -e “process.stdout.write(require(‘./package.json’).config.baseuri)“)
but the responses is now coming back in a different codepage.

This result in the directory name of the JES/MVS/USS explorer being in another code page and strings in JSON file in wrong code page. Here’s the JSON file for the JES explorer:
{
 “identifier”: “?ÊÅ:?ÏÁÁÌø%?ÊÁÊ¦ÁË“,
 “apiVersion”: “1.0.0",
 “pluginVersion”: “1.0.0",
 “pluginType”: “application”,
 “webContent”: {
   “framework”: “iframe”,
   “startingPage”: “index.html”,
   “launchDefinition”: {
     “pluginShortNameKey”: “¢áëáÌø%?ÊÁÊ“,
     “pluginShortNameDefault”: “¢áëáÌø%?ÊÁÊ“,
     “imageSrc”: “images/explorer-JES.png”
   },
   “descriptionKey”: “”,
   “descriptionDefault”: “”,
   “isSingleWindowApp”: true,
   “defaultWindowStyle”: {
     “width”: 1400,
     “height”: 800
   }
 }
}

We were then told by the node.js team that version 12 is no longer an EBCDIC executable like version 8. They suggested the setup script to include setting up the _TAG_REDIR... envvars with:

export _TAG_REDIR_ERR=txt
export _TAG_REDIR_IN=txt
export _TAG_REDIR_OUT=txt

After setting those export statements, running zowe-configure.sh do not generate directory and contents with the wrong code page anymore. The Zowe JES/MVS/USS explorer now comes up properly in the MVD and they function properly.

This behaviour is documented in the Node.js V12 KC docs here: https://www.ibm.com/support/knowledgecenter/en/SSTRRS_12.0.0/com.ibm.nodejs.zos.v12.doc/tag.htm

According to node.js team, it is also advisable to make sure all the text files you used in node-js (for example: .js .json) are tagged in CCSID 819 (i.e. chtag -tc819 ) and consist of well-formed utf-8 characters only. Your application benefits by in skipping unnecessary conversions at run time. For binary files you should tag them with CCSID 65535 (binary).

Another thing I noticed is the nodeServer.log file in zlux-app-server/logs cannot be displayed on zOS. I needed to change it to UTF-8 to see the logs.

@Joe-Winchester FYI

Here's the screen shot of the Zowe directory:

![image](https://user-images.githubusercontent.com/16210114/68867822-7553bc00-06c4-11ea-97f4-811a8925f319.png)

**Comment by kathysychan** [comment]
Exporting " _TAB_REDIR_ERR/IN/OUT=txt" in .zowe-profile works well with Zowe 1.6.0 and Node.js v12.13 (external Beta). I was able to get JES Explorer to come up OK. However, when I do the same for Zowe 1.7.0-RC1 and Node.js v12.13, I got:

{“messages”:[{“messageType”:“ERROR”,“messageNumber”:“MFS0103E”,“messageContent”:“The endpoint you were looking for ‘/ui/v1/explorer-jes/’ could not be located”,“messageKey”:“apiml.common.endPointNotFound”}]}

When that happened, @jordanCain noticed that there were a lot of strange characters (wrong encoded strings) in the output of ZOWESVR. After adding these exports to run-zowe.sh, then the problem goes away and the JES Explorer comes up ok.

Note that this problem with Zowe 1.7.0 RC1 does not happen with Node.js v8.16 (since these exports are not needed for that version).

**Comment by kathysychan** [comment]
Another point to note is the nodeServer.log in zlux-app-server/logs folder does not display in cp1047 code page. I had to switch to UTF-8 to have the log properly readable.

**Comment by kathysychan** [comment]
I also tested Node.js v12 beta with the Zowe post-1.7.0 12/02 development driver. I found that just putting these lines in .zowe-profile is not enough to avoid the problem when running zowe-configure.sh:

export _TAG_REDIR_ERR=txt
export _TAG_REDIR_IN=txt
export _TAG_REDIR_OUT=txt

We then found that the reason is zowe-configure.sh has these lines:

export _TAG_REDIR_IN=""
export _TAG_REDIR_OUT=""
export _TAG_REDIR_ERR=""

According to @stevenhorsman, @Joe-Winchester added those changes  in order to address issues customers had with conversion of files: https://github.com/zowe/zowe-install-packaging/issues/142

To continue with testing Zowe with Node.js v12 Beta, we removed those TAG_REDIR exports in zowe-configure.sh. This enable zowe-configure to properly install the MVS/JES/USS Explorer with Node.js v12 Beta and let the export of TAG_REDIR to txt take effect (from .zowe-profile). We would achieve the same result by putting those lines in zowe-configure.sh.

Note that this is just short term workaround since whatever problem Joe was trying to fix in issue 142 could be back. Zowe development team need to find a solution that works with both the customer file conversion issue and what is expected by Node.js v12.

In addition, to work with Zowe 12/02 driver, we added these TAG_REDIR exports in instance.env so that run-zowe.sh has those settings. We could also put those exports in run-zowe.sh to achieve the same effect.

**Comment by John-A-Davies** [comment]
Node.js may use particular settings of these shell variables, to save time by avoiding on-the-fly file codepage conversion.  However, during Zowe install time, we may need different settings.  Their meanings are explained in "UNIX System Services Command Reference - IBM".  I've pasted Table 30 from that document here:

Shell variables for automatic conversion
When the shell is redirecting standard input, standard output , or standard error, it will default to no automatic conversion of tagged files, and no tagging of files created by the redirection. The following shell variables will override this behavior:

Table 30: Shell variables for automatic conversion (sh command)

_TAG_REDIR_IN=TXT Redirected standard input will override the file's text flag (TXTFLAG),
treating it as if it were tagged as:
TXTFLAG = ON, CCSID = existing file tag CCSID
This has no effect if CCSID = 0.

_TAG_REDIR_IN=BIN Redirected standard input will override the file's TXTFLAG, treating it
as if it were tagged as:
TXTFLAG = OFF, CCSID = existing file tag CCSID
This effectively disables automatic conversion.

_TAG_REDIR_OUT=TXT Redirected standard output will be tagged as:
TXTFLAG = ON, CCSID = program CCSID at the time of the first write
(if not already tagged)

_TAG_REDIR_OUT=BIN Redirected standard output will be tagged as:
TXTFLAG = OFF, CCSID = program CCSID at the time of the first write
(if not already tagged)

_TAG_REDIR_ERR=TXT Redirected standard error will be tagged as:
TXTFLAG = ON, CCSID = program CCSID at the time of the first write
(if not already tagged)

_TAG_REDIR_ERR=BIN Redirected standard error will be tagged as:
TXTFLAG = OFF, CCSID = program CCSID at the time of the first write
(if not already tagged)


The -t option on the `chtag` command
Indicates that the specified file contains pure (uniformly encoded) text data. Used alone, this option sets txtflag = ON

**Comment by ccw-1** [comment]
Explanation:
node v12 is an ascii-mode program, node v6 and node v8 are ebcdic-mode programs. 

The three _TAG_REDIR_... environment variables are used by /bin/sh to tag the 
stdios pipes they created to communicate with the children processes they spawned, 
if they are not set to TXT, the pipes created are un-tagged and data is transferred 
as-is. That is why you have unreadable data in an /bin/sh script, because node-v12 
talks in unicode, not ebcdic. When these environment variables are set to TXT, the stdio pipes 
created for the children are tagged CCSID 1047, automatic code-page conversion happens
at the read-write level to and from the pipes if they do not match the CCSID of 
the program it launches. In this case it is node (v12) which is an ascii program.

**Comment by 1000TurquoisePogs** [comment]
Implemented in https://github.com/zowe/zlux-app-server/pull/96
