### ISSUE TITLE
Add option to download JCL used to submit job

### ISSUE THREAD

**Issue by jordanCain** [zowe/zlux#335]
We should have a context menu option on a jobInstance to download the JCL that was used to submit a job.

**Comment by NakulManchanda** [comment]
just one comment:
GETJCL may not always be same JESJCL

![image](https://user-images.githubusercontent.com/4791635/68968162-ecb24a00-07af-11ea-804e-32402fa49e48.png)

**Comment by NakulManchanda** [comment]
@jordanCain i think we have this ability now, concatenated view

**Comment by jordanCain** [comment]
@NakulManchanda No we have the ability to view the jcl used to submit a job but not download it. This issue was to cover adding a context menu entry to a job instance context menu to download not just view

**Comment by NakulManchanda** [comment]
ok, thanks for reviewing, got should be easy to replicate as we can already download children now.

**Comment by Martin-Zeithaml** [comment]
Hi, I started working on this issue.
