### ISSUE TITLE
Create a Lock API for Datasets

### ISSUE THREAD

**Issue by NolanRogers** [zowe/zlux#353]
In ways that are appropriate to the purpose of being able to read, write, delete, rename datasets & members.

Need foundational **locking service ** to implement write(s) in ZSS:
- to **lock a resource**
- to **free/unlock a resource**
- to **check if lock exists**
- to **calculate or get content hash**

Some more research done in this regard:
- **optimistic locking approach**

**An optimistic locking approach:**
- fetch content, and calculate **content hash** 
- append content hast to response headers as **e-tag**
- let user modify content
- fetch and calculate content hash again, and compare it with e-tag of modified file
- if same, grab lock , else throw error
- replace content with modified content, and save
- and  free, lock

**RSE Dataset locking mechanism:**
https://www.ibm.com/support/knowledgecenter/en/SSBDYH_3.2/com.ibm.zexpl.config.hostconfigref.doc/topics/dataset_lock_owner.html

**Comment by 1000TurquoisePogs** [comment]
This ticket was premature, and a solution that plays well with ispf is needed. More tickets will be made.

**Comment by NakulManchanda** [comment]
Progress is being tracked with story
https://github.com/zowe/zlux/issues/498
Locking functionality is implemented
- Work is being done on releasing lock on configurable timeout
  https://github.com/zowe/zlux/issues/570
