### ISSUE TITLE
Configure zLux/Desktop behind API gateway at startup 

### ISSUE THREAD

**Issue by jordanCain** [zowe/zlux#354]
Currently zLux/Desktop can be configured to be behind the Zowe api gateway but this requires modifying the zluxServer.json file manually. We should look to add this as an install time configuration so a user doesn't have to manually edit files after installing and configuring. 

@1000TurquoisePogs We've discussed this a few times on the weekly webUI squad call so thought I'd raise an issue to track plan when we might do this. 
@NolanRogers FYI

**Comment by NolanRogers** [comment]
@1000TurquoisePogs I thought we had an issue already on GitHub, but Jordan and I couldn't find it. Thank you @jordanCain for raising this.

**Comment by 1000TurquoisePogs** [comment]
This is done in staging, but also is tracked via https://github.com/zowe/api-layer/issues/19
So I'm going to close this as a duplicate.
