### ISSUE TITLE
ZOWESVR does not issue a useful UP message

### ISSUE THREAD

**Issue by FreekCornelis** [zowe/zlux#355]
Version: 1.7.1
We use IBM System Automation to start/stop STCs and use specific messages issued by the STCs as indication of their 'UP' status. ZOWESVR does not issue a specific UP message to SYSLOG, so we have to rely on standard the 'IEF403I STARTED' message.
However, IEF403I is issued at the start and it takes a while before ZOWESVR is fully functional.
The XMEM server does issue a useful UP msg: 'ZWES0109I Core server ready'

Please have ZOWESVR issue also a message to SYSLOG when startup has completed.
Thanks

**Comment by Joe-Winchester** [comment]
Tks @FreekCornelis for creating this issue.  We've heard this from other folks who want to know when the ZOWESVR STC has all of its parts up and running and functional.   I've added the LTSR label which flags that we're hoping to address this before we deliver our Long Term Support release and it'll get included in our zenhub boards, ...

**Comment by 1000TurquoisePogs** [comment]
By the way @FreekCornelis and others that are curious: this is now in the app server. I believe it was in 1.8
The app server has a progress indicator and final message when at 100%:

```
2020-03-16 12:00:33.990 <ZWED:9739> me INFO (_zsf.install,index.js:261) ZWED0290I - Plugin (org.zowe.configjs) loaded. Successful: 100% (15/15) Attempted: 100% (15/15)
2020-03-16 12:00:33.990 <ZWED:9739> me INFO (_zsf.install,index.js:337) ZWED0031I - Server is ready at https://myhost:myport, Plugins successfully loaded: 100% (15/15)
```

**Comment by FreekCornelis** [comment]
Hi @1000TurquoisePogs , nice progress indicators, I see them in our instances (1.9.0)
ZWED0290I - Plugin (org.zowe.api.catalog) loaded. Successful: 95% (20/21) Attempted: 100% (21/21) 
ZWED0032I - Server is ready at https://0.0.0.0:8168, Plugins successfully loaded: 95% (20/21)     
I have to find out what the failing one is.

However, what I am still missing (unless the failing plugin is causing it) is that I do not see a proper UP message being sent to the MVS console. That is, for System Automation for z/OS to be notified of the UP status, it needs to receive a  MVS message via the SubSystem Interface. We only see the following MVS messages being issued:

![image](https://user-images.githubusercontent.com/55885539/77295166-bba9cf00-6ce5-11ea-8809-3e3d61af1e69.png)

The IEF403I message is issued at the start of the initialization, hence much too early.  The XMEM instance for instance issues 

![image](https://user-images.githubusercontent.com/55885539/77295310-ff9cd400-6ce5-11ea-9018-da122314ba60.png)

where the 
       ZWES0109I Core server ready 
message is received by System Automation for z/OS in order to set the status to UP.

Could you please re-open this issue and have it processed?
cc @NolanRogers  @Joe-Winchester

**Comment by Joe-Winchester** [comment]
closing and linking to  https://github.com/zowe/docs-site/issues/1535 (that introduces a 1.19 doc section with more info on how to track startup of the individual Zowe components)
