### ISSUE TITLE
Paging/partial loading of files  

### ISSUE THREAD

**Issue by NakulManchanda** [zowe/zlux#358]
User use JES to open logs/STDOUT for currently active job, we should make partial updates to text editor content, and append at bottom as Job writes more logs. 
tn3270 select feature refreshes and append at bottom on hitting enter when browsing job output file, we should have simillar expereince in jes explorer

1) **infinite scroll for text editor area**, it may need pointed arrow which can be clicked to fetch next lines, or just scroll action at bottom can trigger fetch

2)  **backend api extension** - to support partial fetch, so one scheme could be
 -- add next counter in output, {content:".......", next:"1001"} to keep track of line numbers already sent, sent next 1000 starting 1001, and if we have 1300 lines at next fetch, send  {content:".......", next:"1301"}, and next thousand of next fetch

Sample call:
GET jes/file?start=1 && size=10000 
to fetch first ten thousand lines

**Comment by NakulManchanda** [comment]
Unable to fetch zowe job logs when API ML
LOG_LEVEL=debug

This can help improve the experience for extremely large files
https://github.com/zowe/zlux/issues/358

**Comment by NakulManchanda** [comment]
https://github.com/zowe/zowe-install-packaging/issues/1496

**Comment by AdarshdeepCheema** [comment]
as the explorer-JES is moved to zOSMF APIs, we tried using the API as below:
 atlasFetch(`zosmf/restjobs/jobs/${encodeURLComponent(jobName)}/${jobId}/files/${fileId}/records`,
            { credentials: 'include', headers: { 'X-CSRF-ZOSMF-HEADER': '*', 'X-IBM-Record-Range': `${startLine}- ${startLine + 50000}` }})
            IT TOOK 2 MINS TO GET THE FILE WITH 1000000 LINES
            WHEN WE TRIED TO PICK 100000 LINES AT ONCE THEN IT TOOK 58 SECS
            WITHOUT USING X-IBM-Record-Range, AND FETCHING THE FILE ALL AT ONCE TAKES 35 SECS.
            SO CLOSING THIS DUE TO PERFORMANCE ISSUE.
