### ISSUE TITLE
Can't Login to Zowe. Need info on this error.

### ISSUE THREAD

**Issue by jimmschlo89** [zowe/zlux#360]
Hello!

I can't login to Zowe. I think it's the cross memory server.

Where can I find more specific information about this error:
![image](https://user-images.githubusercontent.com/49279914/71751868-9cb44300-2e42-11ea-9158-224eecc53bcb.png)

**Comment by NolanRogers** [comment]
@1000TurquoisePogs @fkovinAtRocket @ifakhrutdinov : Can you guys help here?

**Comment by ifakhrutdinov** [comment]
@jimmschlo89 have you started the ZIS server? (usually `ZWESIS01`)

**Comment by jimmschlo89** [comment]
@ifakhrutdinov I was able to get past that problem. I have a new issue that I just posted about. It's similar to one you fixed for someone else, but not quite the same.
