### ISSUE TITLE
install-app.sh does not deploy extensions

### ISSUE THREAD

**Issue by kiril-ibm** [zowe/zlux#362]
The reason is components/app-server/share/zlux-app-server/defaults/plugins/ is readonly. Please see logs for details:

/opt/zowe/zowe-1.8.0/components/app-server/share/zlux-app-server/bin/install-app.sh /opt/zowe/zowe-1.8.0/components/extensions/com.ibm.addi.web.mvd/addi-web-mvdapp
Verifying node exists
/usr/lpp/IBM/cnj/IBM/node-v6.17.0-os390-s390x/bin/node is /usr/lpp/IBM/cnj/IBM/node-v6.17.0-os390-s390x/bin/node
Running app-server plugin installer. Log=/dev/null
utils_path=/opt/zowe/zowe-1.8.0/components/app-server/share/zlux-server-framework/utils
app_path=/opt/zowe/zowe-1.8.0/components/extensions/com.ibm.addi.web.mvd/addi-web-mvdapp
json_path=/opt/zowe/zowe-1.8.0/components/app-server/share/zlux-app-server/defaults/serverConfig/server.json
2020-01-09 17:37:15.401 <ZWED:67108937> IBMUSER INFO (_zsf.utils,native array.js:958) Resolved path: /opt/zowe/zowe-1.8.0/components/extensions/com.ibm.addi.web.mvd/addi-web-mvdapp -> /opt/zowe/zowe-1.8.0/components/extensions/com.ibm.addi.web.mvd/addi-web-mvdapp
2020-01-09 17:37:15.403 <ZWED:67108937> IBMUSER INFO (_zsf.utils,native array.js:958) Resolved path: /opt/zowe/zowe-1.8.0/components/app-server/share/zlux-app-server/defaults/serverConfig/server.json -> /opt/zowe/zowe-1.8.0/components/app-server/share/zlux-app-server/defaults/serverConfig/server.json
2020-01-09 17:37:15.404 <ZWED:67108937> IBMUSER INFO (_zsf.utils,native array.js:958) Resolved path: ../defaults/plugins -> /opt/zowe/zowe-1.8.0/components/app-server/share/zlux-app-server/defaults/plugins
2020-01-09 17:37:15.406  Registering App (ID=com.ibm.addi.web.mvd) with App Server
App extracted but not registered to App Server due to write fail. Error=EACCES: permission denied, open '/opt/zowe/zowe-1.8.0/components/app-server/share/zlux-app-server/defaults/plugins/com.ibm.addi.web.mvd.json'
Plugin install completed with rc=0

**Comment by 1000TurquoisePogs** [comment]
Yes, `components/app-server/share/zlux-app-server/defaults/plugins/` is read-only.
This error can happen if  INSTANCE_DIR folders do not exist yet, since they are only created on the first server run. So if you run `install-app.sh` before first run, you could get this error.
There are 2 workarounds
1. Only run `install-app.sh` after running the server for the first time

OR

2. Create the folder `$INSTANCE_DIR/workspace/app-server/plugins` and specify it as the second argument to `install-app.sh`, such as `install-app.sh /opt/zowe/zowe-1.8.0/components/extensions/com.ibm.addi.web.mvd/addi-web-mvdapp $INSTANCE_DIR/workspace/app-server/plugins`

**Comment by kiril-ibm** [comment]
1) I do run it after few restarts. 
2) What would the 2nd option do ?

**Comment by 1000TurquoisePogs** [comment]
If the second option is not present, the script tries to find the right plugins folder. However, it finds the defaults folder, which is read-only on a production install.... it can be writable for a dev environment.

So, the second option makes the script skip checks and just use the folder you specify to place the JSON in. That folder must exist first.

**Comment by kathysychan** [comment]
Will this be in the Zowe documentation? I can see it's a very common problem users might run into.

**Comment by 1000TurquoisePogs** [comment]
Yes, but also I expected `install-app.sh` to exist in $INSTANCE_DIR/bin, and I don't see it. So, I will make a fix for that. It has more intuitive behavior in that location because it picks up instance.env which allows it to find the right folder by default. That must be why number 1 did not work for you.

**Comment by kiril-ibm** [comment]
ok, when is ETA for the fix ? I am running installDir/components/app-server/share/zlux-app-server/bin/install-app.sh now

**Comment by 1000TurquoisePogs** [comment]
I will link a fix today, only small changes are needed.

**Comment by 1000TurquoisePogs** [comment]
This should work, and is part of the PR 966 above. https://zowe.jfrog.io/zowe/libs-snapshot-local/org/zowe/1.8.0-PR-966/zowe-1.8.0-pr-966-2-20200109223821.pax

What changed: now install-app.sh should work without needing to run the server the first time, but also will work after.

**Comment by kiril-ibm** [comment]
@1000TurquoisePogs 
1) The change is still not in nightly builds.

2) I am having different issue. After installing successfully extension I do not see it in MVD. Please see installl log:

Starting process 'command '/bin/sh''. Working directory: /opt/zowe/zowe-1.8.0/components/app-server/share/zlux-app-server/bin Command: /bin/sh -L -c /opt/zowe/zowe-1.8.0/components/app-server/share/zlux-app-server/bin/install-app.sh /opt/zowe/zowe-instance-dir/workspace/extensions/com.ibm.addi.web.mvd/addi-web-mvdapp /opt/zowe/zowe-instance-dir/workspace/app-server/plugins
Successfully started process 'command '/bin/sh''
Verifying node exists
/usr/lpp/IBM/cnj/IBM/node-v6.17.0-os390-s390x/bin/node is /usr/lpp/IBM/cnj/IBM/node-v6.17.0-os390-s390x/bin/node
Running app-server plugin installer. Log=/dev/null
utils_path=/opt/zowe/zowe-1.8.0/components/app-server/share/zlux-server-framework/utils
app_path=/opt/zowe/zowe-instance-dir/workspace/extensions/com.ibm.addi.web.mvd/addi-web-mvdapp
plugin_dir=/opt/zowe/zowe-instance-dir/workspace/app-server/plugins
2020-01-10 15:23:28.518 <ZWED:67108871> IBMUSER INFO (_zsf.utils,native array.js:958) Resolved path: /opt/zowe/zowe-instance-dir/workspace/extensions/com.ibm.addi.web.mvd/addi-web-mvdapp -> /opt/zowe/zowe-instance-dir/workspace/extensions/com.ibm.addi.web.mvd/addi-web-mvdapp
2020-01-10 15:23:28.521 <ZWED:67108871> IBMUSER INFO (_zsf.utils,native array.js:958) Resolved path: /opt/zowe/zowe-instance-dir/workspace/app-server/plugins -> /opt/zowe/zowe-instance-dir/workspace/app-server/plugins
2020-01-10 15:23:28.523  Registering App (ID=com.ibm.addi.web.mvd) with App Server
2020-01-10 15:23:28.527  App com.ibm.addi.web.mvd installed to /opt/zowe/zowe-instance-dir/workspace/extensions/com.ibm.addi.web.mvd/addi-web-mvdapp and registered with App Server
Plugin install completed with rc=0

**Comment by kiril-ibm** [comment]
@1000TurquoisePogs I see in app-server log:
error while parsing Couldn't open '/opt/zowe/zowe-instance-dir/workspace/app-server/plugins/com.ibm.addi.web.mvd.json': /opt/zowe/zowe-instance-dir/workspace/app-server/plugins
error while parsing Couldn't open '/opt/zowe/zowe-instance-dir/workspace/app-server/plugins/com.ibm.zdt.json': /opt/zowe/zowe-instance-dir/workspace/app-server/plugins

which is due to this
-rw-r-----   1 IBMUSER  OMVS         147 Jan 14 12:14 com.ibm.addi.web.mvd.json
-rw-r-----   1 IBMUSER  OMVS         117 Jan 14 12:15 com.ibm.zdt.json

what ownership/permissions these have to be ?

**Comment by 1000TurquoisePogs** [comment]
The user who runs the script and the user who runs the server should be in the same group so that they can read the files that are included there.

**Comment by NolanRogers** [comment]
Closing as out-dated. Please reopen if you facing another issue
