### ISSUE TITLE
File not found error in github wiki for staging branch of zlux-app-server

### ISSUE THREAD

**Issue by pranav1698** [zowe/zlux#363]
Trying to set up the virtual desktop in my machine and I am getting  `app-server.sh` not found error while following the instructions given here: https://github.com/zowe/zlux-app-server/blob/staging/README.md.
This may be due to `app-server` getting renamed to `node-server`.
I would like to work on this issue.

**Comment by 1000TurquoisePogs** [comment]
Hello, thanks for the comment.
`app-server` files are new names in our, it replaced `nodeServer`.
If you are seeing `nodeServer` instead, the likely cause is that when checking out staging branch, you have some repositories on master instead. Master will soon be updated to have the new names, but meanwhile if you want to get the latest of our code for development, staging is always good for development and the way you can get the latest is by doing a `git checkout staging` for each repo you have. If you are in the zlux repo, which has other repos as submodules, you can also do this action in bulk via `git submodule foreach "git checkout staging"`
Hope that helps!

**Comment by pranav1698** [comment]
So can we change app-server to nodeServer in staging branch for now,
or checkout `staging` branch instead of `master` in the wiki mentioned in the staging branch
This would help in the future for other developers

**Comment by 1000TurquoisePogs** [comment]
Yes, in 1 or 2 weeks this will not be an issue anymore - we are in the middle of a big change to documentation - we will be moving the content from `staging` to `master` on our next release, which is what we do every release. I just wanted to point some people to `staging` temporarily because the new steps are in my opinion less confusing than what we currently have on `master`.

**Comment by pranav1698** [comment]
Okay, I will open a PR with the above changes so that users don't get an error for now
