### ISSUE TITLE
Create a component validation script for explorer-jes

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zlux#364]
Create a /bin/validate.sh script to fit into the componentisation scheme to make the server check things like ports, keystore info, the static api-def directory accessibility.
The explorer-jes version of https://github.com/zowe/api-layer/blob/master/zowe-install/src/main/resources/component-scripts/validate.sh

**Comment by NakulManchanda** [comment]
https://github.com/zowe/zlux/issues/365
https://github.com/zowe/zlux/issues/366

same for other explorers

**Comment by NakulManchanda** [comment]
@stevenhorsman 
should we keep these open?

we recently added these, not as many checks as mentioned in this issue though

https://github.com/zowe/explorer-jes/pull/181
https://github.com/zowe/explorer-mvs/pull/117
https://github.com/zowe/explorer-uss/pull/78

**Comment by stevenhorsman** [comment]
The work hasn't been done - IIRC it just does a node check?

**Comment by NakulManchanda** [comment]
yes no other update in that script, thanks for verifying.

**Comment by 1000TurquoisePogs** [comment]
Closed due to inactivity
This seems no longer relevant in v2.
