### ISSUE TITLE
Create a component validation script for explorer-mvs

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zlux#366]
Create a /bin/validate.sh script to fit into the componentisation scheme to make the server check things like ports, keystore info, the static api-def directory accessibility.
The explorer-mvs version of https://github.com/zowe/api-layer/blob/master/zowe-install/src/main/resources/component-scripts/validate.sh

**Comment by 1000TurquoisePogs** [comment]
Closed due to inactivity
This seems no longer relevant in v2.
