### ISSUE TITLE
MVS explorer using deprecated react methods as a result of migration from 15 to 16

### ISSUE THREAD

**Issue by jordanCain** [zowe/zlux#368]
After the migration to react 16 we are seeing warning in the browser console log about using deprecated functions. 

e.g. componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

Migration instructions are provided by React

**Comment by grlwholifts** [comment]
Hi! I would like to take this up. @jordanCain

**Comment by skurnevich** [comment]
Hi Jordan, 

I have investigated issue #292, it wasn't straightforward to reproduce, and i believe that it could be related to these deprecated methods usage, so I would like to take this issue. 

Thanks

**Comment by jordanCain** [comment]
@skurnevich From memory I think #292 was happening prior to the react upgrade, I also remember finding it difficult to reproduce consistently. I will assign this issue to you, thanks!

**Comment by skurnevich** [comment]
@jordanCain Hi, I have created a pull request [ #119 ](https://github.com/zowe/explorer-mvs/pull/119), however it complains that SonarCloud Code Analysis check is failed, and I'm not sure what should i do with it. I'll appreciate any help, thanks.

**Comment by skurnevich** [comment]
Hi @NakulManchanda, checked current master branch in dev mode and there are no warnings about deprecated react methods, only one warning left is to React.createFactory(), but it is about one of material-ui components.
So I believe this one could be closed, thanks.

**Comment by NakulManchanda** [comment]
thanks @skurnevich , closing issue as resolved with v1.13
