### ISSUE TITLE
Unable to fetch information in explorers standalone using Zowe 0.9.1

### ISSUE THREAD

**Issue by NayerNajafi** [zowe/zlux#37]
Explorers don't fetch information while working standalone. 
(Fetch Datasets failed for A99904)
messages.log in explorer-server has some error for java classes:
**java.util.MissingResourceException: Can't find bundle for base name com.ibm.atlas.webservice.messages, locale en_US**
**SRVE0777E: Exception thrown by application class 'java.lang.J9VMInternals.ensureError:146'**

**Comment by jordanCain** [comment]
No longer an issue in 1.* as liberty based APIs have been re written and no longer provide this language translation/bundle
