### ISSUE TITLE
Set refresh icon to loading icon when fetching the members of a partitioned dataset.

### ISSUE THREAD

**Issue by jordanCain** [zowe/zlux#370]
Currently when a user clicks on a partitioned dataset there is no indication that a fetch is happening so they may click again which would untoggle the node and hide any members that come back. 

Setting the refresh icon to the loading icon would make the UX better.

**Comment by jordanCain** [comment]
@sladyn98 This is a good first issue if you're still looking to participate.

**Comment by sladyn98** [comment]
Definitely, I could give it a shot :)

**Comment by sladyn98** [comment]
@jordanCain 
```
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:zowe/zlux-app-manager.git' into submodule path '/home/sladyn/OMP-20/zlux/zlux-app-manager' failed
```
I am unable to pull in the submodules

**Comment by jordanCain** [comment]
@sladyn98 The mvs explorer can actually run outside of the Zowe desktop/zlux, you should be able to clone just zowe/explorer-mvs repo to get going and follow the readme there. One thing to bear in mind is that active development happens on the staging branch. 

If you want to work within the desktop then you should be able to follow the readme in https://github.com/zowe/zlux-app-server .

**Comment by pranav1698** [comment]
@sladyn98 are you working on the issue,

**Comment by sladyn98** [comment]
@pranav1698 Yeah u was looking to solve it in the upcoming days, but if you already have a solution for it in mind then by all means go ahead :smile:

**Comment by pranav1698** [comment]
I am not able to run the dev app in my local machine, 
due to issues mentioned here https://github.com/zowe/zlux/issues/369#issuecomment-583734508
Can you help me with that?

**Comment by sladyn98** [comment]
Apologies, I am not solving this issue anymore you could take a shot @pranav1698

**Comment by skurnevich** [comment]
Hi, I would like to take this one for beginning if no-one currently working on it

**Comment by jordanCain** [comment]
@skurnevich Please go ahead, reach out if you need any help 👍

**Comment by skurnevich** [comment]
Hi Jordan, I have created a pull request for that issue (110) however I'm not so familiar yet with the procedure we have here, so could you please review if everything is in place and done correctly? 
Thanks

**Comment by skurnevich** [comment]
Hi Jordan, I believe this one could be closed now, unfortunately I don't have permissions to do that.
