### ISSUE TITLE
Configure explorer-jes FVT tests to allow ES6 syntax

### ISSUE THREAD

**Issue by jordanCain** [zowe/zlux#372]
Currently the build setup of the explorer-jes fvt selenium tests only allows for ES5 syntax, this is inconsistent with the rest of the repo.

**Comment by pranav1698** [comment]
@jordanCain Maybe this can be closed as the pr is merged

**Comment by jordanCain** [comment]
This is still an issue, the config for the fvt tests still restricts the use of es6 syntax, we need to test run command to correctly configure babel before running in order to allow es6 features

**Comment by jordanCain** [comment]
I think this can likely be solved by including https://www.npmjs.com/package/regenerator-runtime
