### ISSUE TITLE
Unable to run install-app.sh

### ISSUE THREAD

**Issue by kiril-ibm** [zowe/zlux#373]
IBMUSER:/opt/zowe/zowe-instance-dir/bin>./install-app.sh /opt/zowe/zowe-instance-dir/workspace/extensions/com.ibm.addi.web.mvd/addi-web-mvdapp
Verifying node exists
/usr/lpp/IBM/cnj/IBM/node-v6.17.0-os390-s390x/bin/node is /usr/lpp/IBM/cnj/IBM/node-v6.17.0-os390-s390x/bin/node
Running app-server plugin installer. Log=/opt/zowe/zowe-instance-dir/logs/install-app.log
utils_path=/opt/zowe/zowe-1.8.0/components/app-server/share/zlux-server-framework/utils
app_path=/opt/zowe/zowe-instance-dir/workspace/extensions/com.ibm.addi.web.mvd/addi-web-mvdapp
json_path=/opt/zowe/zowe-instance-dir/workspace/app-server/serverConfig/server.json
__: ./install-app.sh 111: FSUM7351 not found
Ended with rc=127

**Comment by grlwholifts** [comment]
Hi @kiril-ibm i'm adding a link to the IBM forum here: [ https://developer.ibm.com/answers/questions/478871/java-fsum7351-not-found/ ]. Hope it helps :)

**Comment by kiril-ibm** [comment]
It is fixed now
