### ISSUE TITLE
Add ability to create new file or directory without needing to right click on existing file or directory

### ISSUE THREAD

**Issue by jordanCain** [zowe/zlux#374]
Currently if you navigate to a directory that has no children (files/directories) you are unable to create anything because we only show a context menu if you have a file or directory to right click. We should add a context menu to the whole tree component that allows a user to create a file or directory

**Comment by shivanshs9** [comment]
We could also show a button, similar to how it is shown in VS Code to open folder. 
![Open folder in VS code](https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTMclpuZq8Q5wvzMm8gpk9Zj15PyRHwDczhsBhWqVSvoZNMxkjY)

**Comment by 1000TurquoisePogs** [comment]
Closed due to inactivity
This seems no longer relevant when using the Editor
