### ISSUE TITLE
Add Descriptive Notifications in Editor

### ISSUE THREAD

**Issue by aarohimshah1** [zowe/zlux#375]
When a directory cannot open, the notification should give reasoning why the file could not open, or the notification should give next steps.

**Comment by pranav1698** [comment]
@aarohimshah1 I would like to work on this issue

**Comment by aarohimshah1** [comment]
Hello @pranav1698, Feel free to assign this to yourself and get started. If you need any help with understanding the requirements or implementation, please let me or @1000TurquoisePogs know.

**Comment by pranav1698** [comment]
As there is no implementation for opening a file right now, I am going with the traditional file not found error, 
We can change the message according to the error code when the implementation of opening a file is added

**Comment by DivergentEuropeans** [comment]
We have this 

![image](https://user-images.githubusercontent.com/20528015/115478228-b2a26e80-a213-11eb-84ab-5dfa0bab3517.png)
