### ISSUE TITLE
Delete the Language Server Settings modal

### ISSUE THREAD

**Issue by aarohimshah1** [zowe/zlux#376]
Delete the Language Server Settings modal

**Comment by piculet** [comment]
Should I remove the language server tab altogether or just the modal? Since that modal is the only option that appears when we click on language server -> URL

**Comment by aarohimshah1** [comment]
> @aarohimshah1 Should I remove the language server tab altogether or just the modal? Since that modal is the only option that appears when we click on language server -> URL

Yes, you can remove the tab from the menu bar. Thanks!

**Comment by piculet** [comment]
@aarohimshah1 I removed the `Language-server` tab, but i haven't yet deleted the remaining code for the modal and the language-server since it was getting a bit messy. Should I try and remove all the remaining code or just the tab?

**Comment by aarohimshah1** [comment]
> @aarohimshah1 I removed the `Language-server` tab, but i haven't yet deleted the remaining code for the modal and the language-server since it was getting a bit messy. Should I try and remove all the remaining code or just the tab?

@1000TurquoisePogs, can you please answer @piculet question

**Comment by DivergentEuropeans** [comment]
If it's not functional, then we should comment it out from the UI @piculet (Don't remove any code) 

But wasn't there a PR to make it work? https://github.com/zowe/zlux-editor/pull/75
It may be more useful to review this and test that it works than removing a feature that's halfway completed. If this is impossible to test (for example, if you need mainframe access and don't have it) then commenting out the language server menu option is fine for now

**Comment by piculet** [comment]
@DivergentEuropeans thanks!

**Comment by DivergentEuropeans** [comment]
This was solved
