### ISSUE TITLE
Add "No Results" for Search

### ISSUE THREAD

**Issue by aarohimshah1** [zowe/zlux#377]
If querying a dataset that does not exist, in the blank space below the address bar, include text “No results.” 

If querying a file that does not exist, in the blank space below the address bar, include text “Folder does not exist” or “Folder exists but is empty” depending on the case.

**Comment by grlwholifts** [comment]
Hi @aarohimshah1 i would like to take this up!

**Comment by grlwholifts** [comment]
Hi @1000TurquoisePogs @DivergentEuropeans, could you help me get started?

**Comment by DivergentEuropeans** [comment]
@grlwholifts Yes, so the way to do this would be to add placeholder text to the PrimeNG tree object. At the core of the File Explorer browsing tree is a PrimeNG tree that gets populated with our data from USS or MVS, depending on which mode you're on. You should be able to add a placeholder attribute when the data inside the tree is empty

So check out this: https://primefaces.org/primeng/#/tree
It will probably be the "**filterPlaceholder**" attribute if I were to guess

**Comment by shivanshs9** [comment]
Hi @DivergentEuropeans,
I've created a [relevant PR](https://github.com/zowe/zlux-file-explorer/pull/61) to fix this issue. Could you please check that out?

**Comment by grlwholifts** [comment]
Hi @shivanshs9 i'm afraid the issue had already been assigned to me 😅. It is considered good open source culture if you firstly ask for the availability of the issue.
Please have a look at the Code of Conduct and Community Guidelines.

**Comment by DivergentEuropeans** [comment]
Hey @shivanshs9 Thanks, I'll take a look when I come into the office. And yes, as @shivanshs9 let's try to follow the Git workflow of things and if there are comments in the thread of an issue that someone is working on something (or an issue is assigned to them) then we let that person work on that issue unless they need help

Thank you!

**Comment by shivanshs9** [comment]
Hi @grlwholifts, I'm sorry about that. It's been assigned to you for almost a week now, so I guess I incorrectly assumed you aren't working on it right now.
@DivergentEuropeans right, I'll confirm the availability of issue from the assignee before starting to work on it.

**Comment by DivergentEuropeans** [comment]
We now get a Snackbar popup that says
![image.png](https://images.zenhubusercontent.com/5cf465968d690c7080bd33a8/2c4c59a2-c2bb-45b6-ad74-32e376c600f6)
