### ISSUE TITLE
Change Search and Address Bar Hint Text

### ISSUE THREAD

**Issue by aarohimshah1** [zowe/zlux#378]
In the address bar for files, instead of the text “Enter a directory…” include the text “Enter an absolute path.” In the search bar for datasets say “Enter a dataset query.”

**Comment by grlwholifts** [comment]
Hi @aarohimshah1 i would like to take this up! Could you provide more information, if required to help me get started?

**Comment by NolanRogers** [comment]
@DivergentEuropeans can you help @grlwholifts get started?

**Comment by DivergentEuropeans** [comment]
Will do thanks @NolanRogers .

**Comment by grlwholifts** [comment]
Check out the pull request for this issue in `zowe-file-explorer` here: [ github.com/zowe/zlux-file-explorer/pull/59/ ](https://github.com/zowe/zlux-file-explorer/pull/59/)

**Comment by NolanRogers** [comment]
Thanks Lenny
