### ISSUE TITLE
Add "/" in Address Bar

### ISSUE THREAD

**Issue by aarohimshah1** [zowe/zlux#379]
When the address bar for files is selected, users should not be able to delete the initial “/” in the field.

**Comment by piculet** [comment]
@aarohimshah1 I'd like to work on this issue.

**Comment by aarohimshah1** [comment]
Hello @piculet, Feel free to assign this to yourself and get started. If you need any help with understanding the requirements or implementation, please let me or @1000TurquoisePogs know.

**Comment by piculet** [comment]
> Hello @piculet, Feel free to assign this to yourself and get started. If you need any help with understanding the requirements or implementation, please let me or @1000TurquoisePogs know.

Thanks a lot!

**Comment by DivergentEuropeans** [comment]
Wooooow, wtf. I literally fixed this months ago. Let me double check that it still exists

**Comment by DivergentEuropeans** [comment]
Yes, this currently works for me and I cannot delete the "/". Closing now, re-open if you can replicate
