### ISSUE TITLE
ZOWESVR abends SEC3 R=20000005  BBGZSAFM cannot be loaded on startup

### ISSUE THREAD

**Issue by ianc-d** [zowe/zlux#38]
Error loading  BBGZSAFM module during startup after installation. All installation activities completed.

STDERR shows...
CEE3250C The system or user abend SEC3  R=20000005 was issued.                 
         From entry point ntv_registerServer at compile unit offset +0000000028046602 at entry offset +0000000000083B2A at address 0000000028046602

SYSLOG shows...
BPXP011I THREAD 1B2E78000000000D, IN PROCESS 50397976, WAS 138
TERMINATED DUE TO A PTHREAD QUIESCE OF TYPE 2.                
IEF450I ZOWESVR3 STEP1 - ABEND=SEC3 U0000 REASON=20000005    

Verification shows zowe destop logon at http://ip:port/ZLUX/plugins/com.rs.mvd/web/index.html, but authorization fails (as expected). All other verifications fail.

Server stderr, stdout and zssServer log attached.
 
[zowesvr.stdout.txt](https://github.com/zowe/zlux/files/2507674/zowesvr.stdout.txt)
[zssServer-2018-10-23-18-36.log](https://github.com/zowe/zlux/files/2507676/zssServer-2018-10-23-18-36.log)
[zowesvr.stderr.txt](https://github.com/zowe/zlux/files/2507679/zowesvr.stderr.txt)

**Comment by 1000TurquoisePogs** [comment]
Looking into this, thanks for posting.
in zowesvr.stdout.txt I see 
```
Ý2018-10-23 18:50:50.307 _unp.child INFO¨ - ÝPath=/S0W1/var/zowe/run091/zlux-example-server/bin/zssServer.sh stdout¨: httpserver: ABEND 047-00 averted when handling com.rs.mvd.login
```
This leads me to believe `/S0W1/var/zowe/run091/zlux-example-server/bin/zssServer` was lacking the permissions it needed - for zowe 0.9.1 that's RDEFINE  and APF-auth, which can be added via `extattr +ap /S0W1/var/zowe/run091/zlux-example-server/bin/zssServer`. In an upcoming release we should see only +p being needed.

But, the abend SEC3 I've forwarded this to the zowedev slack group to see if there are other opinions.

**Comment by fbeyl** [comment]
Table 1. Liberty profile for z/OS® abend codes
Abend Code	Abend Reason	Explanation	
EC3              	20000005	       The BBGZSAFM module could not be loaded from the file system.	Check that the installation of the Liberty profile completed without errors, and that the user ID which is running the Liberty server has permission to read the files in the Liberty installation. If the problem persists, contact your next level of support.

**Comment by fbeyl** [comment]
In zssServer-2018-10-23-18-36.log httpserver: ABEND 047-00 averted when handling com.rs.mvd.login --> An unauthorized program issued a restricted svc instruction seems to confirm it lacks apf auth

**Comment by hogstrom** [comment]
@fbeyl This seems likely that the ID installing Zowe lacks the authority to set the authorized bit on the ZSS objects.  There is likely an error in the install that would indicate an attribute couldn't be set.

Navigate to the directory in Zowe that contains the ZSS Server. and execute this command:

The dir should be ${ZOWE_HOME}/zlux-example-server/bin

`extattr zssServer`

```
    IBMUSER:/SYSTEM/var/zowe/0.9.2/zlux-example-server/bin>extattr zssServer
    zssServer
    APF authorized = YES
    Program controlled = NO
    Shared address space = YES
    Shared library = NO
```

**Comment by 1000TurquoisePogs** [comment]
This is outdated info now that zssServer shouldnt be APF auth anymore, so closing.
