### ISSUE TITLE
Change Save As Modal

### ISSUE THREAD

**Issue by aarohimshah1** [zowe/zlux#382]
Update the Save As Modal

Axure Prototype: https://rsjb54.axshare.com

**Comment by pranav1698** [comment]
I would like to work on this issue

**Comment by aarohimshah1** [comment]
Hello @pranav1698, Feel free to assign this to yourself and get started. If you need any help with understanding the requirements or implementation, please let me or @1000TurquoisePogs know.

**Comment by DivergentEuropeans** [comment]
Thanks for the work @pranav1698 
I posted a review here:
https://github.com/zowe/zlux-editor/pull/139#pullrequestreview-376374503

**Comment by AdarshdeepCheema** [comment]
fixed via https://github.com/zowe/zlux-editor/pull/239
