### ISSUE TITLE
Change Editor Hotkeys

### ISSUE THREAD

**Issue by aarohimshah1** [zowe/zlux#386]
Update the editor hotkeys. The "Zowe Editor Hotkeys" document states what the existing hotkeys are, what to change the hotkeys to, and gives reasoning for change.

[Zowe.Editor.Hotkeys.docx](https://github.com/zowe/zlux/files/4124792/Zowe.Editor.Hotkeys.docx)

**Comment by DivergentEuropeans** [comment]
"Bring focus to search bar"
Alt + F is a common browser binding for "open settings" in browsers. This may be possible to override though.

"Tab backward"
I believe the Editor already has Tab backward as Shift + Tab, not Alt + Tab. Alt + Tab would be really bad since it's for switching windows in Windows

**Comment by NolanRogers** [comment]
@NakulManchanda do you have any input on this? I know you've done some keyboard navigation work

**Comment by aarohimshah1** [comment]
> "Bring focus to search bar"
> Alt + F is a common browser binding for "open settings" in browsers. This may be possible to override though.
> 
> "Tab backward"
> I believe the Editor already has Tab backward as Shift + Tab, not Alt + Tab. Alt + Tab would be really bad since it's for switching windows in Windows

Thank you for noticing this. I will update the document accordingly.

**Comment by NakulManchanda** [comment]
hi, thanks guys for looking into the best options, 
@NolanRogers @aarohimshah1 find demo recording here, skip to 10min 20 sec

[System Demo](https://zoom.us/rec/play/vpwrc-6s-D43T9LDtwSDUPF9W42-L6ms1iQX-fMPmUzhBSYHNlD1Y7MbYesY-d5-k6b2sjSwF-oMxC7M?continueMode=true)

Glanced at it yesterday, looks good mostly.

One thing we tried to do is to borrow keyboard shortcut from **vscode**.
Open VSCode and try these:

just keep pressing Alt - it highlights Menu shortcut keys - we are using Alt+M 
Lets find replacement for this as well, may be use Alt+G(Go) here, as we cannot emulate vscode here

Alt+1 - to go to first open file - Alt+2 for second open file etc - requirement doc suggests Alt+G(Go) - may be we can do what vscode does here, Alt+1,2,3 etc depending on number of tabs

Alt+S - focus to search bar,like Alt+F better as suggestion better
, as we have no other find functionality, Ctrl+F - we use inside editor tab, which is good, and consistent with other tooling developer use.

**Comment by NakulManchanda** [comment]
@1000TurquoisePogs @DivergentEuropeans 

Can we add another issue to trap focus within app so browser shortcut can be used, wherever possible? 
Atleast we can start with zlux-editor if we don't find general solution.

Example - in code editor open file, try CTRL+F, it don't open browser find, only editor find, so editor component ngx-monaco-editor got that working correctly.

**Comment by aarohimshah1** [comment]
I had a discussion with @NakulManchanda and have updated the document in this issue to include the hotkey changes and additions we want now.

**Comment by apsychogirl** [comment]
Hi, I would like to work on this issue. I am new to Zowe, Can you please help me in getting started?

**Comment by apsychogirl** [comment]
@NolanRogers Can you please help me in getting started.

**Comment by DivergentEuropeans** [comment]
Hey @apsychogirl 
I can help you get started if you'd like. Do you have Zowe set up (or at least the virtual desktop portion?)

**Comment by apsychogirl** [comment]
@DivergentEuropeans 
Yes, I have set up the Zowe part. Need further help for changing the hotkeys as it is a little confusing for me to begin with!
![image](https://user-images.githubusercontent.com/37927368/74097095-0c96a700-4b2e-11ea-8f06-39e00acb3630.png)

**Comment by DivergentEuropeans** [comment]
Hey, great @apsychogirl 

So to start us off, you'd want to make sure your Editor is fully up-to-date with the latest code, so pull everything fresh and use the 'staging' branch. Then all is left, is changing the hotkeys (or adding them). We already have a fairly fleshed out keyboard Angular service thanks to @NakulManchanda 's previous work located here:
https://github.com/zowe/zlux-editor/blob/staging/webClient/src/app/shared/editor-keybinding.service.ts

Here's an example of the service is used to register a key such as Alt + T or Alt + W:
https://github.com/zowe/zlux-editor/blob/staging/webClient/src/app/editor/code-editor/code-editor.component.ts#L90

I think from here it should be fairly straightforward... Let me know if you need more help!

**Comment by apsychogirl** [comment]
Thanks @DivergentEuropeans I'll look into the docs and will let you know if I need any more help:)

**Comment by DivergentEuropeans** [comment]
We reviewed the current hotkeys, changed some, and added new ones
