### ISSUE TITLE
Add X to Close Modals

### ISSUE THREAD

**Issue by aarohimshah1** [zowe/zlux#387]
Modals in the Editor should have an X to close the modal in the top right corner of the Modal. The same style of X should be used for all modals.

**Comment by PrajwalM2212** [comment]
https://github.com/zowe/zlux-editor/pull/130

**Comment by NolanRogers** [comment]
@1000TurquoisePogs @NakulManchanda  @DivergentEuropeans  could you guys review the linked PR when you get a chance?

**Comment by DivergentEuropeans** [comment]
Hey thanks @NolanRogers ! 

I apologize I couldn't get to this sooner @PrajwalM2212 . I posted a review here: 
https://github.com/zowe/zlux-editor/pull/130#pullrequestreview-376325038
