### ISSUE TITLE
Support Node 12

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#391]
In order to establish long-term support for Zowe, it must be compatible with versions of prerequisites that will be supported in the future.  Node 12 has been released by IBM recently, and we should support this while maintaining existing support for node 8 as long as that is also supported.

This epic is for both the app server & the web explorers, which are all the users of nodejs for zowe on z/os at this time.

**Comment by 1000TurquoisePogs** [comment]
This epic does not include work previously done, just lists work remaining

**Comment by pranav1698** [comment]
I would like to work on this, @1000TurquoisePogs

**Comment by 1000TurquoisePogs** [comment]
Thanks for your interest @pranav1698. I think the work remaining to be done requires a z/OS system to test with and control of our Jenkins pipeline, so I'm not sure if there is extra work that isn't already being done by @struga0258. We can tag some "good first issue" tickets if we find items related to node 12 that aren't being handled already.

**Comment by pranav1698** [comment]
@1000TurquoisePogs I have tested it with the Jenkins pipeline, the build passes without any error 
Testing on a z/OS system is only left

**Comment by 1000TurquoisePogs** [comment]
Closed due to this being finished in release 1.9
