### ISSUE TITLE
UI components missing bpx jobname

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zlux#393]
All 4 ui components are missing the _BPX_JOBNAME command required to set the address space component code and allow people to track the performance and stats of the components properly. Their start.sh scripts should have something like the following:
```
COMPONENT_CODE=EF
_BPX_JOBNAME=${ZOWE_PREFIX}${COMPONENT_CODE} <start command>
```

**Comment by 1000TurquoisePogs** [comment]
@stevenhorsman I think this is finished?
Also: shouldnt _BPX_JOBNAME include instance number? None of them do currently

**Comment by stevenhorsman** [comment]
Hey Sean, maybe i'm looking in the wrong place, but I can't see something like
```
COMPONENT_CODE=EF
_BPX_JOBNAME=${ZOWE_PREFIX}${COMPONENT_CODE}
```
in zlux-app-server/bin/start.sh

BTW instance should be included - for better or worse the instance was merged with the prefix in run-zowe.sh: `export ZOWE_PREFIX=${ZOWE_PREFIX}${ZOWE_INSTANCE}`

**Comment by jordanCain** [comment]
I've completed the work here regarding jes/mvs/uss explorers 
https://github.com/zowe/explorer-jes/pull/171
https://github.com/zowe/explorer-uss/pull/68
https://github.com/zowe/explorer-mvs/pull/105

**Comment by NakulManchanda** [comment]
this seem to be resolved with pr in comment above
