### ISSUE TITLE
Zlux build fails for 'zlux-server-framework' on 2nd and next builds

### ISSUE THREAD

**Issue by MKoipish** [zowe/zlux#396]
When I try to run full build from zlux-build for the second time, I've got an npm error(see below)

**Steps to reproduce:**
- cd zlux-build && ./build.sh
- (I'm not sure if it's important, but my first build fails in another, not related to ZLUX, place)
- ./build.sh again

**Observed behavior:**
After approximately 10 seconds I've got an npm error in 'zlux-server-framework' directory:

![image](https://user-images.githubusercontent.com/39908467/74415757-0289e680-4e55-11ea-9261-5536ad2faaa1.png)

Problem packages I had to install manually: aws4, core-js, fast-deep-equal, fast-json-stable-stringify

**Workaround:**
Go to directory 'zlux-server-framework' and do 'npm i {package_name}' manually

**Comment by MKoipish** [comment]
Well, zlux-app-server also has this problem.

Removing `package-lock.json` also works as a **workaround**.

**Comment by pranav1698** [comment]
@MKoipish, I am not facing the same issue
Maybe you are checking wrong submodules
Can you try doing a fresh installation following the steps given here: https://github.com/zowe/zlux-app-server/tree/staging#first-time-installation--use

**Comment by MKoipish** [comment]
Hi!
Sorry, forgot to note:
Zowe version: v1.7.0
Node version: v8.17.0
npm version: 5.4.2

**Comment by MKoipish** [comment]
Well, I didn't notice an npm version requirements. So, I've update my npm up to v6.4.0 and try again with a clean build(following installation guide). Same problem.

First time, my build fails with "Operation is not permitted". To reproduce that behavior, you could try to install 'zlux' on 'C' drive on Windows. Hope that would help =)

**Comment by 1000TurquoisePogs** [comment]
There is probably a bug here, but did you know you can skip the build step anyway? Pre-build "zlux" is here: https://zowe.jfrog.io/zowe/libs-snapshot-local/org/zowe/zlux/zlux-core/
You can just put extract the .tar to a linux/windows system, or the .pax to a zos system. the pax includes ZSS, while the tar needs you to get ZSS on zos separately.
