### ISSUE TITLE
For frame-ancestor allow both the named IP and also numeric IP

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zlux#401]
@Joe-Winchester commented on [Thu Jun 20 2019](https://github.com/zowe/zowe-install-packaging/issues/532)

**Problem**   
Customer who was unable to resolve to a named host but could use numeric IP was unable to launch the explorers because of a frame-ancestor error

**Proposed solution**   
In the frame-ancestors add a numeric IP host as well as an alphabetic host name

---

@yann-59 commented on [Mon Feb 03 2020](https://github.com/zowe/zowe-install-packaging/issues/532#issuecomment-581413041)

We had a similar problem ... we had 3 DNS depending the site we connected. If we used the DNS's name provided at the install, we had no error. If we used alternate DNS, the explorer wont' launch and we can see an error message :  
Refused to display 'https://xxxx.yyyy.toto:7554/ui/v1/explorer-mvs/' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors xxxx.yyyy.toto:*".
In previous version of Zowe , we modified the index.html to add the good name :
 è,                                          
 "csp": é                                    
   "frame-ancestors": Ý"https://xxxx.yyyyy:*"   
Now, is it a way to add multiple DSN or IP address for using explorer with ZLUX?

**Comment by 1000TurquoisePogs** [comment]
If you set headers dynamically, it may be possible to see what address the client tried to reach the server by. the Host header is one such way to determine it. This way you can set CSP relative to how the client accessed it.

**Comment by yann-59** [comment]
Hello ... I'm not sure to understand all ... in what path can I put the CSP relative ?

**Comment by NakulManchanda** [comment]
public numeric ip and name both are used as comma separated value in CSP frame ancestor property
available in v1.13

Resolved for all explorers
https://github.com/zowe/explorer-jes/pull/183
https://github.com/zowe/explorer-mvs/pull/118
https://github.com/zowe/explorer-uss/pull/79
