### ISSUE TITLE
Single session time-out mechanism makes the last opened desktop incorrectly work

### ISSUE THREAD

**Issue by jiangg91** [zowe/zlux#403]
Hi, a common scenario is to work on multiple ZOWE desktop tabs simultaneously. Currently, session time-out of any page leads to session time-out of all pages. The problem is, the time-out behaviour of the last opened page is less user-friendly. It does not bring user to the login page or notify user. User can still operate that desktop but no longer receive correct response. This issue brings very bad user experience. 

**Detailed description:** suppose multiple brower tabs are opened for ZOWE desktop. Even though user is actively working on one page of them, the inactive page is still brought to login page due to session time-out. At the time the inactive page is time-out, user is still able to operate on the active page without time-out notification.  However, the  operation cannot receive response from the backend  service.
**Error message in broswer developer tools:** `Object { _body: "{\"category\":\"zss\",\"pluginID\":\"org.zowe.zlux.auth.zss\",\"result\":{\"authenticated\":false,\"authorized\":false}}", status: 401, ok: false, statusText: "Unauthorized", headers: {…}, type: 2, url: ...`
   **Reproducible:** easy.
   **How to reproduce the issue:** open a browser tab for ZOWE desktop every 20 minutes for one hour and not operate on any of them. Wait for the time-out of the first page and then operate on the third page.
   **Browser information:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:71.0) Gecko/20100101 Firefox/71.0
   **ZOWE version:** v. 1.8.0+20200127

**Comment by jiangg91** [comment]
Basically, I think, there are two things to be fixed. 
   1. If session time-out happens, all tabs should notify user clearly. 
   2. When the session time-out occurs should depend on the **most active** page rather than the **least active** page.

**Comment by jiangg91** [comment]
Could I know the progress on this issue?

**Comment by NakulManchanda** [comment]
hi @jiangg91 , 

as you see above i proposed solution in `session across tabs #219` just now
team needs to review and approve the same, i am hopeful it may make v1.11 but not sure yet

FYI @1000TurquoisePogs

**Comment by NakulManchanda** [comment]
hi @jiangg91 , 

Separately there is new session event which is being introduced in next release:
https://github.com/zowe/zlux-app-manager/pull/210

Feel free to add this new feature to your app, and take appropriate action in your app on session expire.

Repeating **React example** here:
**Retrieve the sessionEvents from the resources props**
```
this.sessionEvents = this.props.resources.sessionEvents;
Then listen on the appropriate event:

this.sessionEvents.login.subscribe(() =>{
    console.log("This will trigger when you login")
})

this.sessionEvents.sessionExpire.subscribe(() =>{
    console.log("This will trigger when your session expires")
})
```

See it in action here in one of the angular apps (zlux-editor):
https://github.com/zowe/zlux-editor/pull/145

**Comment by NakulManchanda** [comment]
Hi, PR to fix this is merged
https://github.com/zowe/zlux-app-manager/pull/219

**Comment by NakulManchanda** [comment]
User comments:
I would like to give a sample for your refrence. I opened my first page on 10:00PM. Then, opened my second page on 10:30PM. At 10:55PM, when the first page did the idle check. I operated the second page actively at 10:57PM. However, the session expired at 11:00PM.

Needs investigation

**Comment by NakulManchanda** [comment]
Basically, investigating is there is activity after idle check will that stop a logout or not.
If not we need to check activity again just before logging out.

**Comment by jiangg91** [comment]
@NakulManchanda  Did you investigate the above two scenarios? Recently, I investigated them again. 
- The scenario 1 is not ture. The timeout is not pushed to 11:30PM. It is still 11:00PM.
- The scenario 2 is true. I will get HTTP Status Code 401 at 11:02PM.

Please let me know if you need assistance.

**Comment by NakulManchanda** [comment]
Yes, @jiangg91 i wrote them so i remember, i reviewed the issue, but still need to work on resolution. Will get back to you soon. I will reach out thanks!

**Comment by jiangg91** [comment]
@NakulManchanda Looks like you made great progress. When will it be available? We can help validate. Thanks!

**Comment by NakulManchanda** [comment]
hi @jiangg91 , yes i can send you link for custom build later today for verification.

**Comment by NakulManchanda** [comment]
@jiangg91 
Find full zowe build here to test
[zowe.pax](https://zowe.jfrog.io/zowe/webapp/#/builds/zowe-install-packaging%20::%20serve-compressed/2/1592517315796/published%20/zowe-install-packaging%20::%20serve-compressed)

Feel free to deploy in your environment for testing.

**Comment by NakulManchanda** [comment]
@jiangg91 thanks for feedback
```
One scenario failed. Suppose we open a tab on 10:00AM and a tab on 10:30AM, the first tab expired at 11:00AM 
but the second tab will not promoted to the login page at the same time. 
We can still operate on the second tab but receive no response. 

My proposal is, whenever open a new tab, renew all existing tabs. 
In this way, we can make sure all tabs expire at the same time.
```

Made some more changes. Though i did not test it yet.
1. On new login we were not refreshing login, just detecting activity, now in addition **any new login we refresh token so old tab will not expire now earlier than new tab**
2. **Session event Logout and Expire are sent to all tabs**
https://github.com/zowe/zlux/issues/403#issuecomment-616229961

Its untested but feel free to try, let me know how it goes
[zowe.pax](https://zowe.jfrog.io/zowe/webapp/#/builds/zowe-install-packaging%20::%20serve-compressed/3/1593130354446/published%20/zowe-install-packaging%20::%20serve-compressed)

**Comment by jiangg91** [comment]
@NakulManchanda Thanks for the quick fix. It works wanderful.

**Comment by NakulManchanda** [comment]
Good to know, but its just a proposal before it gets merged. Still to get approval and merge. Thanks!

**Comment by DivergentEuropeans** [comment]
Hello, looking at this code now! Upon initial testing, things look good. Will update thoughts in PR soon
@jiangg91 @NakulManchanda

**Comment by DivergentEuropeans** [comment]
This is basically done. Nakul did a lot of great, merged work that adds features. A small test has been added as well to keep track.

For now, when logging in from a different tab, the tab doesn't log in unless refreshed. Otherwise, criteria is met
