### ISSUE TITLE
On relogin after JWT expiration or logout refresh the jobs tree

### ISSUE THREAD

**Issue by jordanCain** [zowe/zlux#408]
Details from PR: https://github.com/zowe/explorer-jes/pull/160#issuecomment-601339933

We should refresh tree and open files on re-login on expiry/deletion(logout) of cookie upon re-login to avoid displaying stale content.

Steps to replicate:

already login, set filter
delete or wait for cookie to expire,
try refreshing filter
shows login screen - which is good
on re-login, we should find a way to refresh content, currently it says "No job found" which is incorrect
Its an edge case when session expire or cookies are cleared by logout action

**Comment by NakulManchanda** [comment]
resolved with Zowe v1.15
