### ISSUE TITLE
Cannot find module 'webpack-config' for sample angular app

### ISSUE THREAD

**Issue by krutikasoman** [zowe/zlux#411]
Geetting error Cannot find module 'webpack-config'. Tried installing webpack, webpack-cli and webpack-config globally, but still not working for local build.

**Comment by lchudinov** [comment]
Try to remove `node_modules` under `webClient` and run `npm install` again. If the problem persists please let me know what your OS and Node JS version.

**Comment by ksoman13** [comment]
Still same.. I use windows 10 and Node Version v12.16.1

**Comment by 1000TurquoisePogs** [comment]
this issue seems to happen most often on windows, and one suggestion i heard was to remove this line https://github.com/zowe/zlux-app-manager/blob/master/virtual-desktop/plugin-config/webpack.base.js#L13
Did that help? If so, we should make it official.

**Comment by travatine** [comment]
Yes please, this fix works for me too ( I had same issue at https://github.com/zowe/sample-angular-app/issues/42 ).

**Comment by 1000TurquoisePogs** [comment]
This has been fixed in staging! So, it would be seen in zowe 1.14.0

**Comment by travatine** [comment]
@1000TurquoisePogs thanks
