### ISSUE TITLE
When localhost isn't mapped unable to log onto the desktop - put a check in a validate.sh script

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zlux#414]
A customer was unable to log onto the Zowe desktop.  Usually this is because zss can't talk to x-mem server.
In this case it was different because zlux was unable to talk to zss which was because localhost wasn't mapped with a /etc/.host entry
The Zowe startup lifecycle provides the ability for a validate.sh script to be included.  This issue is to create a validate.sh script for the app-server component and check whether localhost is mapped and if not issue an error to STDERR.  This will help diagnosing the problem going forward
There is an accompanying doc troulbeshooting issue  https://github.com/zowe/docs-site/issues/1163 as well to help users searching the log message with the problem.

**Comment by John-A-Davies** [comment]
A check will be added to `install/zowe-check-prereqs.sh`, at least to check we can `ping localhost`.

**Comment by 1000TurquoisePogs** [comment]
Would it be better if we defaulted to 127.0.0.1? Way back, we wanted zss to be available only internally due to the need for AT-TLS configuration if it is desired externally. localhost seemed better than 127.0.0.1 because people use other internal IPs, but maybe this is just something we need to call out in `instance.env` so that people can quickly configure it just like they do with ports.
I think we could add that config item within an hour... what about `ZSS_IP_ADDRESS`

**Comment by John-A-Davies** [comment]
`ZSS_IP_ADDRESS` and/or defaulting the zss IP to loopback might help but is this a special case?  There are 56 references to `localhost` in 27 files in `zowe-install-packaging`.  If the customer site does not have `localhost` defined in `/etc/hosts` then the other references might cause similar problems.

I'm not a networking specialist but I think that assuming localhost is defined as loopback is reasonable.

**Comment by Joe-Winchester** [comment]
@1000TurquoisePogs - we've only ever once in a year of Zowe installs come across a customer who didn't have localhost mapped, and that was because they had never got USS working before so they were exceptional.  I prefer leaving localhost which, as you say, covers the AT-TLS configuration because zssServer is an http connection, and just having validate.sh script log to STDERR that it can't be resolve.  Zowe troubleshooting asks users to check STDERR and they'd see the message and just create an /etc/,hosts entry.  

I think when we move to containerize Zowe and get the Unix portions running on docker, we'll need to rethink how the Zowe z/OS portion starts without the Unix portions, and how the docker image can locate the z/OS endpoints, and because zssServer is http maybe there will need to be a node or Java proxy left behind on z/OS that acts as a https:// gateway, however at that time we'll need to fiddle with the instance.env file, so I think for the gold plated solution wait for containerization and for now just have a validate.sh script with a STDERR message.  This isn't urgent and can wait till next sprint but each time we help a customer it's nice to leave a breadcrumb in the doc and product validation so the next customer can self problem determination more easily

**Comment by 1000TurquoisePogs** [comment]
OK, I won't add it for now so that we don't entice people to do the wrong thing.
But, for the future docker case I still think AT-TLS is the way to go... it's great when it works, but the setup is something that should be made easier somehow.
