### ISSUE TITLE
tn3270 app does not work with CICS BMS Maps

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zlux#415]
When using the 3270 emulator with CICS BMS maps the terminal doesn't recognize the input areas correctly.
To test this use the 3270 emulator with the CESN CICS transaction. Input entered is ignored; tabbing through the input fields moves the cursor to position 2 in each field (almost as if it is over-compensating for the attribute byte)

**Comment by 1000TurquoisePogs** [comment]
Hi Joe, I believe there was an update to the terminal in 1.13 or so where we fixed a few bugs such as missing codepages and the ability to save preferences. At that time, I believe some CICS bugs were fixed so this should be retested to see if it's better now.

**Comment by Joe-Winchester** [comment]
sweet !  I'll do some testing and let you know.  Cheers !

**Comment by 1000TurquoisePogs** [comment]
Closing this one due to inactivity but just reopen if it is still an issue. Thanks!
