### ISSUE TITLE
Problems accessing certain features of Zowe Desktop

### ISSUE THREAD

**Issue by mhernandezf** [zowe/zlux#418]
We have installed and started Zowe version 1.10.0 in our test environment.

We have verified API Mediation using https://myhost:httpsPort/api/v1/apicatalog/application/health, Zowe Application Framework using https://myhost:httpsPort and z/OS Services using 
https://hostName:gatewayPort/api/v1/jobs?prefix=*

We can login to Zowe Desktop, and some applications are working fine, but there are four of them (API Catalog, JES Explorer, MVS Explorer and USS Explorer) that are showing a “connection rejected” message form IP 127.0.0.1.

If we access directly JES Explorer, for example, using https://myhost:17554/ui/v1/explorer-jes/#/, the application is working correctly.

We think that maybe the problem is that Desktop is using IP address 127.0.0.1 to access applications instead of myhost address, but we don-t know how to change it.

This is our current configuration:

z/OS release level: 2.3
Zowe version and release level: 1.10.0
Node version: v6.17.0
Java version: 1.8.0_231

We attatched our configuration files (instance.env,  server.json) and our log files:

[instance.env.txt](https://github.com/zowe/zlux/files/4579236/instance.env.txt)
[server.json.txt](https://github.com/zowe/zlux/files/4579238/server.json.txt)
[appServer-2020-05-05-06-28.log.txt](https://github.com/zowe/zlux/files/4579239/appServer-2020-05-05-06-28.log.txt)
[zssServer-2020-05-05-06-28.log.txt](https://github.com/zowe/zlux/files/4579240/zssServer-2020-05-05-06-28.log.txt)

Please, can anyone help us?

**Comment by jordanCain** [comment]
@mhernandezf Hi, to further diagnose this we need to see the full error message and the browser console output. 

If you're not sure how to capture the console output:
First open the console
Chrome: Cmd-Shift-J (on Windows) or Cmd-Option-J (on Mac)
Firefox: Cmd-Shift-K (on Windows) or Cmd-Option-K (on Mac).
Edge: F12 to access the F12 Developer Tools. Once in the F12 Developer Tools, navigate to the Console tab.

Reload the webpage once the console is open and capture the output as the page loads. 

We can also look into setting up a remote diagnosis session if you'd prefer via webex

**Comment by 1000TurquoisePogs** [comment]
Try accessing the app framework through the mediation layer,
https://hostName:gatewayPort/ui/v1/zlux/ZLUX/plugins/org.zowe.zlux.bootstrap/web/
The issue you are seeing is most likely due trying to access (possibly self-signed certificate-using) servers on different ports from the app framework itself. When accessing the desktop through the gateway, everything uses the gateway port and therefore that should no longer be an issue.

**Comment by mhernandezf** [comment]
First of all sorry for the delay. We have had many problems and lack of resources on our test environment.

Last week we installed Zowe 1.12.0 and now all is working fine.

Thank you.
