### ISSUE TITLE
Zowe - APIML - Make zLUX work with most recent code base

### ISSUE THREAD

**Issue by plavjanik** [zowe/zlux#425]
<a href="https://github.com/supmi01"><img src="https://avatars0.githubusercontent.com/u/41791592?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [supmi01](https://github.com/supmi01)**
_Wednesday Sep 12, 2018 at 12:41 GMT_
_Originally opened as https://github.com/gizafoundation/api-layer/issues/101_

----

None

**Comment by DivergentEuropeans** [comment]
@struga0258 Any comments on Joe's comment here in https://github.com/zowe/zlux/issues/425#issuecomment-602570042 ?
Otherwise, if we have the smoke tests, we can close out this issue

**Comment by balhar-jakub** [comment]
Definitely close this issue. Zlux works with API ML as is shown by users actually using it and smoke tests for login, if I remember correctly.
