### ISSUE TITLE
New instance.env variable to allow VT Terminal connection type to be controlled

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zlux#426]
Under node v12 the SSH Zowe client is slowing down to the point where on some systems it times out, and even on native z/OS hardware it seems to have slowed down by a factor of 6 or more.

Working with a customer the solution that worked for them was to change the connection type from SSH to telnet, and change the port.  

Solution is to make this an instance.env parm, e.g.
```
ZOWE_ZLUX_VT_TYPE=ssh/telnet
```
This would have the effect of updating what can be done manually which is to set  

`<INSTANCE_DIR>/workspace/app-server/ZLUX/pluginStorage/
org.zowe.terminal.vt/sessions/`

_defaultVT.json
```
{                      
  "host": "",          
  "port": "23",      
  "security": {        
    "type": "telnet"   
  }                    
}     
```

**Comment by 1000TurquoisePogs** [comment]
A lot of related work went into here: https://github.com/zowe/zlux-app-server/pull/108
The PR works around the fact that the config service is a hierarchy of on-disk jsons. I don't yet see a good standardization for mapping the config service to env vars. There would be ambiguity and very_very_very_very_long_variable_names
So for now we'll keep working around it.
