### ISSUE TITLE
Home directories default to /u/${username}

### ISSUE THREAD

**Issue by Tam-Lin** [zowe/zlux#435]
And while that's a default on z/OS, it isn't required.  Some people prefer /home/${username}, some people run with a shared home directory . . . at the very least, the /u/ part should be configurable.  Ideally, Zowe should talk to the security manager and find out where a users home directory really is.

**Comment by pdbossman** [comment]
I hit this issue also.  I would think the explorer would lookup the home directory for the user and use that.

**Comment by NolanRogers** [comment]
The explorer could query ZSS at the /OMVS API and it will return the value of the home dir
