### ISSUE TITLE
USS Explorer should default to JCL syntax if file suffix/extension is .jcl

### ISSUE THREAD

**Issue by jordanCain** [zowe/zlux#439]
A feature has been requested to default the USS Explorer code editor to use the JCL syntax when editing a JCL file, We can simply add a check for the file suffix/file extension. Going beyond this to inspect the contents of the file are likely beyond the realm of this app however.

Check for syntax can be seen here: https://github.com/zowe/explorer-uss/blob/master/WebContent/js/components/editor/Editor.js

**Comment by 1000TurquoisePogs** [comment]
Closed due to inactivity
This seems no longer relevant when using the Editor
