### ISSUE TITLE
Add option to view Dataset attributes in MVS Explorer

### ISSUE THREAD

**Issue by jordanCain** [zowe/zlux#441]
A way to view the attributes of a dataset in the MVS explorer would be beneficial to users.

We already have the endpoint and function to do this, see WebContent/js/actions/editor.js fetchDatasetAttributes(path) we just need to surface this functionality. I suggest as a context menu entry and then render a dialog with the attributes.

**Comment by 1000TurquoisePogs** [comment]
Closed due to inactivity
This seems no longer relevant when using the Editor
