### ISSUE TITLE
File editor is unable to show file contents after being restarted twice

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zlux#442]
When using the editor app to view uss files, if a user goes through two cycles of opening the app and then closing it, the third time they open the app it will be unable to open the contents of any file.

--Content below is prior to triaging---
After editing a file with the USS Explorer, the File Editor shows all files as empty, even though they are not empty.
![image](https://user-images.githubusercontent.com/36740892/84288434-18749300-ab39-11ea-94b2-eba680485b0f.png)
![image](https://user-images.githubusercontent.com/36740892/84288567-46f26e00-ab39-11ea-9091-50d6676ff8ab.png)

**Comment by John-A-Davies** [comment]
To reproduce:  The sequence is SOMETHING like this ...
1.  open a file in File Editor
2.  edit the file in USS explorer
3. close File Editor
4. open File Editor
4.5 flip to show another file, which is truly empty?
5. open same file (tab is still there?) (still shows un-edited contents)
6. file shows as empty
7. stays empty even if you close/restart File Editor
8. shows true contents if you close/restart MVD

**Comment by John-A-Davies** [comment]
I think "showing as empty" is because it's just not fetching the file, and the default display is an empty screen.
The network traffic appears to show that the file contents are fetched properly, which suggests that the problem is in file rendering.

**Comment by John-A-Davies** [comment]
When the fault occurs, MVS datasets also show as 'empty'.

**Comment by John-A-Davies** [comment]
This screenshot shows I've selected TSTRADM.SMPE.JCL(RECEIVE1) which is displayed in the response body in the debugger, but is shown as blank in the File Editor.
![image](https://user-images.githubusercontent.com/36740892/84493260-64d9e300-ac9f-11ea-8a0e-a6914af9f21b.png)

**Comment by John-A-Davies** [comment]
I've made a recording to demonstrate the fault.  You first see the fault at about 4:30.  
https://ibm.webex.com/webappng/sites/ibm/recording/play/3df0f50ab593468a8dd7a8dc04b08ac0
the recording password is 
9BisPi9J

**Comment by John-A-Davies** [comment]
I recreated this without changing the file in another tab.  It seems that just close/open of the File Editor a couple of times provokes the fault.

**Comment by John-A-Davies** [comment]
You just have to open/close the File Editor twice, after that, all files and datasets show as empty.

**Comment by John-A-Davies** [comment]
Here's a recording
https://ibm.webex.com/webappng/sites/ibm/meeting/postinfo/72D3F230DCF11DF3E0535006FC0A96B3_I_163841143228868861
Its password is 
KchuK3fG
This one shows the fault but the demo peters out because the server connection went down.

**Comment by John-A-Davies** [comment]
@jordanCain Said in Slack:  Looks like they were aware of the issue .... Sean has been able to work on a fix though so should hopefully make it into 1.13

**Comment by DivergentEuropeans** [comment]
Hey @John-A-Davies Correct! As demo'd in today's system demo, we have replaced the main Editor component with a less containerized version of Monaco, which solved that bug. Let me know if it's still a problem for you!
