### ISSUE TITLE
Add cancel job function to JES Explorer

### ISSUE THREAD

**Issue by jordanCain** [zowe/zlux#443]
A user should be able to cancel a job from the JES explorer. We already have the modify job endpoint available from the jobs-api so this would just be surfacing that functionality within the explorer. 

Ideally we should check to see if the job is in active status before rendering the cancel option in the context menu.

**Comment by skurnevich** [comment]
Hi Jordan, @NakulManchanda, 
Reviewed on v 1.13 RC1, I'm able to cancel jobs with JES Explorer, option to cancel job is available for active jobs and not seen for cancelled or abend jobs. LGTM, could be closed, thanks.
