### ISSUE TITLE
Make it such that logout session events in the Desktop are more in sync with each other

### ISSUE THREAD

**Issue by DivergentEuropeans** [zowe/zlux#444]
**How to reproduce?**

Using standard timeouts, change authentication plugin (for example, zss-auth\lib\zssAuth.js in zss-auth) to 36000

Open Desktop, log in & wait until timeout warning prompt appears. 
Now, wait some more. Initially the timeout appears, but eventually wallpaper & app list info is lost because the session seems to timeout before logout occurs.

**Expected behaviour**

These events need to be synchronized & desktop should not show signs of old age prematurely

**Comment by DivergentEuropeans** [comment]
Almost certainly related to: https://github.com/zowe/zlux/issues/440

**Comment by NakulManchanda** [comment]
hi @DivergentEuropeans resolved this with my last PR
https://github.com/zowe/zlux-app-manager/pull/247

- we were not clearing session expire warning timeout on logout, now we are:
https://github.com/zowe/zlux-app-manager/blob/65766ad619e24ee3ed7f676a37a929b7317b7066/virtual-desktop/src/app/authentication-manager/authentication-manager.service.ts#L178

this issue can be closed, feel free to verify and close
