### ISSUE TITLE
USS Explorer, content could be messed up for two equal files

### ISSUE THREAD

**Issue by skurnevich** [zowe/zlux#445]
USS Explorer - File content could be messed up if two files have equal content.

**Steps to reproduce:**
Create two files with same content, empty content will work fine as well.
Change content of one file then switch to second file without saving anything.
Modified content of first file will be incorrectly represented as content of second file.

**Notes:**
Can be solved after Orion editor fixes from [this PR](https://github.com/zowe/orion-editor-component/pull/35) will be merged to the master.
Same issue is fixed for MVS Explorer in [PR 133](https://github.com/zowe/explorer-mvs/pull/133) and can be used as reference.

Seems that I can't add any labels to the issue.
This is a USS Explorer issue, a bug and could be a good first issue.

**Comment by NakulManchanda** [comment]
update orion to 0.0.12 or above
https://github.com/zowe/explorer-uss/blob/184f80b05f12de94deba29365e1ab628387fcca9/package.json#L14
