### ISSUE TITLE
High Availability for Explorer Servers

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#448]
I need to be able to use REST APIs and Zowe websites even in the event that one of the backing servers crashes, so that I can use Zowe in a high available situation.

Concerns: 
- If Sysplex Distributor doesn't "Just work" for API servers, what to do next?
- Moving explorer UI server code to app server could sacrifice load balancing solutions for HA

Dependencies:
- We should follow APIML squad to learn progress about HA, OR architecture calls?

Plan: 
- Move explorer UI server code into app server plugin, such that app server HA is inherited
- Create static definition file to tell APIML to continue to host UI code at old URLs, for backwards compatibility
- Test Sysplex Distributor with Java API servers to see if HA "just works"

**Comment by jordanCain** [comment]
The Systems squad is researching what will be involved for extenders services of Zowe which aligns with how the explorers operate as part of Zowe See: https://github.com/zowe/zowe-install-packaging/issues/1471

**Comment by 1000TurquoisePogs** [comment]
This epic may not be needed. What the explorers DO need is consistently applied startup parameters, which zlaunch should handle.

**Comment by 1000TurquoisePogs** [comment]
Seems no action was needed, so closing.
