### ISSUE TITLE
Be able to delete file on local Z

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#45]
As a mainframe user, I need to be able to delete fiies, so I can manage data remotely

Acceptance criteria: content is deleted, but only if you have the permission to do so

**Comment by DivergentEuropeans** [comment]
File Tree has been added to FTA --> File Tree has delete capabilities --> FTA now has delete capabilities
![image](https://user-images.githubusercontent.com/20528015/85343785-c843ec00-b4bb-11ea-813b-fb6874a3e48a.png)
