### ISSUE TITLE
Integrate Docker within the current RC pipeline

### ISSUE THREAD

**Issue by sakeerthy** [zowe/zlux#453]
zowe-install-packaging jenkins job currently builds both a convenience build pax, and an smpe package.
the existing docker code is built by extracting a convenience build pax... does that mean that we would want a separate jenkins job to run after pax build? I don't think so: I think we want to make building the docker an optional step within zowe-install-packaging

start work by creating a docker branch on zowe-install-packaging, so that we can modify the jenkinsfile without disruption to regular work.

we may want to add new smoke tests, as well as to attempt to run as many scripts from the existing smoke test against the docker container.

**Comment by NakulManchanda** [comment]
Way to manually run smoke test is this:
https://github.com/zowe/zowe-install-test
These test are portable, can be execute with any client machine, windows/linux
Just point to backend with correct environment variable on client
And for zowe cli - add a profile for docker instance too

```
ZOWE_ROOT_DIR=/path/to/zowe \
  ZOWE_INSTANCE_DIR=/path/to/zowe/instanceDir \
  SSH_HOST=test-server \
  SSH_PORT=12022 \
  SSH_USER=********* \
  SSH_PASSWD=********* \
  ZOSMF_PORT=10443 \
  ZOWE_DS_MEMBER=ZWESVSTC \
  ZOWE_JOB_PREFIX=ZWE \
  ZOWE_ZLUX_HTTPS_PORT=8544 \
  ZOWE_API_MEDIATION_GATEWAY_HTTP_PORT=7554 \
  ZOWE_EXPLORER_JOBS_PORT=8545 \
  ZOWE_EXPLORER_DATASETS_PORT=8547 \
  npm test
```
