### ISSUE TITLE
[SPIKE] Further research for docker use

### ISSUE THREAD

**Issue by sakeerthy** [zowe/zlux#456]
List any questions you have here. The current docker image is very similar to a standard zowe pax, minus zss and all z/os specific folders & servers.

**Comment by sakeerthy** [comment]
Open question: one docker image for all components, or docker images for each components?

UX question: what's the most elegant way to utilize plugins & static registrations without modifying the docker image?

**Comment by 1000TurquoisePogs** [comment]
Answer to docker quantity: Start with just one image for all components, because you can always configure it to only run 1 server within the image.
