### ISSUE TITLE
[SPIKE] Research component package layout

### ISSUE THREAD

**Issue by timgerstel** [zowe/zlux#459]
Determine the layout of plugins/apps/components that will be installed by install-app.sh. What metadata should components be required to tell the desktop? How should metadata be separated? Are JSON files appropriate for conveying information about a component?

Should components define their own environment variables that overwrite the instance environment variables (see example component yml in screenshot below)?

Zowe needs a universal scheme for other components to adhere to.

Consider (credit: @stevenhorsman ):
![image.png](https://images.zenhubusercontent.com/5d0799a241e1974be7393ed7/2505c8c5-3521-4155-a89f-e44643e1e1ed)

**Comment by 1000TurquoisePogs** [comment]
What fields do we need for zowe metadata that we can't fit into the ones conda provides?
What conda fields are completely useless to us, yet are required by conda?
What conda fields are optional, and therefore we should not bother with?

**Comment by 1000TurquoisePogs** [comment]
Do we really need paths.json? It comes from conda, and is a checksum of literally every file. It would be annoying to do this ourselves.

**Comment by 1000TurquoisePogs** [comment]
Done and documented by component design in zowe-install-packaging tickets.
