### ISSUE TITLE
Be able to browse files on local Z

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#46]
As a USS mainframe user, I need to be able to browse directories to choose where to download or upload files.

Acceptance criteria:

Use the reusable file explorer tree, to view files & folders on the mainframe where Zowe is.

user needs to see & be aware that they are browsing files rather than datasets, and to swap between these views easily

users should not be able to browse content they do not have permission to view

performance shouldn't diminish with large quantity of files & folders in directory

Nice to have: filtering the list of content to find what you want quickly

**Comment by NolanRogers** [comment]
Copy of zlux#48
