### ISSUE TITLE
Improve Zowe core component install

### ISSUE THREAD

**Issue by timgerstel** [zowe/zlux#460]
In the current Zowe pax file:

- PAX files for each component are stored in /files/
- Hard coded install scripts for each component are stored in /scripts/zowe-install-<component>.sh

Instead, perhaps the install script for each component should be placed within its pax file in a defined directory (such as /zowe-scripts/install.sh) as to decouple the install scripting for components from the zowe install packaging.

Consider a script which takes a a YML file containing a list of component info (id, pax file, install target) and installs each package on the list (using the known location of the install script mentioned above).

Overall this would enable the containerization of specific Zowe components.

**Comment by 1000TurquoisePogs** [comment]
Done and documented by component design in zowe-install-packaging tickets.
