### ISSUE TITLE
Define universal naming conventions and IDs

### ISSUE THREAD

**Issue by timgerstel** [zowe/zlux#461]
Need to define naming conventions for Zowe components to adhere to.

How should Zowe component IDs be shaped? For example, org.zowe.core.apiml
Need to define naming conventions for files within components (as well as folders), specifically ones that contain metadata or information the server may need to consume about the component.

Need to define conventions about namespaces as well.

**Comment by 1000TurquoisePogs** [comment]
Done and documented by component design in zowe-install-packaging tickets.
