### ISSUE TITLE
Create new script for installing components

### ISSUE THREAD

**Issue by timgerstel** [zowe/zlux#462]
Create new script /<runtime-dir>/bin/install-component.sh -p <component-pax-location> -i <install-target-directory> [-l <log_directory>] -u <unpax-directory-location>

- How do we validate whether or not the install-dir can go into runtime?
- - We unpax then read the metadata and compare id against org.zowe.core.* filter, or whitelist
- It will extract pax to <unpax> then run <unpax>/bin/zowe-install.sh –i <install-directory> -f <log-file>
- Clean up unpax’d directory

**Comment by 1000TurquoisePogs** [comment]
Done and documented by component design in zowe-install-packaging tickets.
