### ISSUE TITLE
Make ZSS a Eureka client (auto-register to apiml)

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#467]
May not be needed if APIML can tell ZSS about the status of copies of ZSS, by simple HTTP requests.
Otherwise,
ZSS needs to become a eureka client in order to register into the APIML and query it about other running copies of ZSS. A eureka client is an HTTP client, so first we must discover the state of our HTTP client code, to see how much work is needed on that before making a eureka client.

ZSS must also utilize the instance.env environment variables so that, just like app-server, it can find the right port & host to contact apiml.

**Comment by NakulManchanda** [comment]
its simillar to https://github.com/zowe/zss/issues/179

**Comment by 1000TurquoisePogs** [comment]
Closing due to being done in https://github.com/zowe/zss/pull/208/files
