### ISSUE TITLE
TN3270 configuration

### ISSUE THREAD

**Issue by mhernandezf** [zowe/zlux#480]
We use the ZOWE TN3270 emulation but, every time that we access, is necessary to change the configuration: codepage, terminal model. Also, the Spanish codepage is not available.

Is there any way to modify the configuration defaults?

Is planned to include the Spanish codepage?

We have found the following topic that could be helpful for us: https://github.com/zowe/zlux-app-server/pull/108

Is it included in some version?

How can we know if one topic solution is planned or included in a version?

Currently we have ZOWE 1.10.0

**Comment by 1000TurquoisePogs** [comment]
Zowe 1.13.0 will include a save button on the same panel as the codepage & model setting. It will allow each user to save their own personal configuration. This setting will be saved even during upgrades to future zowe versions.

The issue #108 isnt yet in any release, but that would set defaults, override-able by the save button you will see in 1.13.0. 1.13.0 is likely to be released next week.

**Comment by mhernandezf** [comment]
Thank you for your answer, we will wait for Zowe 1.13.0.

We have installed Zowe 1.12.0, and we didn't found  in TN3270 the Spanish code page (284).

Do you know if will be available in Zowe 1.13.0?

**Comment by 1000TurquoisePogs** [comment]
284 will also be in 1.13.0. I think we also added 1145 which is 284 with euro.
