### ISSUE TITLE
JES Explorer, sidebar container is higher than the app container

### ISSUE THREAD

**Issue by skurnevich** [zowe/zlux#484]
The explorer sidebar is not fit into the app container, that leads to appearing of the redundant scrollbar and empty area below the content container. 
This difference become bigger on Job Filters expanding. See screenshots below.

<img width="1680" alt="Screenshot 2020-07-03 at 12 33 40" src="https://user-images.githubusercontent.com/61471197/86462773-748f9900-bd2c-11ea-83a8-62615f1e9bab.png">
<img width="1680" alt="Screenshot 2020-07-03 at 12 34 06" src="https://user-images.githubusercontent.com/61471197/86462777-78232000-bd2c-11ea-9ede-1d6d9bb9f105.png">

Same issue with smaller difference could be seen in MVS Explorer

**Comment by NakulManchanda** [comment]
this is odd, needs to fixed, and compared to old version as well, thanks for filing an issue

**Comment by NakulManchanda** [comment]
comment from @jordanCain :
The formula for calculating tree height should get updated whenever props change but i guess filter card expansion doesn’t force the fullHeightTree to update
FYI @skurnevich
