### ISSUE TITLE
SAF Keyrings implementation

### ISSUE THREAD

**Issue by mhernandezf** [zowe/zlux#485]
We installed Zowe 1.12.0 and we are very insterested in new functionallity about using SAF Keyrings instead of USS directory to locate certificates, but we didn't found in Zowe documentation how to implement it.

Do you have any example?

**Comment by mhernandezf** [comment]
Please, can anyone help us?

Reading Zowe 1.12.0 documentation we don't understand how to configure Zowe to use SAF certificates.

**Comment by 1000TurquoisePogs** [comment]
Keyrings are a common scenario these days and you can read more about it here https://docs.zowe.org/stable/user-guide/configure-certificates
