### ISSUE TITLE
nodeServer - server startup problem ret=1115 reason=0x744c7247

### ISSUE THREAD

**Issue by lesliezhao** [zowe/zlux#49]
/zowe/0.9.2/zlux-example-server/bin/zssServer.sh stdout]: zssServer startup, version 0.8.4+20180813
serverConfigFile ../deploy/instance/ZLUX/serverConfig/zluxserver.json
reading server settings from ../deploy/instance/ZLUX/serverConfig/zluxserver.json
rootDir is ‘../deploy’
productDir is ‘../deploy/product’
siteDir is ‘../deploy/site’
instanceDir is ‘../deploy/instance’
groupsDir is ‘../deploy/instance/groups’
usersDir is ‘../deploy/instance/users’
pluginsDir is ‘../deploy/instance/ZLUX/plugins’
MVD server settings: port=8542
server startup problem ret=1115 reason=0x744c7247
implement me - freeSocketSet

**Comment by Limei-Wu** [comment]
Hi any update about this, I ran into the same error.

**Comment by lchudinov** [comment]
```
$ bpxmtext 744c7247
TCPIP
JRPortBusy: Specified port is in use.

Action: Specify a port not in use or try again later.
```
Please change `zssPort` in your `zlux-example-server/config/zluxserver.json`, re-deploy, and try again.

**Comment by MariuszJn** [comment]
Hi,
I experienced the same issue today.
The output from netstat portlist command  provided some useful information who is using - in my case 8542 port ..and it was ZOWE process. Noticed when main zowesvr started task has been cancelled the child processes still allocate the ports.
Regards,
Mariusz Dabek
