### ISSUE TITLE
Introduce shortcuts when in focus on tree - to trigger context menu items

### ISSUE THREAD

**Issue by NakulManchanda** [zowe/zlux#493]
1) Introduce single key stroke shortcut when focused on tree nodes to trigger context menu items action
2) Highlight keyboard shortcut in right menu by underlining keystroke
3) for delete/purge etc - add warning popup in between
4) to be triggered only when in focus

if any trade off/ please discuss

Actions are already implemented, just create this new keyboard binding to execute that action

![image](https://user-images.githubusercontent.com/4791635/87173087-37cf1f00-c2a3-11ea-924f-6dd683918c69.png)

O - to open 
"Delete" - purge - add warning popup in this workflow
 J - Get JCL

![image](https://user-images.githubusercontent.com/4791635/87173207-66e59080-c2a3-11ea-811d-b391db2cebdc.png)

D - download
F - Open in Full screen

![image](https://user-images.githubusercontent.com/4791635/87173500-dd828e00-c2a3-11ea-80e1-f5416cfb4f19.png)
N- New Dataset
O - Open
"Delete key" - Delete
F2 - rename
S - submit job

![image](https://user-images.githubusercontent.com/4791635/87173635-0efb5980-c2a4-11ea-916d-93b31a895815.png)
ctrl +N - new dataset
 ctrl + M- new dataset member -
"Delete key" - Delete
F2 - rename

![image](https://user-images.githubusercontent.com/4791635/87174302-f6d80a00-c2a4-11ea-9cd1-3513ae429bf4.png)

New Directory - D
New File -  N
Open - O
Delete - "Delete key"

**Comment by Martin-Zeithaml** [comment]
Hi, I would like to work on this, can you assign me to this issue?
What is the preferred way for highlighting Delete, F2 and such keys?

![image](https://user-images.githubusercontent.com/66114686/93866487-007be600-fcc8-11ea-86db-18aa1dec76b3.png)

**Comment by Martin-Zeithaml** [comment]
Hi @NakulManchanda 
This is summary for what I did for JES explorer:
* I have enabled the ```Arrows keys``` when in Menu by changing ```react-contextmenu.css```
   * There is a possible problem: ```Enter key``` is already used for some actions so it is not working for the menus.
* I have introduced shortcuts as suggested in the issue
* ```Del key``` is aligned to right:
![image](https://user-images.githubusercontent.com/66114686/94801193-f9e72000-03e5-11eb-9b24-98c46eacb287.png)
* Menu will disappear only by clicking on item, elsewhere or hitting ```Esc```
   * By hitting correct or any other key, menu is still displayed

This issue is not complicated, but the UI behavior must be defined very preciously.

**Comment by NakulManchanda** [comment]
HI @Martin-Zeithaml 

- Enter key is already used for some actions so it is not working for the menus.
one way to check if menu is visible disable the default action
or as menu occur disable key listener for tree node


Del Key -> can be written as Delete Key
Here is example of Vs Code - right click menu
![image](https://user-images.githubusercontent.com/4791635/94809030-022c6480-03c0-11eb-9082-2024bd487b34.png)

**Comment by NakulManchanda** [comment]
https://pressbooks.library.ryerson.ca/iwacc/chapter/2-1-keyboard-accessible-level-a/

Single Key shortcuts can create some accessibility difficulty
So, just for future extension, just add one flag in component
It can be always "true" for now
But later we should if needed can make that "false", from lets say from setting section

**Comment by Martin-Zeithaml** [comment]
Added to Explorer-JCL, the rest has (almost) no priority due to Editor.
