### ISSUE TITLE
Refresh Job Tree - partial or complete successful job actions

### ISSUE THREAD

**Issue by NakulManchanda** [zowe/zlux#494]
Refresh tree on following actions
SUBMIT
CANCEL
PURGE, none of these automatically refresh job tree

We refresh MVS tree successful on create, delete, and rename datasets.
need to adopt simillar approach in JES explorer

SUBMIT:
- complete refresh on set filter
- or partial refresh to add new job if it match filter

CANCEL:
- partial refresh - change status of job cancelled

PURGE:
- delete job instance from tree view

**Comment by LiangXuehongBJ** [comment]
I'd like to  work on this. Thanks.

**Comment by AdarshdeepCheema** [comment]
is it  implemented
