### ISSUE TITLE
v1.12 install-app.sh not found

### ISSUE THREAD

**Issue by nannanli** [zowe/zlux#495]
@F-LEMANER commented on [Sat Jul 04 2020](https://github.com/zowe/docs-site/issues/1297)

Hello,
In DD STDERR of STC ZWESVTC I have : 
/SYSTEM/var/ZWE/inst_01/bin/install-app.sh: /var/ZWE/bin/utils/zowe-install-iframe-plugin.sh 97: FSUM7351 not found 

Im' upgrading from 1.9 to 1.12

In 1.9 install-app.sh was in /var/ZWE/instance_dir/bin/

In 1.12, I look in all dir and subdir and don't find it

![image](https://user-images.githubusercontent.com/63342548/86493743-fefaeb80-bd72-11ea-84c5-036695e33f40.png)

**Comment by nannanli** [comment]
@1000TurquoisePogs Hi Sean, this issue seems to be a troubleshooting problem about zlux so it was moved from the doc repo to this repo.

**Comment by John-A-Davies** [comment]
If you `cd` to your `instance_dir`, you should find the file here 
```
./bin/install-app.sh
```
Did you run `zowe-configure-instance.sh` ?  
If so, you should find its log in the same instance directory
```
./logs/configure-2020-06-10-04-46-23.log
```

**Comment by John-A-Davies** [comment]
It looks like something has gone wrong during the upgrade, so it might be an install problem rather than a zlux one.  Instance directories have been in use since 1.9 GA or before, so you might like to see if the missing files are in a previous instance directory.  

You should also find the missing script in your runtime directory
```
./components/app-server/share/zlux-app-server/bin/install-app.sh
```

**Comment by stevenhorsman** [comment]
This is a dup of https://github.com/zowe/zowe-install-packaging/issues/1503, which has since been closed
