### ISSUE TITLE
JES Explorer: differentiate between JOB types

### ISSUE THREAD

**Issue by Martin-Zeithaml** [zowe/zlux#503]
I would like to be able to quickly recognize different job types in the panel list.
To achieve that, each job type (STC, TSU, JOB, GRP) will be displayed in different color or by some other formatting technique.
For example, STCs and JOBs:
![image](https://user-images.githubusercontent.com/66114686/88651096-9a108800-d0c9-11ea-81a1-3f6742007464.png)

**Comment by NakulManchanda** [comment]
JOB type is one: Then there is JOB return code [CC 0000] - success, or failure
Will check with UX and get feedback from others too

**Comment by John-A-Davies** [comment]
There are probably JES commands and MVS command to let you select a subset of jobs.  Return codes can also be shown, but you might have to process the output in the desktop to filter the user's desired subset.

Caution is needed in using only colour to distinguish types, because that may violate accessibility rules.

**Comment by John-A-Davies** [comment]
If you use JES commands, be aware that there are 2 flavours of JES; JES2 and JES3.  Commands are not interchangeable between the two.

**Comment by NakulManchanda** [comment]
We have colors highlights already, its just about extending it i believe
![image](https://user-images.githubusercontent.com/4791635/89093332-81cd9100-d387-11ea-9745-83e8156b539d.png)

**Comment by John-A-Davies** [comment]
Do we follow web content accessibility guidelines (wcag) ?
`1.4.1 Use of Color: Color is not used as the only visual means of conveying information, indicating an action, prompting a response, or distinguishing a visual element. (Level A) `

It's OK to use colour to help, but it must not be the only way that a user can perceive the information.

**Comment by Martin-Zeithaml** [comment]
The information itself is already there, the label contains the jobId, which indicates the mainframe job type (TSU, JOB, STC or Gnn for Group). Some new formatting will just you help to be able to locate e.g. STCs between all jobs, when some general filter is used (for example owner A*).

Similar thing is already done with job status - for example the ABENDs and JCL Errors are highlighted in red.
