### ISSUE TITLE
USS path with spaces

### ISSUE THREAD

**Issue by Martin-Zeithaml** [zowe/zlux#508]
In USS Explorer, it is not possible to display a file, which is in the directory with spaces:
![image](https://user-images.githubusercontent.com/66114686/92712572-2e713a00-f35a-11ea-9352-a46f0eed687a.png)

**Comment by AdarshdeepCheema** [comment]
<img width="891" alt="Screen Shot 2021-07-09 at 2 07 22 PM" src="https://user-images.githubusercontent.com/57364561/125119383-060fb480-e0bf-11eb-9a17-139cc41cf4ef.png">

 Cannot reproduce it anymore

**Comment by AdarshdeepCheema** [comment]
Closing based on the above-mentioned findings.

**Comment by Martin-Zeithaml** [comment]
Directory with characters and space(s) is working fine (zowe 1.22).
Directory with space(s) only does not work - yes, it is stupid name for directory, but it is legal.
Directory with hash '#' sign does not work:
![image](https://user-images.githubusercontent.com/66114686/125293124-6a32b280-e323-11eb-900f-1695f1776f37.png)

The issue itself can be closed, but obviously some further investigation is needed.

**Comment by Martin-Zeithaml** [comment]
No longer valid issue.
