### ISSUE TITLE
Re-prompting for credentials to access Zowe explorers 

### ISSUE THREAD

**Issue by NayerNajafi** [zowe/zlux#511]
We have Zowe 1.14 running. We define ZOWE_EXPLORER_HOST=my-domain.com and ZOWE_IP_ADDRESS=ip-address. We don't code ZWE_REFERRER_HOSTS and ZWE_EXTERNAL_HOSTS in instance.env file.

The Explorers windows showed the following message:
_"The webpage at https://my-domain.com:7554/ui/v1/explorer-jes might be temporarily down or it may have moved permanently to a new web address."_

We access port 7554 directly from browser and accept the certificate for both IP address and hostname, go back to the Zowe browser (8544) and open the Explorers, the results were as follows.

JES Explorer: Asks for userid/password twice, then the window is shown but no job is displayed for any filters.
MVS Explorer: Asks for userid/password endlessly.
USS Explorer: Asks for userid/password twice, then the window is shown but no file is shown. When we change the path, it again asks for userid/password twice and no file is shown.

**Comment by jackjia-ibm** [comment]
Seems the cause is missing `SameSite: None` in our set-cookie header, then the browser (with default `SameSite=Lax`) blocked the cookie comes from different domain.
