### ISSUE TITLE
TN3070 terminal service fails to take pre-set values in instance.env

### ISSUE THREAD

**Issue by raymondyanli** [zowe/zlux#513]
We have new values defined in instance.env for opening TN3270, but it seems the service fails to use those values and caused failure to launch tn3270 from zowe desktop.

Here are the values set in instance.env:
ZOWE_ZLUX_TELNET_PORT=992
ZOWE_ZLUX_SECURITY_TYPE=tls

We expect after zowe starts, we can launch tn3270, but it fails with error:
Error: Terminal closed due to websocket error. Code=4999

The way to change those setting, we need to launch the terminal from Desktop and change settings and save them.

The issue already talked to Sean Grady, opening this issue is just for tracking pipeline failure in our pipeline.

**Comment by 1000TurquoisePogs** [comment]
Thanks for reporting this.
We have a fix (and some new features) that went into this PR https://github.com/zowe/zlux-app-server/pull/108 which will be present in 1.16.0
So, hopefully you can try it out soon and confirm that it works for you? Thank you.

**Comment by stevenhorsman** [comment]
It looks like the 'fix' has added more regressions and we are now seeing this problem in the staging branch where the tn3270 app is ignoring the instance.env configuration:
![image](https://user-images.githubusercontent.com/35110159/94906619-b39dc980-0496-11eb-8cf1-3b604c33c017.png)

**Comment by 1000TurquoisePogs** [comment]
I don't observe this behavior, this screenshot is from an unmodified 1.16.0 RC1 in a new instance
![image](https://user-images.githubusercontent.com/30730276/94925178-cdd2aa00-048c-11eb-8192-192b5b18996f.png)

**Comment by stevenhorsman** [comment]
the issue isn't in 1.16 rc1, it's in staging.

**Comment by stevenhorsman** [comment]
the versions of staging and rc1 have different SHA codes in artifactory, so I'm not sure what version was prompted to rc, but I don't think it is the same as staging zlux-core-1.16.0-20200928.124124.pax

**Comment by raymondyanli** [comment]
@1000TurquoisePogs @stevenhorsman 
I tested it with zowe 1.16.0-RC1, it works. I think the issue got fixed in 1.16.0-RC1. I will close the issue later. Thx

**Comment by stevenhorsman** [comment]
@raymondyanli - Jadin confirmed that you were having issues with this in the lastest nightly staging branches as we are seeing in open source.

**Comment by raymondyanli** [comment]
@stevenhorsman We are currently running zowe 1.16.0-RC1, we will get back nightly staging runs asap once 1.16.0-RC1 tests done.

**Comment by raymondyanli** [comment]
@1000TurquoisePogs @stevenhorsman 
I started the pipeline runs for taking staging builds, it seems the fix was not in PAX package. It works ok on SMPE package, not on PAX.
whatever the values in instance.env won't be taken when zowe starts...

**Comment by raymondyanli** [comment]
![image](https://user-images.githubusercontent.com/18621966/94961973-b19e2f80-04c3-11eb-9aa5-929f5d4ceec4.png)

**Comment by stevenhorsman** [comment]
I've noted over DMs, but to make it searchable:
It might not be related, but since I've seen this error in staging I've also seen the following in STDERR:
```
/ZOWE/staging/zowe/components/app-server/share/zlux-app-server/lib/../defaults: /ZOWE/staging/zowe/components/zss/bin/configure.sh 39: .: /ZOWE/staging/zowe/bin/internal/run-zowe.sh 184: FSUM9209 cannot execute: reason code = 0b1b011f: EDC5111I Permission denied. (errno2=0x0B1B011F)
     cd: /ZOWE/staging/zowe/components/zss/bin/configure.sh 39: .: /ZOWE/staging/zowe/bin/internal/run-zowe.sh 184: /var/zosmf/data/home/zwesvusr: EDC5129I No such file or directory. (errno2=0x05190050)
```

**Comment by raymondyanli** [comment]
TN3270 terminal works ok for taking pre-set values from instance.env on pax and smpe-ptf builds for zowe-1.16.0-RC2.
I will verify this when we start to run the staging builds.

**Comment by raymondyanli** [comment]
this issue verified works ok in staging build.
