### ISSUE TITLE
Enhance run-zowe.sh to do port discovery on behalf of all services

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#517]
In instance.env, what if PORT statements were not a single number, but multiple or a range

GATEWAY_PORT=7554
DESKTOP_PORT=8544

option A)
1. set ZOWE_PORT_RANGE=7000-7100
2. run-zowe.sh does port lookup, finds open ports, and assigns a value for GATEWAY_PORT and DESKTOP_PORT

Important that some ports are fixed, like the gateway, so that admins can do ahead-of-time firewall configuration

Note: this ticket may already exist in zowe-install-packaging

**Comment by stevenhorsman** [comment]
Dup of zowe/zowe-install-packaging/issues/441

**Comment by 1000TurquoisePogs** [comment]
This is done a bit differently, via the yaml design where the system spawns different env files per HA instance. Anyway, it is complete.
