### ISSUE TITLE
zss server end when handling com.rs.mvc.logoin

### ISSUE THREAD

**Issue by lesliezhao** [zowe/zlux#52]
httpserver: ABEND 0C4-11 averted when handling com.rs.mvd.login,
does anyone know how to fix this issue? thanks

**Comment by lchudinov** [comment]
Please run `cd zlux-example-server/bin && extattr +a zssServer`.

**Comment by lesliezhao** [comment]
I issue the **extattr +a zssServer** in zlux-example-server/bin/  and restart the zowesvr, when I try to connect the zss server, the error "httpserver: ABEND 0C4-11 averted when handling com.rs.mvd.login" still pops up, do you have any more suggestions @lchudinov , thanks

**Comment by lesliezhao** [comment]
makeWebPlugin begin
makeWebPlugin end
initalizeWebPlugin begin, count=0
initalizeWebPlugin end
begin testing
/ZLUX/plugins/org.zowe.api.catalog/web/**
org.zowe.api.catalog.webcontent.web
../../api_catalog/web/
begin testing
begin testing
Installing VSAM dataset contents service
Installing dataset metadata service
Installing dataset contents service
begin settings service
begin testing
begin testing
httpserver: ABEND 0C4-10 averted when handling com.rs.mvd.login

**Comment by lchudinov** [comment]
Try `extattr +ap zssServer` please.

**Comment by lesliezhao** [comment]
After issuing `extattr +ap zssServer`, the error message "ABEND 0C4-10 averted when handling com.rs.mvd.login" pops again when i try to login the zlux

**Comment by ifakhrutdinov** [comment]
Hello @lesliezhao ,

* What ZSS version are you using?
* Can you please provide the full log
* Is there anything particular about your user ID/password? E.g. non-ASCII characters or spaces?
* Can you please try logging in using some dummy user ID/password, for example FOO/BAR

**Comment by lesliezhao** [comment]
Upgrade it from 0.9.2 to 0.9.4 and can’t reproduce it.
