### ISSUE TITLE
Make testing automation for docker

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#526]
Ansible & jenkins combined can be used to invoke the setup of a docker image such that we can test that it runs as expected.
@jackjia-ibm can you add links here that would be relevant to making enhancements?

**Comment by jackjia-ibm** [comment]
We can define new installation test here https://github.com/zowe/zowe-install-packaging/tree/master/tests/installation/src/__tests__/extended. The test case definition is Jest based, and here is an example https://github.com/zowe/zowe-install-packaging/blob/master/tests/installation/src/__tests__/extended/security-systems/ptf/ts.ts. We can launch the zowe docker container in `beforeAll` step, and use other steps to call Ansible playbook https://github.com/zowe/zowe-install-packaging/blob/master/playbooks/verify.yml which will run sanity test cases defined in https://github.com/zowe/zowe-install-packaging/tree/master/tests/sanity.

With the new installation test case ready, we can add it to TEST_SCOPE defined here https://github.com/zowe/zowe-install-packaging/blob/master/tests/installation/Jenkinsfile#L65, then it will show up in Jenkins Build with Parameter option https://wash.zowe.org:8443/view/Zowe/job/zowe-install-test/job/staging/build?delay=0sec.

**Comment by 1000TurquoisePogs** [comment]
The things that need testing automation are to make sure the configuration options here actually work as described https://github.com/zowe/zowe-dockerfiles/blob/master/dockerfiles/zowe-release/amd64/zowe-v1-lts/README.md

**Comment by 1000TurquoisePogs** [comment]
Right now the images go to https://hub.docker.com/r/rsqa/zowe-v1-lts/tags
But, I will soon be moving it to go to https://hub.docker.com/r/ompzowe/zowe-v1-lts/tags

**Comment by NakulManchanda** [comment]
- its still a hybrid environment for this new playbook and run test for docker
- new playbook can reside in zowe-install-test jenkins job
- zowe-install-packaging - has docker packaging job- new optional stage to also build docker, it pushes new built image to docker-hub -  rsqa/zowe-v1-lts
-  omp/zowe-v1-lts will be a new account to publish images

**Comment by NakulManchanda** [comment]
https://github.com/zowe/zowe-dockerfiles/pull/21
