### ISSUE TITLE
Editor: Syntax For REXX Highlighting

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#527]
Syntax highlighting for REXX is missing. This could be easy if the explorer one can be reused.

We should compare the syntax highlighting with the MVS Explorer and ISPF. Then, we will pick whichever one we like better and model our own syntax highlighting after that one. The code to write for the syntax highlighting will be similar to what was written for JCL.

We need good files to test against. We should ask Jordan, Irek, and Kyle where we should find good examples.

**Comment by 1000TurquoisePogs** [comment]
We can take a look at https://github.com/zowe/orion-editor-component to see if there are good rules for REXX highlighting to use.

**Comment by DivergentEuropeans** [comment]
You completed this
