### ISSUE TITLE
Add OS-awareness for Apps & Plugins

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#53]
If Zowe were configured to operate on a non-Z host, not all Apps would work. Some Apps would. An editor can edit files regardless of where the data lives: ZOS, Linux, Windows. But data needs to be read&written differently depending on the host OS. However, an App meant to work on JES would never support a non-Z host. To allow for Apps to exist in other environments, the following would be needed:

1. A way for Apps & Plugins to specify a list of supported OSs. This would go into the pluginDefinition (https://github.com/zowe/zlux/wiki/ZLUX-Plugin-Definition-&-Structure). The server could refuse to load plugins if the host OS did not match the list of supported OSs in the pluginDefinition.
2. An OS-aware abstraction could be made in uriBroker (https://github.com/zowe/zlux/wiki/URI-Broker), and the server could provide information to the uriBroker to help it make decisions on what endpoints can be used to fulfill a REST API needed for a particular App & OS combination

**Comment by NolanRogers** [comment]
Closing as out-dated
