### ISSUE TITLE
Editor: file renaming

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#530]
Renames: simple would be to make a modal that edits the node value. possibility to rename without modal and with hotkey,
@timgerstel was working on this.
His idea has been to replace the file tree item text with an input field such that you can type whatever you want, and then when finished, the result generates a REST API to ZSS to do the rename, and then update the tree on complete, or replaces with the old text if failure.
https://github.com/zowe/zlux-file-explorer/pull/94

**Comment by DivergentEuropeans** [comment]
Tim completed this
