### ISSUE TITLE
Editor: Review & update hotkeys

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#532]
Review and document existing hotkeys in the editor. Maybe put it into a zlux-editor wiki.
For the copy, delete, create, rename, refresh abilities in the editor unification epic, we need hotkeys for all these new features.

**Comment by 1000TurquoisePogs** [comment]
let's add some info here https://github.com/zowe/zlux-editor/wiki/Hotkeys

**Comment by DivergentEuropeans** [comment]
Updated https://github.com/zowe/zlux-editor/wiki/Hotkeys & will work w/ Alex to update it in doc
