### ISSUE TITLE
Editor: Add refresh buttons & abilities

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#535]
Various places in the UI need the ability to refresh either automatically or on user request.

file tree: take the existing periodic tree refresh logic and make it manual refresh based on clicking a button or something (can already do by enter key) (1-2 days)
datasets: redo search when button clicked (1-2 days)
tabs: re-fetch data for monaco buffer (add menu for tabs https://github.com/zowe/zlux-editor/blob/master/webClient/src/app/editor/code-editor/file-tabs/file-tabs.component.html#L14) ... provide refresh option on a tab, somehow need to modify monaco buffer. (3-4 days)

**Comment by DivergentEuropeans** [comment]
We have now completed this
