### ISSUE TITLE
Use cppcheck in github bot for PR quality check of ZSS code

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#546]
https://github.com/danmar/cppcheck can scan C code that is used on the mainframe pretty well, so we should use it in a quality scan to increase the quality of ZSS pull requests

**Comment by NakulManchanda** [comment]
GFlags.exe program on windows 
- Convert memory for each variable heap to 4K blocks
- and it attach, read, write & execute flag to each block
- so when we feed are c exe to gflags - 
   it can help catch memory write errors, if var1 overflow into memory allocated for var2
http://systemmanager.ru/windows_support_tools.en/gflags.htm

**Comment by 1000TurquoisePogs** [comment]
This was researched and determined that most likely moving to clang is the best static analysis that we can get.
