### ISSUE TITLE
Accessing ZLUX with old application ID url gives no response instead of 404/30x error.

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zlux#55]
After move to new application ID with URL https://myhost:httpsPort/ZLUX/plugins/org.zowe.zlux.bootstrap/web/index.html, when accessing the old URL https://myhost:httpsPort/ZLUX/plugins/com.rs.mvd/web/index.html, the server gives no response instead of http 404 error, or 30x redirect. Currently the browser will show:

```
This page isn't working
{domain name} didn't send any data
ERR_EMPTY_RESPONSE
```

Expected behavior should return http 404 error or http 30x redirect.

**Comment by 1000TurquoisePogs** [comment]
Should be resolved in https://github.com/zowe/zlux-proxy-server/pull/35
