### ISSUE TITLE
Enhance new single app mode to not have window header UI on first app

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#550]
Enhance single app mode to initially not have window header UI

 

Have conditionals in the window manager such that if an app is declared to be fullscreen, then it takes up the entire page dimensions and has no window border.

Make sure that the window buttons like close and minimize are not keyboard navigable so that in addition to not being seen, they also do not effect the page/experience.

The fullscreen attribute should actually be app2app/dispatcher supported, such that app2app can request something to be fullscreen. The dispatcher contacts the window manager, and the window manager will use the fullscreen argument to make sure the app is really fullscreen.

The simplest way to add this feature to the dispatcher is probably to add a new int here, LaunchFullscreen https://github.com/zowe/zlux-platform/blob/acfab928b82dac644ef6bf53e9d5ab847131e546/interface/src/index.d.ts#L109

 

 

Launch callback (https://github.com/zowe/zlux-platform/blob/staging/base/src/dispatcher/dispatcher.ts#L739) needs a new argument which is an object of info about what the window manager should do. This will include fullscreen boolean, and maybe more in the future.

 

Window manager's callback needs to handle that new object https://github.com/zowe/zlux-app-manager/blob/staging/virtual-desktop/src/app/application-manager/application-manager.service.ts#L52

 

Window manager's createWindow interface needs to recieve this object too, so it can know what things to do with the new window (hide UI, maximize) https://github.com/zowe/zlux-app-manager/blob/f2260f33bfc399292eef7bf70083911eb212e27b/virtual-desktop/src/app/application-manager/application-manager.service.ts#L281

 

There is a window state associated in MVD, so it can probably init to being fullscreen

https://github.com/zowe/zlux-app-manager/blob/staging/virtual-desktop/src/app/window-manager/mvd-window-manager/shared/window-manager.service.ts#L524

**Comment by DivergentEuropeans** [comment]
This is done for 1.18
