### ISSUE TITLE
Support app2app and notifications in single app mode

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#554]
In single app mode, when a user makes an action that is supposed to communicate with another app, there are potentially more than one launch style that may be desired (popup, new tab, new window, sizing options etc.). This may require that the cross-launch dispatcher be able to determine if the launcher is or is not in single-app-mode.

This story may only require implementation on a single such "launch style".

**Comment by DivergentEuropeans** [comment]
I completed this for 1.18
