### ISSUE TITLE
New app idea: netstat UI

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#555]
netstat (sometimes onetstat) is a unix tool on z/os that I believe is guaranteed to exist on all the systems. It helps with understanding TCP/IP configuration & status of the machine.
A prototype UI for the zowe desktop was shown in today's web ui meeting... I take no credit and am looking for the authors to add more details to this ticket! Thanks to them for the idea and research.

This ticket is to identify short and long-term plans, such as
* if this should be bundled into a release vs part of an app store or extended app bundle
* what are the minimum requirements of the app before it should be released
* what is a good architecture for its functionality?
* who wants to work on it
* what is the roadmap or timeline

**Comment by 1000TurquoisePogs** [comment]
Some of my thoughts
* screenscraping is a good start and may be sufficient overall, but that depends on the performance & frequency of the call
* do you need certain ESM permissions to get certain info out of netstat
* if you need certain permissions, you shouldnt do the screenscraping from a server that cannot issue the command as the same user that requests it. ZSS can do this, but app-server cannot for example
* if screenscraping is lacking some feature, or better performance is needed, which system calls does netstat use? The same could be constructed into a ZSS plugin
* if the server code does not live in ZSS, then metadata for the plugin must state that the server the plugin uses must be running on z/os. This is a new feature and an example of how to do it is found here https://github.com/zowe/zlux-server-framework/pull/243

**Comment by vit-tomica** [comment]
I plan to look at the backend part. Some research notes:

- There is the [EZBNMIFR](https://www.ibm.com/support/knowledgecenter/SSLTBW_2.4.0/com.ibm.zos.v2r4.halx001/ezbnovervpoll.htm) service which seems to provide the same data like netstat command (possibly, the netstat command uses this service). It's an authorized service and is already implemented in cross memory server (https://github.com/zowe/zss/blob/staging/c/zis/services/nwm.c) so it may be a good candidate to pull data from backend. 

- Another approach could be to move the netstat call from app-server to zss with the help of [popen()](https://www.ibm.com/support/knowledgecenter/SSLTBW_2.4.0/com.ibm.zos.v2r4.bpxbd00/rpopen.htm) function so that we could have, for example, the following in zss:
```C
FILE *fpipe;
char *command = "onetstat -c SERVER";
char c = 0;

if (0 == (fpipe = (FILE*)popen(command, "r"))) {
    perror("popen() failed.");
    exit(EXIT_FAILURE);
}

while (fread(&c, sizeof c, 1, fpipe)) {
    printf("%c", c);
}
pclose(fpipe);
```

- netstat can be optionally protected by a [security resource](https://www.ibm.com/support/knowledgecenter/SSLTBW_2.4.0/com.ibm.zos.v2r4.halu101/netsec.htm)

- EZBNMIFR is not protected by any resource, except a "[drop a connection](https://www.ibm.com/support/knowledgecenter/SSLTBW_2.4.0/com.ibm.zos.v2r4.halx001/configen.htm)" command.

**Comment by skurnevich** [comment]
I’m currently working on the frontend part, so just want to add some details and summarise my current vision.

The idea appeared after one of customers meetings, so we wanted to implement some minimal functionality to allow user to check if the port is free or occupied.

For now it screen scrapes the `netstat -c SERVER` command output, executed by node server (most likely we will move backend to the zss plugin in future)

To make it more useful we are currently working on expanding ports list with more details, like displaying the process that occupies the port, showing FQDN and displaying well-known names for some ports.
Next planned step it is to display the list of reserved ports on separate tab.

As for the frequency of the call, now it has the button for manual refresh only. We were discussing the auto refreshing on some time interval, but still having doubts if it really needed, as it could interrupt user workflow.

We have in mind plan to add some columns customization for the tables on user level, and I would like to utilize the zlux plugin storage feature for that.

Also I was thinking about possible app-to-app communication with new App Du Quarter application in future.
I do not know in details what features it has, but if it is a process manager, then I believe, we could open it with the process ID that occupies the port to allow user to see more details or manipulate with the process.

**Comment by 1000TurquoisePogs** [comment]
>Also I was thinking about possible app-to-app communication with new App Du Quarter application in future.
>we could open it with the process ID that occupies the port to allow user to see more details or manipulate with the process.

Yes that's a great use-case.
The app in development is a process manager, so yes we can do that. We've come up with a slight modification to Swagger in order to document the shape of the data that can be sent/received. I think we'll be able to show that when the app gets into users hands in Q1.


You might want to think about what commands your own app could accept.
Let's say the process manager wants to go in the opposite direction: you have a process that's in a zombie state, so you want to see if it's attached to a socket? So, the process manager could provide the PID to your app.

How to code it:
The concept is described here https://github.com/zowe/zlux/wiki/App-to-App-Communication and you can see it in action in the sample apps, and a tutorial of how we coded them here https://github.com/zowe/sample-angular-app/tree/lab/step-3-app2app-complete
But, those just cover app2app v1.
v1 is where a caller uses a global function and give it data, possibly the data includes a callback. The listener listens by a zowe-specific api.
v2 is entirely based on Custom Events. The caller uses the global function to make a request, with data, which generates a Custom Event and the listener handles the Custom Event.

It's not necessary to use app2app for things that can be done through rest API better, but app2app can be used for things like workflows, or to "open X in Y", such as when you want to open a file but your app isnt good at being an editor.

**Comment by 1000TurquoisePogs** [comment]
I'm closing this one because the work has progressed and is being tracked in #618
