### ISSUE TITLE
ZWED0159W - Plugin (org.zowe.terminal.tn3270) loading failed. Message: "ZWED0047E - Proxy (undefined:undefined) setup failed.

### ISSUE THREAD

**Issue by pierremontel** [zowe/zlux#556]
I am running Zowe 1.13 and I am getting the following messages into ZWESVSTC:
ZWED0159W - Plugin (org.zowe.terminal.tn3270) loading failed. Message: "ZWED0047E - Proxy (undefined:undefined) setup failed.

I have found that this can be ignored and should not occur above Zowe 1.11.
Is it still Okay to ignore it?

**Comment by 1000TurquoisePogs** [comment]
Different error (47E vs 47W).
This one actually means that you're using the app server with the 3270 terminal but the app server cannot find ZSS.
Did you get past this or is it still an issue? If the app server cannot find ZSS I am just expecting there to be other issues. Can you explain a bit about your zowe configuration?

**Comment by pierremontel** [comment]
The problem disappear in r14. No clue why but I am good now.
Thanks for your feedback.
Regards,
Pierre
