### ISSUE TITLE
How to configure Zowe Editor

### ISSUE THREAD

**Issue by pierremontel** [zowe/zlux#557]
I try to use the Zowe Editor but nothing occurs.
Per the documentation it is written that the language server settings must be updated but I have not found how to do it and why it is not working like for the other application automatically.
Here is the contents of the URL:
{"domain":"ws://localhost:3000","endpoint":{"hlasm":"asmServer","json":"jsonServer"}}
Any assistance is welcome as I really have no clue what to put here and where as how.
Thanks for your advice.
Pierre

**Details**
 -  Version '1.13.0+20200623'  
 - Test environment:  MONOPLEX,, z/OS Rev 232, ACF2,

**Comment by 1000TurquoisePogs** [comment]
Hi Pierre. Is this still happening to you? If so, can you provide us with the output from what you see in the browser's "developer tools" console and network tabs during the time in which you see nothing in the editor, or see the expiration warning? You can access it from menus or by pressing f12 in most browsers.

**Comment by pierremontel** [comment]
Hi,
I have no longer the problem with the version r14.
So this seems to have been a problem in r13.
You can close this ticket.
Thanks for the feedback.
Pierre
