### ISSUE TITLE
Gateway returns not-trusted certificate error when accessing Desktop through Gateway

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zlux#566]
**Description:**

If we turn on verifying certificates by setting `ZOWE_APIM_VERIFY_CERTIFICATES=true`, we see error when visiting Desktop through Gateway:

```
{"messages":[{"messageType":"ERROR","messageNumber":"ZWEAM511E","messageContent":"The certificate of the service accessed using URL '/ui/v1/zlux/' is not trusted by the API Gateway: Certificate for &lt;S0W1&gt; doesn't match any of the subject alternative names: [s0w1.dal-ebis.ihost.com, 192.86.32.67, localhost.localdomain, localhost, 127.0.0.1]","messageKey":"org.zowe.apiml.common.tlsError"}]}
```

**Possible Cause**

The possible reason is when we setup certificate, we use full domain name as `ZOWE_EXPLORER_HOST` to be `s0w1.dal-ebis.ihost.com`. So this domain is put into certificate, not the short domain name like `S0W1`. When Desktop registers itself to Discovery server, it's hardcoded to use `os.hostname()` which only contains short name. This could be the code caused the issue https://github.com/zowe/zlux-server-framework/blob/staging/lib/index.js#L325. I believe if we use the value of `ZOWE_EXPLORER_HOST`, this problem should be resolved.

@NakulManchanda

**Comment by NakulManchanda** [comment]
Eg.
![image](https://user-images.githubusercontent.com/4791635/102262590-52a46000-3ee1-11eb-8c88-050c2c88c9bb.png)

**Comment by NakulManchanda** [comment]
We need to converge on these two values
only hostname, ZOWE_EXPLORER_HOST - which is added as trusted host
Node.js Hostname/IP doesn't match certificate's altnames
![image](https://user-images.githubusercontent.com/4791635/112221959-7a9d1100-8bfe-11eb-9818-58b639287444.png)
