### ISSUE TITLE
explorer-ui icons don't show up in docker build

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zlux#572]
From the docker tests, you can see the explorer ui icons missing in the menu
![image](https://user-images.githubusercontent.com/35110159/104934520-22e5ed80-59a2-11eb-8762-6c5cb4e71651.png)

**Comment by NakulManchanda** [comment]
we still need to verify both:
But released with probable fix:
https://github.com/zowe/explorer-jes/tree/v1.0.10
https://github.com/zowe/explorer-mvs/tree/v1.0.11
https://github.com/zowe/explorer-uss/tree/v1.0.10

**Comment by NakulManchanda** [comment]
Item tested with local zowe docker build as well as on staging branch.

**Comment by NakulManchanda** [comment]
tagging images as binary resolved the issue. Thanks!
