### ISSUE TITLE
Enhance Mediation layer config to add distinct hostname for api ml

### ISSUE THREAD

**Issue by NakulManchanda** [zowe/zlux#575]
API ML is comprise of discovery service, gateway service, catalog and new caching service.
In multicontainer scenario like `kubernetes`, they can all be on different host. 
We can enhance `mediationLayer` config with new properties like `gatewayHost` fallback to existing `hostname` for backward compatibility.

Example - new optional override for gateway host - `"gatewayHost":"gatewayService.host.com"` 
```
"mediationLayer": {
      "enabled": true,
      "server": {
        "hostname": "discoveryService.host.com",
        "port": 47553,
        "gatewayHost":"gatewayService.host.com",
        "gatewayPort": 47554,
      }
    }
```

Additional Info:
Discovery Service info is use to complete dynamic eureka registration
Gateway Service used by sso-auth plugin, to verify token.

Requested by: @markjhollands

**Comment by 1000TurquoisePogs** [comment]
closing because work is done here
https://github.com/zowe/zlux-app-server/pull/153
https://github.com/zowe/zlux-server-framework/pull/273
