### ISSUE TITLE
Updates to RECFM=F datasets fail if the record gets too long

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zlux#576]
In the file Editor, Updates to RECFM=F datasets will fail if the record gets too long; 

Mitigation:  Select the whole file using CTRL+A to see the hidden spaces at EOL, remove them and re-do the SAVE.

It would be good to have a mechanism that prevented lines exceeding the LRECL.  You'd have to warn the user if the record gets too long.  

It would also be good to indicate the are of the record where you can type data, perhaps by colour (bad for accessibility because not everyone can see colour) or by an EOL marker or a fixed-width box.  The boundaries of the box would be visible if the window was wide enough.

**Comment by 1000TurquoisePogs** [comment]
Should we just omit the spaces anyway? The inclusion of spaces was just to be literal, but I think it's a source of confusion and error. 

I believe it could be accomplished by substituting this https://github.com/zowe/zowe-common-c/blob/master/c/datasetjson.c#L101 for a "trimRight" + "jsonAddString" command.
