### ISSUE TITLE
Editor incorrectly wraps the file body in an extra layer of JSON if the dataset SAVE fails.

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zlux#578]
The editor incorrectly wraps the file body in an extra layer of JSON if the dataset SAVE fails.

This is quite a bad error because it corrupts the user's data.  

How it works.  The editor carries the file data contents in a data object.  To save the file, the editor wraps the object in JSON and sends the result on the POST `/datasetContents` API call.  However, the current logic updates the object in-situ, so that if the POST fails, it now has the data contents wrapped in JSON.  For the next save attempt, it wraps it in JSON again, and so on.  The logic to wrap it in JSON needs to be disentangled from the in-situ copy of the dataset.

**Comment by John-A-Davies** [comment]
This seems to happen whether the SAVE fails or not; two saves in a row produce the error.

**Comment by timgerstel** [comment]
Relevant PR/file changed: https://github.com/zowe/zlux-editor/pull/199/files#diff-3a9d2cb83ebc7e73ccee10608527f0bfeaca2f045636778b00ff188f92840c87R570
