### ISSUE TITLE
Can't logon zowe desktop with TSO userid

### ISSUE THREAD

**Issue by lesliezhao** [zowe/zlux#58]
![zlux](https://user-images.githubusercontent.com/13866530/50225514-bd4a6000-03db-11e9-9040-e508336d6c92.jpg)

The userid "IBMUSER" is the tso user id and has been connected to IZUADMIN group. i can use this user id "IBMUSER" to logon the zOSMF, but can't logon zowe desktop, does anyone know how to fix this isse or how can i logon the zowe desktop ?

**Comment by carabanchel** [comment]
Hi again,
On mainframe the ZOWESVR server sho  ws the following msg:

[2018-12-21 08:54:24.552 _unp.utils WARNING] - Callservice: Service call failed.
{ Error: getaddrinfo ENOTFOUND localhost localhost:8544                         
    at errnoException (dns.js:28:10)                                            
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)               
  code: 'ENOTFOUND',                                                            
  errno: 'ENOTFOUND',                                                           
  syscall: 'getaddrinfo',                                                       
  hostname: 'localhost',                                                        
  host: 'localhost',                                                            
  port: 8544 }                                                                  


Does anyone know where or how would be possible to manage this varriable, parm, etc...???

**Comment by 1000TurquoisePogs** [comment]
If you get a service call fail eith ENOTFOUND, this means the zowe app server (zluxServer) is unable to connect to zssServer. zssServer should be at localhost:8544, but it could be that either it is not running, or localhost was not a valid hostname on the machine. The release after 0.9.4 will have better checks for this so it will be more obvious, but also we're updating zluxServer to allow for configuration of address binding, which will make this default to '127.0.0.1' or '::1' instead of 'localhost'.

**Comment by carabanchel** [comment]
Thanks @1000TurquoisePogs 
I guess that this configuration is located on USS. 
What is the configuration file where I can set or fix hostname parm???
I'm using an IBM zD&T (z/OS emulator on x86 Linux) and on mainframe the IP and DNS is 10.1.1.2(default). It was nated during zD&T install on x86-linux  .  
I was looking for on  
z/OS=/usr/productos/zowe/0.9.4/zlux-example- server/deploy/instance/ZLUX/serverConfig/zluxserver.json -

it's only one place where i've found port 8544 references.

**Comment by carabanchel** [comment]
+ info 
I've inserted one line with my DNS "hostname" : "My.DNS",   previous to the row "port" : 8544, on every zluxserver.json, but problem continues. it seems the thisvalue is resolved via getaddrinfo.

**Comment by carabanchel** [comment]
I got it. Just including 127.0.0.1 localhost in RESOLVER on tcpip parms library 
of mainframe. Not necessary IPL, via "MODIFY RESOLVER,REFRESH" command.

**Comment by carabanchel** [comment]
I got it. Just including 127.0.0.1 localhost in RESOLVER on tcpip parms library 
of mainframe. Not necessary IPL, via "MODIFY RESOLVER,REFRESH" command.
