### ISSUE TITLE
Per-server container: App-server

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#586]
As an alternative to the docker image "server-bundle", create docker images for each server (app-server, jes explorer, uss explorer, mvs explorer) which follow best practices for use with kubernetes and openshift, while still maintaining a high degree of doc & feature compatibility with zowe features found on z/os (as is also a goal of "server-bundle")

Related items:
https://github.com/zowe/zowe-container-sample/issues/11
https://github.com/zowe/zlux/issues/587
https://github.com/zowe/zlux/issues/575

## Tasks
* Research: where do plugins belong? (own container, mounts)
* Remove hardcoding from zowe-install-packaging for components, so only 1 (any 1) component can exist in an environment
* Create upgrade documentation: how to go from z/os or from server-bundle to app-server image
* Kubernetes configuration mapping: how do convert to instance.env or server.json
* Mounts: do they change?
* Keystore: does orchestration have another "type" of key storage that our keystore needs to accomodate

Tasks to be done

1)  how do people download things
someone needs to set up jfrog to host docker stuff (docker repo, and/or helm if they are different)
- this can be postponed by having a tar-to-image translation by which a tar from github could contain all content and an image can be made from it as an extract-and-copy operation.

2) how do people know what to do with what they download
someone needs to write documentation that explains things clealrly like
- how to get the code (step 1)
- how to configure the code
- how to start
- how to stop
- how to add 3rd party components

3) how do 1st party components get released
someone needs to make some jenkins/github actions to release images
someone needs to put those images onto jfrog when release is ready

4) how to 3rd party components get made
someone needs to make a set of tools (probably also used by 1st party components) to make all of the scripting & config stuff standardized and simple

someone needs to write a conformance program around things we know will/wont work

5) how do people migrate to/from zos
someone needs to write migration scripting

6) how to people upgrade
someone needs to write this doc chapter

7) how are zos depdencies spotted
someone needs to enhance manifest spec so that zos depedencies can be identified

8) how are runtime depedencies managed?
someone needs to make examples about init container scripts (probably being used in step 3 for 1st party components such as jes explorer needing apiml)

**Comment by NakulManchanda** [comment]
Created PR https://github.com/zowe/zowe-container-sample/pull/16 @1000TurquoisePogs

**Comment by 1000TurquoisePogs** [comment]
App-server container is now being built, so closing this epic. We'll make more specific tickets as needed.
