### ISSUE TITLE
Cannot use git 2.18 or above without many clone warnings

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#61]
In Git 2.18 for platforms other than z/os, support was added for a statement in .gitattributes files, `working-tree-encoding`, which overlapped in purpose and name with a command on git for z/os. This command is used to checkout files as a certain encoding that may differ from what is stored within git. On z/os, it is convenient to have many text files checked out as EBCDIC, but many other platforms don't have the tooling to convert to EBCDIC, nor would they want to as most editors do not interpret EBCDIC. Therefore, in git 2.18, use of `working-tree-encoding` for z/os needs is broken.

**Comment by bluecmd** [comment]
This seems to be still happening even for the modules that have been updated:

```
[bluecmd]$ head zlux-ng2/README.md
㈉�@�������@���@���@������������@���
```

May I suggest this issue is kept open until all the referenced PRs are merged as well as the submodule revs are updated to include the fixes.

**Comment by 1000TurquoisePogs** [comment]
Reopening until all are merged.
