### ISSUE TITLE
Automated test of zss api for client crash

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#616]
If a client (Desktop Editor primarily) crashes when holding a lock in ZSS, what happens?
Ideally, the lock is removed because ZSS senses this, perhaps by lack of heartbeat.
We need tests to prove that locks are removed when we expect them to be removed, in a failure case like this.

**Comment by NakulManchanda** [comment]
![image](https://user-images.githubusercontent.com/4791635/107464171-afad4280-6b2d-11eb-9abe-75bcb5baff0b.png)

**Comment by NakulManchanda** [comment]
![image](https://user-images.githubusercontent.com/4791635/107466508-277d6c00-6b32-11eb-8d51-9173f366b16c.png)
