### ISSUE TITLE
Change zlux to release before building Zowe RC

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zlux#623]
To fully automate the Zowe build and release process, we would like to suggest zlux can be released before building Zowe RC. The "release" here means we have proper source code tags. If we find issues in zlux build, we can release a newer version and bring into Zowe RC.

The benefits of this change will be:

- We can fully automated the process after RC is confirmed to final release without waiting for zlux source tag updating.
- we can automatically run license scan and generate correct license when we build Zowe RC
- People should see correct license file when they check RC build.

**Comment by 1000TurquoisePogs** [comment]
We have the ability to do this, it's just a process thing. Remind @struga0258 and it will be done.

**Comment by struga0258** [comment]
Next release i will create the tags when building the pax's for RC.
