### ISSUE TITLE
Automate TLS setup for ZSS

### ISSUE THREAD

**Issue by lchudinov** [zowe/zlux#632]
Make ZSS support secure connections and automate TLS setup for ZSS.

**Comment by 1000TurquoisePogs** [comment]
https://github.com/zowe/zlux-server-framework/pull/271
https://github.com/zowe/zss/pull/226
https://github.com/zowe/zlux-app-server/pull/151
https://github.com/zowe/zowe-common-c/pull/199

**Comment by 1000TurquoisePogs** [comment]
This was done in I believe 1.20
