### ISSUE TITLE
Spike: investigate/experiment limitations of deploying App Server and plugins in cluster

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#646]
What happens to app-server objects and features when running stand-alone in a docker container with no other parts of zowe?
Check topics such as:
- File storage (configjs), does it need to be shared by all instances of app-server? as a mount?
- How can multiple App Servers share plugin registration information (need to share instance dir mount?)
- For plugins rely on zss (like explorer-ip) what does app-server need to do in communication with zss to be able to contact zss properly
- How does the option to turn off node.js cluster work within docker scenario?

**Comment by NakulManchanda** [comment]
@1000TurquoisePogs @jackjia-ibm 
will try replication and share results
suggestion is use shared `instance-volume` and it should work as expected


Will try on my local setup with PR
https://github.com/zowe/zowe-container-sample/pull/16

**Comment by 1000TurquoisePogs** [comment]
We haven't seen issues other than that plugins that use zss need a warning printed to remind people that they also need to be installed on z/os in order to have the plugin work 100%.
