### ISSUE TITLE
Spike: Where should ZIS plugin metadata recorded

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#655]
Because ZIS plugins arent really REST APIs, they arent really part of "dataservices" in the app framework today. Therefore, we dont see any mention of them in the current pluginDefinition.json files.
Now that we have both pluginDefinition.json files and a superset packaging metadata object called "manifest" for "components", there's a question of whether we should record ZIS metadata in pluginDefinition.json, or manifest.yaml...
Ultimately, the difference between the two matters at install time:
If in pluginDefinition.json, then component-install.sh can call install-app.sh,
If not, then component-install.sh needs to call a different script, such as zis-plugin-install.sh https://github.com/zowe/zss/blob/staging/bin/zis-plugin-install.sh

**Comment by DivergentEuropeans** [comment]
PR: https://github.com/zowe/docs-site/pull/1729
