### ISSUE TITLE
ZIS Plugin Install Improvement

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#656]
Problems:

Installation currently done by script not in instance directory (same problem for component install)
Installer requires several arguments, could be reduced by using attributes to be recorded in instance
Install not done by component installer
Install not formalized in conformance program, should be by way of component manifest
ZIS finds plugins within same dataset as itself, but dataset is recreated during upgrade... plugins get lost.

Proposal:

Record ZIS attributes in instance by storing the attributes in /tmp during install-time, and writing them to instance at instance creation time
Put ZIS plugin installer, and/or component installer into instance
Formalize manifest properties for ZIS plugins
Provide a secondary dataset exclusively for plugins, that does not get erased on upgrade.
Update conformance program to ensure smooth ZIS plugin usage

Work started here: https://github.com/zowe/zowe-install-packaging/pull/1756 but feel free to start from scratch if you have better ideas.

**Comment by 1000TurquoisePogs** [comment]
I started this but never finished https://github.com/zowe/zowe-install-packaging/pull/1756

@joepun76 if you want to get involved let me know.

**Comment by NakulManchanda** [comment]
Some install information about existing ZIS
```
I believe ZIS is Zowe Cross Memory Server that has default procedure name ZWESISTC.
1- When we install Zowe by running zowe-install.sh :
     A) It creates two data sets hlq.SZWESAMP and hlq.SZWEAUTH
     B) ZIS procedure (ZWESISTC), ZIS PARMLIB (ZWESIP00), and ZIS AUX procedure (ZWESASTC) are copied into hlq.SZWESAMP
     C) ZIS load modules (ZWESAUX, ZWESIS01) are copied into hlq.SZWEAUTH
2- Then we need to copy ZWESISTC and ZWESASTC into PROCLIB, so that we can start that by command S ZWESISTC.
3- In ZWESISTC, we need to specify where PARMLIB member ZWESIP00 and module ZWESIS01 picked up from
//STEPLIB  DD   DSNAME=hlq.SZWESAMP,DISP=SHR
//PARMLIB  DD   DSNAME=hlq.SZWEAUTH,DISP=SHR
All above steps are done manually, but I recall that in early releases of Zowe, such as Zowe 1.13.0 we were able use a script runtime/scripts/utils/zowe-install-xmem.sh to do that all above steps automatically.
```

**Comment by NakulManchanda** [comment]
@Martin-Zeithaml @joepun76 if you guys would like to help would be great!

**Comment by 1000TurquoisePogs** [comment]
Much of this was done in v2.
