### ISSUE TITLE
Login failure on Desktop when ZSS- TLS is disabled in Zowe 1.21.0

### ISSUE THREAD

**Issue by NayerNajafi** [zowe/zlux#658]
In Zowe 1.21.0, there is a new variable added to instance.env:
`ZOWE_ZSS_SERVER_TLS=true # Set this to false if you need to use ZSS without TLS (Backward-compat). May be needed if encountering desktop login failure due to app-server to ZSS communication failure`

When we disable TLS and sets this variable to false, Desktop login fails. It works when we add `ZWED_agent_mediationLayer=false` 
 to instance.env.
@NakulManchanda

**Comment by NakulManchanda** [comment]
i believe we need to adjust this conditionally based on `ZOWE_ZSS_SERVER_TLS`
https://github.com/zowe/zss/blob/fd0f46566d38ee4d8b4c8ac4be063a20d027eacd/apiml-static-reg.yaml.template#L7

Even after that we may need `ZWED_agent_http_ipAddresses=0.0.0.0` or  `ZWED_agent_http_ipAddresses=$ZOWE_EXPLORER_HOST` as apiml static registration have problem with `http://localhost`

so, even after conditional change **for backward compatibility user may need to do following:**
```
ZOWE_ZSS_SERVER_TLS=false
ZWED_agent_http_ipAddresses=$ZOWE_EXPLORER_HOST or ZWED_agent_http_ipAddresses=0.0.0.0
```
