### ISSUE TITLE
Cannot tag previously untagged file

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#660]
1) Create untagged file in USS
2) Open the blank file in Editor
3) Save the new file and attempt to tag
4) It tags the file on USS, but it's permanently untagged until you refresh the tree on the left, prompting you to pick a tag over and over again. The dropdown doesn't appear to be filled when I select one either.
It seems the file tree (zlux-file-explorer) does not refresh the tag state under this circumstance.

**Comment by AdarshdeepCheema** [comment]
transfer the ownership to @AdarshdeepCheema
