### ISSUE TITLE
App server doesn't automate certificate chain loading

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#661]
CA's are a chain of the root CA & >= 0 CA's . Zowe environment variables only state what root CA is and App server doesn't know there are other CA's, so if App server receives a certificate from the ML which is signed by an intermediate, that the App server doesn't know about, it will reject it as an unknown certificate.

Current workaround: Manually state to App server the intermediate CA's.

Typically they're in the keyring or in the same directory as root CA so why can't App server auto-discover them? The server should load all CA's in a specific location, but scanning a keyring for other CA's may be difficult

The Explorers may not have this issue so what are they doing different from us?

**Comment by vit-tomica** [comment]
@1000TurquoisePogs FYI, a new version of [keyring_js](https://www.npmjs.com/package/keyring_js) is published. It has the ability to list SAF keyring content.

**Comment by 1000TurquoisePogs** [comment]
Outdated ticket, fixed in either 1.27.2 or 1.28.0
