### ISSUE TITLE
Spike: Migrate script to-from zos

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#663]
Have 1-2 scripts that are shipped on z/os server installs of zowe which takes in keystore and instance directories as arguments and if compatible with docker, will output converted keystore and instance directories to a different location.
The script(s) will convert to and from a z/os install format and a docker install format.
However, not all options in zowe work on both z/os and docker, such as keyrings, so when attempting to convert a z/os configuration to a docker configuration, the scripts must validate the configuration and possibly return in an error stating if the configuration is incompatible with the requested conversion.

**Comment by NakulManchanda** [comment]
- take backup of existing Keystore on z/OS
- run script on docker host and reuse parts like `Certificate Authority`
- add new docker hostname to valid list of `Alt Names`
