### ISSUE TITLE
Explorer UI: Security Updates

### ISSUE THREAD

**Issue by NakulManchanda** [zowe/zlux#666]
Need to update packages for explorer ui repos
- orion-editor-component -> released new version
- explorer-fvt-uitilies -> released new version
- explorer-jes -> released new version
- explorer-mvs -> https://github.com/zowe/explorer-jes/pull/261
- explorer-uss -> https://github.com/zowe/explorer-uss/pull/125

Orion Editor - updated react version, didnt notice anything breaking
JES - just Orion editor update
MVS - material from 1.x to 4.x, react, webpack update - no code changes required
USS - material update from 0.18 to 4.x, React updates - most code changes required

**Comment by NakulManchanda** [comment]
Hi @skurnevich 
will need help testing above updates.
Released explorer-jes - did try out manually, and passing all test.
Holding release for MVS, USS - for 1.22
Thanks

**Comment by NakulManchanda** [comment]
Hi @skurnevich , you can use this build to test explorers
[Custom Explorers Zowe Build](https://zowe.jfrog.io/artifactory/libs-snapshot-local/org/zowe/1.22.0-PR-2093/zowe-1.22.0-pr-2093-28-20210603061133.pax)

**Comment by skurnevich** [comment]
Hi @NakulManchanda, I tried the explorers from this custom build, looks good to me as well, thanks
