### ISSUE TITLE
Automate installing ZIS plugins

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#670]
Currently, ZIS plugins are put into the same DS that ZIS exists in, this a problem so we should have a DS just in use by plugins.

AC:
Add additional parameter & default for what the name of the DS should be & then add logic to install script to create the DS & then add DS to ZIS JCL so that ZIS is able to use the DS on start-up

When we say make a second dataset just for plugins, we mean make another LOADLIB here https://github.com/zowe/zowe-install-packaging/blob/master/scripts/zowe-install-MVS.sh#L24 but leave it empty.

When we say adding the new plugins-only dataset to the ZIS JCL, we mean adding an extra STEPLIB to a second dataset here https://github.com/zowe/zss/blob/staging/samplib/zis/ZWESIS01#L49

Relates to #667 because this DS should also be listed in instance.env after creation

**Comment by DivergentEuropeans** [comment]
PR: https://github.com/zowe/docs-site/pull/1729
https://github.com/zowe/zowe-install-packaging/pull/2215
