### ISSUE TITLE
Session security call authenticate failed for auth handler org.zowe.zlux.auth.safsso. 

### ISSUE THREAD

**Issue by lzuckett** [zowe/zlux#673]
I upgraded to 1.22.0 and since upgrading I am unable to logon to desktop.  I receive on the logon screen:

![image](https://user-images.githubusercontent.com/67926731/123156863-d2cef380-d437-11eb-8a8e-81c04d0b8996.png)

and in the log for ZWES

Session security call authenticate failed for auth handler org.zowe.zlux.auth.safsso. Plugin response: {"success":false,"error":{"message":"ZSS 500 Internal Server Error"},"reason":"ConnectionError","apiml":true,"zss":true,"sso":false,"canChangePassword":true}

I attached the joblog from ZWESVSTC started task.  

As a note I am running nodejs 12.16.1.  I attempted to upgrade this before installed 1.22,  but IBM download site is apparently having issue.

**Comment by lzuckett** [comment]
I also validated the troubleshooting steps https://docs.zowe.org/stable/troubleshoot/app-framework/app-troubleshoot.html#nodejsapp-disables-immediately

all services are running at APIML:

![image](https://user-images.githubusercontent.com/67926731/123157623-c5fecf80-d438-11eb-9f40-544303d79771.png)

ZIS status is ok:
ZWES1014I ZIS status - 'Ok' (name='ZWESIS_STD      ', cmsRC='0', description='Ok', clientVersion='2')        

I do have a endpoint failure 

TCOMVS INFO (_zsf.apiml,apiml.js:279) ZWED0020I - Registering at https://mstrsvw.lvn.broadcom.net:7553/eureka/apps                  
TCOMVS WARN (_zsf.apiml,EurekaClient.js:710) Eureka request failed to endpoint https://mstrsvw.lvn.broadcom.net:7553/eureka/apps, ne
TCOMVS CRITICAL (_zsf.bootstrap,plugin-loader.js:927) connect ECONNREFUSED 10.175.80.48:7554                                        
TCOMVS CRITICAL (_zsf.bootstrap,plugin-loader.js:959) connect ECONNREFUSED 10.175.80.48:7554                                        

but I see port 7553 connected:

MVS TCP/IP NETSTAT CS V2R4       TCPIP Name: TCPIP           19:41:36    
User Id  Conn     Local Socket           Foreign Socket         State    
-------  ----     ------------           --------------         -----    
ZWE1AC   004674C3 10.175.80.48..15210    10.175.80.48..7553     Establsh
ZWE1AC   004674BD 10.175.80.48..15209    10.175.80.48..7553     Establsh
ZWE1AC   004674BB 10.175.80.48..15208    10.175.80.48..7553     Establsh
ZWE1AD   00467319 10.175.80.48..7553     10.175.80.48..15089    Establsh
ZWE1AD   004674C4 10.175.80.48..7553     10.175.80.48..15210    Establsh
ZWE1AD   004674BC 10.175.80.48..7553     10.175.80.48..15208    Establsh
ZWE1AD   00464D01 0.0.0.0..7553          0.0.0.0..0             Listen   
ZWE1AD   004674BE 10.175.80.48..7553     10.175.80.48..15209    Establsh
ZWE1AG   00467317 10.175.80.48..15089    10.175.80.48..7553     Establsh

and port 7554 listening

MVS TCP/IP NETSTAT CS V2R4       TCPIP Name: TCPIP           19:42:21     
User Id  Conn     Local Socket           Foreign Socket         State     
-------  ----     ------------           --------------         -----     
ZWE1AD   00464DF0 10.175.80.48..12494    10.175.80.48..7554     ClosWait  
ZWE1AG   00464D2A 0.0.0.0..7554          0.0.0.0..0             Listen    
***

**Comment by lzuckett** [comment]
[ZWESVSTC.txt](https://github.com/zowe/zlux/files/6704505/ZWESVSTC.txt)

**Comment by lzuckett** [comment]
I also see the ECONNREFUSED can be ignored:

![image](https://user-images.githubusercontent.com/67926731/123158605-03179180-d43a-11eb-8f16-daeab4f65d5b.png)

**Comment by 1000TurquoisePogs** [comment]
I don't recommend uploading ZWESVSTC if there is anything sensitive in it.
 You can reach out via mailing list or slack direct message if you want to send it to someone specific rather than putting it on github where it's easy for others to see.

But from what I see, `ZOWE_ZSS_SERVER_TLS=false` is set yet ZSS says it is using HTTPS. The app-server seems to be respecting `ZOWE_ZSS_SERVER_TLS` yet ZSS is not, so when app-server contacts ZSS, the connection fails due to wrong connection type.
I don't see why ZSS does not respect this, but can you try setting `ZOWE_ZSS_SERVER_TLS=true` in the instance.env file to see if that works better? In that case, I expect that both servers will agree upon https being used, leading to success.

**Comment by lzuckett** [comment]
hello,  there is nothing sensitive in the attached startup. Not used for production.

**Comment by lzuckett** [comment]
Ok,  I had that set to to true and changed it.  Let me change it back and see what happens.

**Comment by lzuckett** [comment]
Ok,  I am logged on.  I think I just didn't give it enough time to startup.
