### ISSUE TITLE
Eureka client failover to multiple discovery servers

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#674]
App-server only talks to 1 discovery server right now, so in an HA environment, if there is more than one, but the first one stops or crashes, then the app-server heartbeats go nowhere, leading to the app-server now longer being part of the HA environment.

The fix we need is to have the app-server read the environment variable that lists alll the discovery servers, and have it failover its connection to the next one on the list when the one its currently talking to fails. It appears that the eureka-js-client library that we use may already support this feature so we just need to give it the right env var input.

**Comment by lchudinov** [comment]
This issue depends on https://github.com/zowe/zowe-install-packaging-tools/pull/11

**Comment by lchudinov** [comment]
the issue should be resolved by https://github.com/zowe/zlux-server-framework/pull/311.
