### ISSUE TITLE
explorers do not accept spaces in keyring variables

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#677]
https://github.com/zowe/explorer-mvs/blob/master/bin/start.sh#L44-L52
https://github.com/zowe/explorer-jes/blob/master/bin/start.sh#L44-L52
https://github.com/zowe/explorer-uss/blob/master/bin/start.sh#L44-L52
https://github.com/zowe/jobs/blob/master/jobs-zowe-server-package/src/main/resources/bin/start.sh#L34-L36
https://github.com/zowe/data-sets/blob/master/data-sets-zowe-server-package/src/main/resources/bin/start.sh#L33-L35

None of the above lines put the keyring or keystore variables in quotes. When these paths or object names include spaces, they can be incorrectly parsed according to however the receiver chooses to parse arguments. We've witnessed that when spaces are included in keyring variables, only the characters up to the first case are used resulting in "not found" sorts of errors.

**Comment by jthyssenrocket** [comment]
I am not a java expert, so not sure if it is needed, but the Java based components have options like
-Dserver.ssl.keyAlias=${KEY_ALIAS} \
Should it be
-Dserver.ssl.keyAlias="${KEY_ALIAS}" \
? 

./gateway/bin/start.sh
./discovery/bin/start.sh
./jobs-api/bin/start.sh
./files-api/bin/start.sh
./caching-service/bin/start.sh
./api-catalog/bin/start.sh

**Comment by jthyssenrocket** [comment]
Deleted comment. You already had the java based components.

**Comment by AdarshdeepCheema** [comment]
Made the specified changes
