### ISSUE TITLE
Problems logging Desktop

### ISSUE THREAD

**Issue by AlbertoGCMF** [zowe/zlux#679]
Hello,

We're finding some problems at logging at Desktop in an instance of Zowe after upgrading it to 1.15 ("Authentication failed for 1 types. Types: ["zss"]"

We had two instances of the product in the same system of our sysplex, each one with his own z/OSMF, using the same Zowe software installation path, so the unique diference between them is the configuration path, where we have it defined to use different ports (But the same IP address).

One of the two instances, can log in to Desktop without any problem, but in the other one, we found the message related. Looking in the log, also found that messages indicating problems:

ZWED0070I - -sZxfgkeUbpW3hULmBabzR_ryrf9kEjz: Session security call authenticate succesful for auth handler org.zowe.zlux.auth.trivial. Plugin response: {"success":true}
ZWED0171W - Rejected undefined referrer for url=/login, ip=192.168.30.227                                                          
ZWED0003W - -sZxfgkeUbpW3hULmBabzR_ryrf9kEjz: Session security call authenticate failed for auth handler org.zowe.zlux.auth.zss. Plugin response: {"success":false}

Searching in troubleshooting guide, are pointed two possible issues for that errors:

- ZSS server unable to communicate with X-MEM: I discarded this one, cause in our zssServer log we can see the message indicating the connections works propertly:

ZIS status - Ok (name='ZWESIS_STD      ', cmsRC=0, description='Ok'

- ZLUX unable to communicate with zssServer: We don't have /etc/hosts file pointing to 127.0.0.1 for localhost, but the fact is one of the two instances in the same system is working, so I can't imagine how should the other having problems for that reason

Had someone a similar problem or can help us to understand wath its going wrong with that failing instance?

Please, feel free to ask wathever can help to diagnose.

Many thanks in advance.

**Comment by 1000TurquoisePogs** [comment]
I believe this was solved, so I am closing it.
