### ISSUE TITLE
Passticket API in ZSS

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#683]
Add a ZSS API that allows for getting a passticket provided you have already authenticated with ZSS (either directly or via APIML SS\
O). This must be usable by APIML such that APIML can use this as a replacement for APIML-provided passtickets

**Comment by jandadav** [comment]
It would be interesting to consider this as well, as an potential alternative to ZSS implementation. https://www.ibm.com/docs/en/zos/2.2.0?topic=passticket-incorporating-generator-algorithm-into-your-program#algor

**Comment by 1000TurquoisePogs** [comment]
This will be present in v1.25, so let's close this.
