### ISSUE TITLE
Research how C code can get a passticket

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#697]
Is this a feature we can get through our SAF library already in zowe-common-c?
Is there a BPX call we can do? Or is it a callable service we need assembly for?
Does this require new ESM permissions for the ZSS process?

**Comment by jordanfilteau1995** [comment]
Hi Sean,

You can use the r_ticketserv and/or r_gensec callable services. They support problem state, 31-bit, and 64-bit callers.

r_gensec
https://www.ibm.com/docs/en/zos/2.1.0?topic=3-generate-passticket1

r_ticketserv
https://www.ibm.com/docs/en/zos/2.1.0?topic=rtipe-parameters

You might be familiar with r_admin, which we have an implementation for (https://github.com/zowe/zowe-common-c/blob/620845f70c8543a0b1d59d9185d9927f54eed6f9/c/radmin.c). It should be a similar process for invoking the callable services above. If you do need to implement this yourself, I would start there.

Best,

Jordan

**Comment by 1000TurquoisePogs** [comment]
I also saw this doc, might be the same? https://www.ibm.com/docs/en/zos/2.2.0?topic=passticket-incorporating-generator-algorithm-into-your-program#algor

**Comment by jordanfilteau1995** [comment]
Yes. It is the same algorithm. It seems much more difficult to implement yourself though...

**Comment by 1000TurquoisePogs** [comment]
PR is out on ZSS repo
