### ISSUE TITLE
TN3270 supporting user defined keyboard actions

### ISSUE THREAD

**Issue by Martin-Zeithaml** [zowe/zlux#698]
I would like to have an option to define and use user defined commands (including special keys such Home, Tab etc) in TN3270 application.
- The expected behavior is like a clipboard with the ability of using special keys, which is especially useful in environment like ISPF. 
- This feature should be able to save and load user defined actions. Each user can predefine own set of actions.
- The basic support should contain alfa-numeric keys, F-keys, ctrl and alt combined with other keys.
- The format for saving the action JSON.
- Action will be invoked via button
- User hits button and predefined keystrokes are typed at the cursor position.

**Comment by Martin-Zeithaml** [comment]
This is the current design of data structure for storing the key sequences:

1. ```Normal``` intended to use when need to type text
2. ```Special``` for Enter, Tab, PF1 etc.
3. ```Ctrl``` and ```Alt``` for pressing Control and Alternate key
4. ```Prompt``` for asking for a value, which will be only inserted into the current position

```
export class Keys {
  constructor(
    public normal?: string,
    public special?: string,
    public alt?: boolean,
    public ctrl?: boolean,
    public prompt?: string
  ){

  }
}
```

Each Key Sequence has ```title```, which will be (probably) used in the button, ```description``` for some details and array of keys to be artificially typed.

```
export class KeySequence {
  constructor(
    public title?: string,
    public description?: string,
    public keys?: Keys[]
  ) {

  }
}
```

Entire config (reused from Terminal Config):

```
export class KeySequencesConfig {
  constructor(
    public _objectType: string,
    public _metadataVersion: string,
    public resource: string,
    public contents: KeySequence[]
  ){

  }
}
```

Example of real data:

```
{"keySequences": [
      {
            "title": "SWAP NEXT",
            "description": "ISPF: Swap next command",
            "keys": [
                  { "special":"Home"},
                  { "normal": "E", "ctrl": "true"},
                  { "normal":"SWAP NEXT"},
                  { "special":"Enter"}
            ]
      },
      {
            "title": "DB2",
            "description": "ISPF: P.3.4 -> DB2 Datasets",
            "keys": [
                  { "special":"Home"},
                  { "normal": "E", "ctrl": "true"},
                  { "normal":"START"},
                  { "special":"Enter"},
                  { "normal": "P.3.4"},
                  { "special":"Enter"},
                  { "special":"Tab"},
                  { "normal": "DB2.DB2"},
                  { "prompt": "Type the version, e.g. 710 or A10:"},
                  { "special":"Space"},
                  { "special":"Enter"}
            ]
      }      
  ]
}
```

**Comment by Martin-Zeithaml** [comment]
Quick UI design

The upper config menu is related to connection, same as the "power on/off" button and save button.

It makes more sense to create new panel just for key sequences:

![image](https://user-images.githubusercontent.com/66114686/129336296-0d5e2c13-431b-4c5e-89e9-dbf8b822b5be.png)

**Comment by Martin-Zeithaml** [comment]
Menu simplified as text, new row added to the connection setting
Key sequences loaded from the key sequences config file (workspace)
![image](https://user-images.githubusercontent.com/66114686/130763157-bb3edb2a-f0ec-49bc-a6a4-cec08c0f3a74.png)

**Comment by 1000TurquoisePogs** [comment]
I believe this was resolved by the recently merged PR, so closing this.
