### ISSUE TITLE
Node server tracing

### ISSUE THREAD

**Issue by jplinardon** [zowe/zlux#7]
Node server tracing

**Comment by 1000TurquoisePogs** [comment]
This should be here by now. Formal documentation is being worked on now, but in the meanwhile,
You can enable logging via the server config file, see: https://github.com/zowe/zlux/wiki/Logging#server-startup-logging-configuration

The logs that pertain to the server core are:
_zsf.bootstrap = logging pertaining to the startup of the server

_zsf.auth = logging for network calls that need to be checked for authentication & authorization

_zsf.static = logging of serving static files (such as images) from an App's /web folder

_zsf.child = logging of child processes, if any are being used

_zsf.utils = logging for misc utilities that the server relies upon

_zsf.proxy = logging for proxies set up in the server

_zsf.install = logging for the installation of plugins

_zsf.apiml = logging for communication with the api mediation layer

_zsf.routing = logging for dispatching network requests to plugin dataservices

_zsf.network = logging for the HTTPS server status (is it connected, to what ports, to what IP, etc)
