### ISSUE TITLE
Make 64 bit version of ZSS

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#703]
Probably plugins compiled for 31 bit ZSS will not be compatible with 64 bit ZSS, so we would need to be careful about transitioning people if true.

Idea:
As soon as ZSS can be compiled in 64 bit mode, merge that code into staging branch under a different compile option from 31 bit mode. In our automation, we can build both, but for zowe v1 we will just ship 31 bit mode. In v2, we could either ship both or just ship 64 mode.

Concerns:
How does the compilation of ZSS effect how it interacts with ZIS?

**Comment by DivergentEuropeans** [comment]
@lchudinov completed this
