### ISSUE TITLE
Upgrade Angular version used in Desktop

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#704]
The Desktop currently uses angular 6, but the current version is 12.
Angular lists what the differences between versions are if you intend to upgrade a codebase: https://update.angular.io/?v=6.0-12.0
Let's try to upgrade the version of angular but strive to make the change be minor for existing plugins. I don't think there are too many plugins that use angular versus React or iframe, so it's probably not a big deal except for our own bundled apps, but ideally if we do need to make a breaking change with angular it would be a simple one that ideally could be automatically upgraded using angular upgrade tools, such as `ng update @angular/cli@7 @angular/core@7`

**Comment by DivergentEuropeans** [comment]
duplicate
