### ISSUE TITLE
Editor can't differentiate between files with the same name

### ISSUE THREAD

**Issue by jordanfilteau1995** [zowe/zlux#709]
If there are two files of the same name, the contents are the same as well as the place of the cursor. This is easily repeatable by opening two different files of the same name.

**Comment by 1000TurquoisePogs** [comment]
I have seen this before. Something in the object we're passing to monaco is being tracked by filename rather than pathname.

**Comment by AdarshdeepCheema** [comment]
Could not replicate successfully, closing for now. Please re-open if new replication scenario comes up
