### ISSUE TITLE
Editor no longer defaults to home directory

### ISSUE THREAD

**Issue by jordanfilteau1995** [zowe/zlux#710]
The editor is setting the initial directory to root instead of your home directory as noted in the omvs segment.

**Comment by 1000TurquoisePogs** [comment]
I think it still does, but that there is a timing bug that has been hard to track down. If you retry, does it sometimes work?

**Comment by jordanfilteau1995** [comment]
I've gotten it to work on some and not others. It probably is a timing issue, now that you mention it.

**Comment by lchudinov** [comment]
Yes, it a timing issue. I notice the issue sometimes, too. It's very easy to fix so I'll take care of it when I get a minute.

**Comment by lchudinov** [comment]
The issue should be resolved as soon as we update version of zlux-file-explorer in zlux-editor.
