### ISSUE TITLE
Spike - Implement SHA1 function in C library

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#713]

**Comment by joepun76** [comment]
Two branches are created pre our meeting discussion.

1. Add etag in header.
- a new function generateSHA1Etag(char *filename, int recordLength, char eTag[64]) in ../zowe-common-c/c/datasetjson.c
2. Add etag in body.

Using functions icsfDigestInit(&digest, ICSF_DIGEST_SHA1), icsfDigestUpdate(&digest, buffer, bytesRead) and icsfDigestFinish(&digest, hash) in ../zowe-common-c/c/icsf.c
