### ISSUE TITLE
mvs failed with listing data sets with catalog entries with no data sets behind the name

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zlux#716]
If we define nvsam to put an entry in a catalog with no data set behind it, MVS Explorer will fail to display the list of the content.

`define nvsam(name('ZOWE110.NO.DATASET') devt(3390) volume(T50093))`  only creates an entry for this data set name in catalog, it means you can see the data set via 3.4, but it is just an entry not a physical data set residing on a DISK.

![image (9)](https://user-images.githubusercontent.com/39711029/130500449-1e6dbc3f-9a14-4a1f-8294-b8a1de3bab9b.png)

One thing that I noticed is z/OSMF rest data set api displays this non vsam data set.

![image (10)](https://user-images.githubusercontent.com/39711029/130500485-39d22ec0-bd84-41c1-ad54-8d493c0e4cd9.png)

![image (11)](https://user-images.githubusercontent.com/39711029/130500510-bbdad947-43ca-44ad-bcec-1dd9a2432120.png)

z/OSMF API and Explorer Datasets API can return the list correctly, but MVS Explorer shows `No Datasets found`.

**Comment by AdarshdeepCheema** [comment]
Fixed via https://github.com/zowe/explorer-mvs/pull/197
