### ISSUE TITLE
Help for desktop applications

### ISSUE THREAD

**Issue by Martin-Zeithaml** [zowe/zlux#717]
**Idea**
It would be nice to have some basic help for each or at least some desktop applications.

**Description**
Question mark next to close/minimize/maximize button or menu to be able to display help. For example, there are short cuts defined for TN3270, which are described on the wiki page only. It is not straight forward how to get this type of information, especially for the new users.

**Comment by 1000TurquoisePogs** [comment]
It would be cool if we wrote sections in "Use" in docs.zowe.org and link each app (or the properties viewer app) to its own page.

**Comment by 1000TurquoisePogs** [comment]
It would be cool if we wrote sections in "Use" in docs.zowe.org and link each app (or the properties viewer app) to its own page.
