### ISSUE TITLE
Can't view Plugin Filesystem Layout page

### ISSUE THREAD

**Issue by whtknght30** [zowe/zlux#722]
I was trying to view the Plugin Filesystem Layout page that is on the Home page, but continues to just go back to the home page.

It is linked to the following page.

https://github.com/zowe/zlux/wiki/ZLUX-App-filesystem-structure

Does this page still exist?

**Comment by 1000TurquoisePogs** [comment]
Thanks for asking, yes it does but looks like it got moved. Here it is: https://github.com/zowe/zlux/wiki/Plugin-package-file-structure

**Comment by whtknght30** [comment]
Thanks, I see it now.

**Comment by DivergentEuropeans** [comment]
Thank you @1000TurquoisePogs
