### ISSUE TITLE
Update tn3270-ng2 to angular 12, corejs3, rjx

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#741]

**Comment by 1000TurquoisePogs** [comment]
Talk to @DivergentEuropeans to get the latest desktop build to do angular 12 testing upon. (https://github.com/zowe/zlux-app-manager/pull/376 ?)

**Comment by skurnevich** [comment]
Created branch for the upgrade [feature/upgrade-angular](https://github.com/zowe/tn3270-ng2/tree/feature/upgrade-angular)
