### ISSUE TITLE
[Spike] What versions of angular-l10n, popper.js, jquery, rxjs, corejs, systemjs can we upgrade the desktop to?

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#745]
Determine if there are benefits of upgrading these libraries to newer versions, such as new features developers might want, or better performance, or major security issues with using an old version.
If there's no benefit, its fine to keep our code where it is.
Also evaluate what the breaking changes are. If we upgrade, do extensions break?

**Comment by DivergentEuropeans** [comment]
![image.png](https://images.zenhubusercontent.com/5cf465968d690c7080bd33a8/c5610a31-fb65-4d91-aecd-99a25ca2a9b0)

**Comment by DivergentEuropeans** [comment]
These were the upgrades where I tested minimal conflicts and/or coding changes
