### ISSUE TITLE
[Spike] Put vscode into the zowe desktop

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#755]
Via technologies such as theia running in a container, or the new "Vscode in the web" (https://code.visualstudio.com/blogs/2021/10/20/vscode-dev) (which is cool and new but may not be exactly what we're looking for), try to get vscode into the zowe desktop in a way that allows you to use the Zowe Explorer plugin.
The goal:
- Have vscode in the desktop in a way that lets you target mainframe data, NOT just your own PC data (which is nice if also possible)
- We don't really care if the vscode install also lets you edit in some sandbox in a container somewhere, its really irrelevant to the desktop use cases.

**Comment by DivergentEuropeans** [comment]
@adityadr-joy completed this
