### ISSUE TITLE
Zowe 1.24: missing " around keyring variables in explorer-uss/bin/start.sh

### ISSUE THREAD

**Issue by jthyssenrocket** [zowe/zlux#759]
Packaging issue?? 

Zowe 1.24 installed from ShopZ. 

Zowe 1.24: /components/explorer-uss/bin/start.sh has

        --keyring $KEYRING_NAME \
        --keyring-owner $KEYRING_OWNER \
        --keyring-label $KEY_ALIAS \

Git repo https://github.com/zowe/explorer-uss/blob/master/bin/start.sh#L53 has:

        --keyring "${KEYRING_NAME}" \   	
        --keyring-owner "${KEYRING_OWNER}" \   	
        --keyring-label "${KEY_ALIAS}" \

Alt three explorer's start.sh was fixed in https://github.com/zowe/zlux/issues/677 but the change in  the USS script has not made it into the Zowe 1.24 distribution

**Comment by 1000TurquoisePogs** [comment]
there does not appear to be a packaging problem, and the code you seek is in 1.25
explorer repos follow a different policy than zlux repos for when content goes into master branch and what master branch means.
1.24 had uss v 1.0.15 https://github.com/zowe/zowe-install-packaging/blob/v1.24.0/manifest.json.template#L82 
1.0.16+ did not exist until after 1.24 code freeze.
I can ask around why there was a gap in time between the code merge and the releases using it, but looks like the packaging is working as designed.
