### ISSUE TITLE
tn3270 limited default keymapping (org.zowe.terminal.tn3270)

### ISSUE THREAD

**Issue by markklerks** [zowe/zlux#760]
The current keyboard mapping of the TN3270 app is lacking some default keys, like:
PA1 (PageUp)
PA2 (PageDown)
CLEAR (ESC)
Without these I'm not able to use the app

**Comment by Martin-Zeithaml** [comment]
Hi,

At this moment, the keymapping is hardcoded and cannot be easily changed. There is an initiative to rewrite the terminal code to enable more customization, such as font setting or keyboard mapping.

**Comment by markklerks** [comment]
Thanks Martin,
I don't mind too much it being hard coded, however there are some keys lacking that I need to be able to use the app. That is sad and make it hard to demo to potential users.

**Comment by Martin-Zeithaml** [comment]
And are you aware of these [default key mapping](https://github.com/zowe/tn3270-ng2/wiki/Keyboard-Shortcuts)?
The clear and page up/down is missing there, but there are some other keys.

**Comment by markklerks** [comment]
thanks again, I was not aware of these.

Should they apply for version 0.11.2?
I'm not sure how to interpret ALT+1 and ALT+2, if these refer to the number keys, it does not work over here.

**Comment by Martin-Zeithaml** [comment]
I don't know, when the mapping was introduced, but it is definitely working in version 0.11.2.
ALT+1 is referring to the digit 1, not the number 1 in the keypad.
ALT+1 is working for me as attention key, it is indicated by the **X []** in the left bottom corner of the terminal:

![image](https://user-images.githubusercontent.com/66114686/140943079-50be7982-dc95-4bb8-b6ff-03a520a36948.png)

**Comment by markklerks** [comment]
There are an "Alt" key and an "AltGr" key at the bottom left and right of my keyboard, but pressing these won't do anything.
I think you added a picture but probably due to company internet policies, I'm not able to check that out now.
Later at home I will. 
thanks

**Comment by markklerks** [comment]
For me the left ALT key and the right AltGr key on my keyboard don't do anything.
Can you explain why ALT+1 on your side is 'working as attention key', while the document  you refer to states it as invoking [PA1].
All other default-key mappings mentioned seem to be working perfectly though.

**Comment by Martin-Zeithaml** [comment]
The PA1 is also called generally attention key, under the TSO/ISPF environment it will cause sending the signal for interruption, when you need to for example cancel the viewing of a large file.

**Comment by markklerks** [comment]
got it now, thanks.
In general the P**A1** command, stands for "**A**ttentionkey 1"

However if I key in "PA1" + _enter_ in my IDMS DC map, it scrolls down 1 screen/page
I expect pressing the ALT-key would do the same then (or not? :) )
![image](https://user-images.githubusercontent.com/92708598/141262361-b9a5f6f5-278b-4552-8c6a-0c5e6b3d8f8c.png)

**Comment by Martin-Zeithaml** [comment]
At this moment I don't have access to IDMS on our system, but I will try to get it and test it.
I have quickly discussed this with IDMS guys and they said, the scrolling in IDMS is special :)
I will update this issue when I will get some progress.

**Comment by Martin-Zeithaml** [comment]
Ok, it seems, that this is CA ADS screen? Is that right?
Did you try to press _ALT+1_ and then _Enter_?

**Comment by markklerks** [comment]
(It's a CA IDMS DC screen.)

I'm ashamed to say, with a new attempt, pressing ALT+1 **does** work (now) as shortcut for PA1 and PA2.
No idea what went wrong the first time.

Thank you, so this issue is solved for me by the url you provided to the default key-settings.
👍

**Comment by Martin-Zeithaml** [comment]
No problem, I am glad to help.
I will propose a change to zowe docs to include TN3270 predefined keyboard shortcuts.
