### ISSUE TITLE
Zowe Desktop Editor saving datasets

### ISSUE THREAD

**Issue by markklerks** [zowe/zlux#763]
I would like to save datasets I edited in Zowe Desktop Editor.
Although there is a save option in the menu, using it provides the message: _"Dataset saving not yet supported"_

**Comment by 1000TurquoisePogs** [comment]
Thanks for writing an issue about it, this helps us prioritize.
Actually, this feature was a long time in development and has recently been completed! You should be able to save datasets once zowe 1.26.0 gets released, so check back soon (December)

**Comment by markklerks** [comment]
I'm happy it will be completed, thank you for that. I will look forward to 1.26 👍
