### ISSUE TITLE
Install ZOWE 1.24.0 in SAF keyring

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/zlux#764]
@GilPen commented on [Fri Oct 29 2021](https://github.com/zowe/api-layer/issues/1869)

Hello

I'm trying to upgrade 1.20.1 version to 1.24.0 and I would like to install certificates on a SAF keyring at the same time.

Unfortunatly, the ZLUX port 8544 is not listening for the ZWESVSTC STC.

In the app log, you can see the error message "ZWED0151W - unhandledRejection  TypeError: Cannot destructure property 'userId' of 'parseSafKeyringAddress(...)' as it is null." but I didn't find the details in the message & code documentation.

Config:
ZOS 2.3
nodejs 12.18.0
ZOWE 1.24.0
JAVA 8.0_64
TOP SECRET V16

Regards
Gilles Peniguel

[appServer-2021-10-29-07-17.txt](https://github.com/zowe/api-layer/files/7440099/appServer-2021-10-29-07-17.txt)
[instance.txt](https://github.com/zowe/api-layer/files/7440101/instance.txt)
[zowe-certificates.txt](https://github.com/zowe/api-layer/files/7440102/zowe-certificates.txt)
[ZWESVSTC.txt](https://github.com/zowe/api-layer/files/7440103/ZWESVSTC.txt)

---

@balhar-jakub commented on [Mon Nov 01 2021](https://github.com/zowe/api-layer/issues/1869#issuecomment-956072901)

@1000TurquoisePogs Hey, could you please take a look with WebUI this seems like some issue with the desktop. Could you transfer it to your repo?

---

@GilPen commented on [Tue Nov 02 2021](https://github.com/zowe/api-layer/issues/1869#issuecomment-957163114)

Hello,

Thank you very much for your answer and ypur help.

For my next installations, can you please tell how did you see the problem is the WebUI ? 

Can you tell me also what kind of files you need I transfer ?

Regards
Gilles

---

@GilPen commented on [Tue Nov 02 2021](https://github.com/zowe/api-layer/issues/1869#issuecomment-957237567)

[server.txt](https://github.com/zowe/api-layer/files/7459234/server.txt)

---

@GilPen commented on [Wed Nov 03 2021](https://github.com/zowe/api-layer/issues/1869#issuecomment-959045483)

Hello

I suppose according the log records just below that I bind on IP address 0.0.0.0 

_HTTPS config valid, will listen on: Ý '0.0.0.0'
ZWED0072I - Using Certificate: Ý 'safkeyring:////ZWESVUS/Sysazowering&zowe-sysa.dns21.socgen
unhandledRejection TypeError: Cannot destructure property 'userId' of 'parseSafKeyringAddress(...)' as it is null._

I only put the DNS partition name  in the DOMAIN NAME certificate. Do you think I have to put  "localhost" DSN name  as an alternate in the DOMAIN NAME too ?

Regards
Gilles Peniguel

---

@GilPen commented on [Fri Nov 05 2021](https://github.com/zowe/api-layer/issues/1869#issuecomment-961764775)

Hello

According the text below from documentation, the STC ZSS STC is listening.

Attributes that control ZSS are in the agent object. For example, agent.http.port is the TCP port that ZSS will listen on to be contacted by the App Server. Define this in the configuration file as a value between 1024-65535. Similarly, if specified, agent.http.ipAddresses will be used to determine which IP addresses the server should bind to

In our server.json configuration 
    "https": é                    
      "ipAddresses": ["0.0.0.0"], 
      "port": 8544,               

But the command netstat conn (cli ZWESISTC ( ZWESISTC where ZWESISTC is the ZSS server displays nothing
However the command netstat conn ( cli ZWESVTSC sends : 
EZZ2587I ZWESVSTC 000DF0F4 0.0.0.0..8544          0.0.0.0..0             Listen
It seems  the App Server listens .

Do you think I can manage the 8544 port with AT TLS policy ?

In this case; I 'd have to code a agent body with http entry and the encryption should be done by AT TLS. Is it correct ?

Thank you very much for your help

Regards
Gilles Peniguel

**Comment by 1000TurquoisePogs** [comment]
Have you manually specified the entry  `ZWED_node_https_certificateAuthorities="safkeyring:////ZWESVUS/Sysazowering/SG Unipass Server Auth. 2016 CA,safkeyring:////ZWESVUS/Sysazowering/SG UniPass Root CA 2016"` within the instance.env file?
It seems the syntax is invalid, causing the 8544 port error.

The correct syntax appears to be
`ZWED_node_https_certificateAuthorities="safkeyring:////ZWESVUS/Sysazowering&SG Unipass Server Auth. 2016 CA,safkeyring:////ZWESVUS/Sysazowering&SG UniPass Root CA 2016"`
However, in the most recent Zowe version, I don't think specifying this parameter is required anymore.

**Comment by 1000TurquoisePogs** [comment]
Closed due to inactivity and probably no longer being necessary once 1.28.0 comes out (automated setting of ZWED_node_https_certificateAuthorities)
