### ISSUE TITLE
Error: TypeError: keyring_js.listKeyring is not a function 

### ISSUE THREAD

**Issue by vit-tomica** [zowe/zlux#766]
In Zowe version 1.25.0, I can see the following error:
`ZWED0179W - Unable to retrieve the list of certificate authorities from the keyring=ZWESTC_RING owner=ZWESTC Error: TypeError: keyring_js.listKeyring is not a function `
It seems that the keyring_js library is not on the correct version. The `listKeyring` function is supported since keyring_js@1.1.0 and the package.json contains an old one:
https://github.com/zowe/zlux-server-framework/blob/49642a32891997de3a5ec28f86e09e536b0a752a/package.json#L80

**Comment by 1000TurquoisePogs** [comment]
Thank you for the report!

**Comment by 1000TurquoisePogs** [comment]
This fix will be present in 1.28 / v2.0
