### ISSUE TITLE
No Warning or Saved Message when we try to save the Deleted file in Editor

### ISSUE THREAD

**Issue by AdarshdeepCheema** [zowe/zlux#767]
Steps to reproduce:
1. open a file in Editor.
2. Delete the file from USS 
3. now try to save the file from Editor and u will see no warning or saved message.
4. open the network tab from Browser and you will see errors, 404 not found

**Comment by AdarshdeepCheema** [comment]
https://github.com/zowe/zlux-editor/pull/283

**Comment by DivergentEuropeans** [comment]
Completed by https://github.com/zowe/zlux-editor/pull/284
