### ISSUE TITLE
Editor monaco panels broken

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#774]
In v2, the preferences menu looks like this
![image](https://user-images.githubusercontent.com/30730276/150604295-6a9ff6f2-3022-41d4-b541-ee9d819f9e82.png)
instead of this
![image](https://user-images.githubusercontent.com/30730276/150604322-48063f67-5e5c-4bdf-8117-401086fca6da.png)

**Comment by 1000TurquoisePogs** [comment]
It also does not disappear when the tab is closed

**Comment by 1000TurquoisePogs** [comment]
Also file viewing styles are broken
![image](https://user-images.githubusercontent.com/30730276/150604532-ed76986d-ec64-429c-b8dc-ce6df44c83a0.png)

**Comment by 1000TurquoisePogs** [comment]
I believe it is caused by:
```
Refused to apply style from 'https://.../ZLUX/plugins/org.zowe.editor/web/assets/monaco/editor/editor.main.css' because its MIME type ('application/json') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
/:1 Refused to apply style from 'https://.../ui/v1/zlux/ZLUX/plugins/org.zowe.editor/web/assets/monaco/editor/editor.main.css' because its MIME type ('application/json') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

**Comment by DivergentEuropeans** [comment]
WebUI team is planning to do this
