### ISSUE TITLE
Forbid DISP customization

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#796]

**Comment by DivergentEuropeans** [comment]
When you create a DS, you can say how you would like the DS to be referenced after creation i.e. DISP=new or DISP=keep or DISP=old which has different behaviours on if creation is doing overwrite on old dataset, or hold dataset with an exclusive lock. There's a lot of bad answers for DS creation API, so we shouldn't let users provide DISP arg (we don't do) and we should hardcode correct DISP arg in our API (we already do)

**Comment by 1000TurquoisePogs** [comment]
Completed in zss ~2.4
