### ISSUE TITLE
Unable to Launch Explorers under zowe Desktop 

### ISSUE THREAD

**Issue by grewaljasi** [zowe/zlux#803]
Hi, I am unable to open any Explorers under Desktop except IP Explorer and which works.
The error I am seeing is the following:
{"category":null,"pluginID":"org.zowe.zlux.auth.safsso","result":{"authenticated":true,"authorized":false,"message":"SAF RC 4, RACF RC 4, RACF REASON 0"}}

From looking at SAF 4 RACF 4 it means Certificate Not Trust but our certificates are in Trust Mode as everything else works.
This brings up the question....when we created certificates and we use: zowe-setup-certificates.env and do we need to use for external certificates as jwtsecret or other system alias or localhost.

I do see that there are other issues on the same problem too...and I can work with you on anyday and in any timezones.
I would really appreciate if someone can work with me as I really like to make this work.
Thank You in advance,
Regards,
Jasi.

**Comment by grewaljasi** [comment]
The error which i stated above - Does it requires RACF Certificates? we are using keystore

**Comment by grewaljasi** [comment]
I came to find out that if I do this and then it works but cannot go through Desktop link.
https://xxxx.xxxx.com:7554/ui/v1/explorer-jes/#/
https://xxxx.xxxx.com:7554/ui/v1/explorer-uss/#/
As one of the users which reported it and could it be that is using localhost ip address 127.0.0.1 instead of the system IP or host name under zowe desktop

**Comment by 1000TurquoisePogs** [comment]
This is not related to certificates or networking, its about RACF config and how the desktop checks for authority to display something.
Have you turned RBAC on? That looks like an RBAC message. 4/4 just is "The specified resource is not protected by RACF."
When RBAC is on, each URL is checked for authorization. The documentation is here https://docs.zowe.org/stable/extend/extend-desktop/mvd-dataservices/#using-dataservices-with-rbac
You'll need to let us know which URL was rejected for us to help more. You can open the browser's network log by opening the "Developer Tools" (normally F12) and checking the network tab. Such failures should have error code 403.

**Comment by lv198** [comment]
Hello everyone,
that's the same error I have here: https://github.com/zowe/zlux/issues/770#issue-1108198503

I have RBAC turned on and also configured the RACF Class ZOWE and the profile ZLUX.** but I still get the error mentioned above. When I turn off RBAC everything works fine.

**Comment by 1000TurquoisePogs** [comment]
To check if this is the same issue as not being able to use `ZLUX.**` can @grewaljasi confirm whether or not you can see a list of pinned apps on the desktop launch bar? If there are no pinned apps, you're likely getting authorization failures on reading the config service (same as #770) but if you are seeing them, then you may only be getting a failure on the explorers.

**Comment by grewaljasi** [comment]
Thank You and our problem as it was stated earlier by  1000TurquoisePogs, it is fixed by turning off RBAC and everything is working now.

Thank You everyone.
