### ISSUE TITLE
Fetch Datasets Failed

### ISSUE THREAD

**Issue by jimmschlo89** [zowe/zlux#807]
Hello,

I just recently upgraded Zowe to v1.27. Since then I have not been able to use the USS Explorer and the MVS Explorer. I get these errors:
![image](https://user-images.githubusercontent.com/49279914/157323455-8ed21efa-12c9-4605-aa77-73759a9ca3e7.png)
![image](https://user-images.githubusercontent.com/49279914/157323493-f952c654-7d33-4abd-9d2c-84ccf5ede53c.png)

I've followed the guide and it tells me:
**Error from msgsnd(), msgrcv(), or a related message queue
service. The UNIX errno is the reason code.
For reason code 1141, the following causes are possible:
• The TSO/E logon PROC is not correct. Ensure that the
information specified on the RESTAPI_FILE statement in the
IZUPRMxx parmlib member is correct.
• The user ID does not have a TSO segment in the RACF user
profile.
• TSO/E logon exit is active and is preventing the user ID from
logging on.
MSG_QUEUE_SYS_ERROR**

The parmlib member is good.
My ID does have a TSO segment (I'm a sysprog).
Which TSO logon proc? Nothing has changed in months. And the previous Zowe version worked fine.

Any help would be great!

Thanks!

**Comment by 1000TurquoisePogs** [comment]
@Joe-Winchester is this something you have seen before? This sounds more zosmf-bound but it's not my specialty.

**Comment by Joe-Winchester** [comment]
This does sound like it's z/OSMF causing the root problem, but I am unsure why a Zowe upgrade would be the tripwire that causes failure.
To diagnose more the first step would be to see if a raw z/OSMF REST API request for a data set API can be issued.  Try
`https://<zosmf_host>:443/zosmf/restfiles/ds?dslevel=<HLQ>` and look for the response.  
For example, here's a screen shot of google chrome firing the get request for `SYS1.*` data sets
<img width="688" alt="image" src="https://user-images.githubusercontent.com/28100302/157658313-fe1cae58-005e-43e9-9e14-74df3dd2f64c.png">
My guess would be that this is failing and there will be some kind of servlet stack trace in the response.  If we could see that response that'd be great.  
The TSO Logon proc that is used by z/OSMF is `IZUFPROC` and I have run into cases where folks have upgraded z/OS levels but failed to update the `IZUFPROC` member which is back level, so a patch of this to be the correct level for z/OS fixes the problem.

**Comment by jimmschlo89** [comment]
This is what was returned: { "errorID":"IZUG846W","errorMsg":"IZUG846W: An HTTP request for a z/OSMF REST service was received from a remote site. The request was rejected, however, because the remote site \"\" is not permitted to z/OSMF server \"IZUSVR\" on target system \"ibmsbx1.nml.com\" ."}

**Comment by jimmschlo89** [comment]
I get this other error in the zOSMF logs that I think tells a little more: 

CWWKS2960W: Cannot create the default credential for SAF authorization of unauthenticated users. All authorization checks for unauthenticated users will fail. The default credential could not be created due to the following error: CWWKS2905E: SAF service IRRSIA00_CREATE did not succeed because user IZUGUEST was not found in the SAF registry. SAF return code 0x00000008. RACF return code 0x00000008. RACF reason code 0x00000010.

The thing is - we didn't add IZUGUEST, we used a different name during configuration. But this was never a problem before when we had Zowe v1.19.

**Comment by jimmschlo89** [comment]
And actually I got that CWWKS2960W message to go away. I created the IZUGUEST UID and all that. Now the message doesn't show up but I still get the same CEA TSO error message and that IZUG846W error still displays when trying the url.

Any ideas? Or would I be better off opening a ticket with IBM?

**Comment by Joe-Winchester** [comment]
For the `IZUG846W` message,  what occured here is that your browser where you fired the REST request from got blocked by z/OSMF as it isn't an openlisted site.  You can add the value `X-CSRF-ZOSMF-HEADER` that is possible from the developer tools in your browser, or else using a REST client like postman.    https://www.ibm.com/docs/en/zos/2.3.0?topic=v2r3-establish-security-cross-site-zosmf-rest-requests has a little more info, and also it's possible to allow your z/OSMF server to relax its rules on CSRF (cross site forgery).  
Having said that,  I expect that your `CWWKS2960W:` means that you still won't be through.   I haven't come across IZUGUEST before.    Looking at https://www.ibm.com/docs/en/zos/2.3.0?topic=guide-security-configuration-requirements-zosmf it says that `IZUGUEST` is the security group for unauthenticated z/OSMF users.    I wonder if anyone from the APIML squad can help out.  @balhar-jakub

**Comment by Joe-Winchester** [comment]
@jimmschlo89 ,  if you want to you can open a ticket,. or else if you want to do a quick ad-hoc 30 minute webex give me a shout (you can e-mail me at `winchest@uk.ibm.com`) and I'd be happy to just eyeball some logs and see what's going on.

**Comment by jimmschlo89** [comment]
I have that header in place. I see it in the dev tools console under network.

**Comment by jimmschlo89** [comment]
That would be great, if you have time today! This is my last day before a long weekend. Back on Tuesday. I'm in the US (wisconsin) so I'm in Central Time (CT). I think you are 6 hours ahead of me.

**Comment by jimmschlo89** [comment]
Disregard this whole ticket.... IZUFPROC was not in the the SYS1.TSO.PROCLIB library. That fixed it all. Always the simplest things....

**Comment by Joe-Winchester** [comment]
Woo hoo !   That's great to hear that it was just a case of  `IZUFPROC` being available. 
Apologies I missed your update yesterday saying you were available,  I was travelling yesterday for an all day on-site face to face meeting (which felt a little odd meeting real people rather than talking to them through a web cam).   I'll close the git issue just to help keep the queue clean, but I'll also create a documentation troulbeshooting tip so it's easier to solve this for others going forward.
