### ISSUE TITLE
How to keep leading spaces in editor?

### ISSUE THREAD

**Issue by Martin-Zeithaml** [zowe/zlux#844]
I am not seeing leading spaces when open a member (there are missing 2 spaces before ```say```).
Is this a bug or some setting is missing?
![image](https://user-images.githubusercontent.com/66114686/167848977-cd3f8088-b633-48a2-a861-b0b26c056e20.png)

The language REXX was automatically detected. The same behavior for JCL too.

**Comment by 1000TurquoisePogs** [comment]
Can you check the network request associated with opening the dataset to see if your example has missing spaces in the rest api or if it is just the editor doing it wrong?
the output is organized into an array of strings for each row.

**Comment by Martin-Zeithaml** [comment]
Records look good:
![image](https://user-images.githubusercontent.com/66114686/167852019-13b58ef1-212c-403e-8032-2a787d2fb8f1.png)

**Comment by Martin-Zeithaml** [comment]
I have modified this [line](https://github.com/zowe/zlux-editor/blob/2daf253c47b1f3781424db253157c88e2c7dedfb/webClient/src/app/shared/http/http.data.adapter.service.ts#L102), replace ```trim``` with ```trimEnd``` and got the expected result:

![image](https://user-images.githubusercontent.com/66114686/168243726-a976df30-66c1-4ecd-b0d0-36405fe45bd7.png)

It seems, that the uss files are kept (with whitespaces) and the members were trimmed.

If no objection (I don't see any reason for trimming leading whitespace), I will fix this.

**Comment by Martin-Zeithaml** [comment]
Fixed in [PR280](https://github.com/zowe/zlux-editor/pull/280) and [PR281](https://github.com/zowe/zlux-editor/pull/281).
