### ISSUE TITLE
Editor panel doesn't expand when expanding editor when comparing files 

### ISSUE THREAD

**Issue by DivergentEuropeans** [zowe/zlux#851]
If you open Diff viewer (right click, compare contents on a secondly opened tab) and then expand the window, for example: widen it, the diff viewer render doesn't update to fit the new width of the Editor window

**Comment by anj20** [comment]
@DivergentEuropeans is the issue still open? I want to work on it...

**Comment by Anonymous961** [comment]
is this issue still open? I can try for this one.
