### ISSUE TITLE
Right click paste not working

### ISSUE THREAD

**Issue by DivergentEuropeans** [zowe/zlux#856]
When trying to paste into the editor currently we can only use ctrl + v, seems like the right click paste doesn't work.

**Comment by Martin-Zeithaml** [comment]
It seems to be a security limitation:
[Monaco-Editor #1674](https://github.com/microsoft/monaco-editor/issues/1674)
[StackOverFlow Paste](https://stackoverflow.com/questions/51395393/how-to-trigger-paste-event-manually-in-javascript)
