### ISSUE TITLE
Resource not found - HTTP 401 for all desktop explorer apps

### ISSUE THREAD

**Issue by Dingmans** [zowe/zlux#865]
Greetings,

Zowe version: v1.27.1
Node version: v12.22.10

After installing Zowe, all of the explorer applications in desktop has the same "Resource not found " issue.

**Excerpt from log **
Loading remote iframe app org.zowe.explorer-jes located at https://myhost/zlux/ui/v1/ZLUX/plugins/org.zowe.zlux.bootstrap/web/index.html:7554/ui/v1/explorer-jes

Loading remote iframe app org.zowe.explorer-mvs located at https://myhost/zlux/ui/v1/ZLUX/plugins/org.zowe.zlux.bootstrap/web/index.html:7554/ui/v1/explorer-mvs

Loading remote iframe app org.zowe.explorer-uss located at https://myhost/zlux/ui/v1/ZLUX/plugins/org.zowe.zlux.bootstrap/web/index.html:7554/ui/v1/explorer-uss

Accessing the apps directly via APIML works fine, for example: 
https://myhost/ui/v1/explorer-uss 
(Above "myhost" is mapped via a proxy to z/OS localhost port 7554)

Attached is the instance.env file, as well as joblog for STC ZWE1SV with apiml debug set to true. 
The STC log includes start up of zowe and test of desktop explorers before shutting down the task.

Any thoughts on above issue - can you see something in our setup that causes this behaviour, or suggestions for fixes?

[STDOUT.txt](https://github.com/zowe/api-layer/files/9010364/STDOUT.txt)
[instance.env.txt](https://github.com/zowe/api-layer/files/9010367/instance.env.txt)

**Comment by CarsonCook** [comment]
Hi @Dingmans, could you provide the URL that is opened when you right click on explorer-mvs and select `Open in new tab`? For example: https://<host>:<port>/zlux/ui/v1/ZLUX/plugins/org.zowe.explorer-mvs/iframe/

The URLs you added in the issue seem to be malformed, was this a copy paste error?

**Comment by Dingmans** [comment]
Hello @CarsonCook.

Indeed the URLs does seem to be malformed, and it's not a copy/paste issue.

The iframe itself seems to load correctly: 
https://myhost/zlux/ui/v1/ZLUX/plugins/org.zowe.explorer-jes/iframe/

Not exactly my home field this, but it does look like the routing breaks down in the iframe. If I manually change the iframe element to https://myhost/ui/v1/explorer-jes it works fine within the frame as well.

 **Iframe html element:** 
<iframe id="zluxIframe" src="https://myhost/zlux/ui/v1/ZLUX/plugins/org.zowe.zlux.bootstrap/web/index.html:7554/ui/v1/explorer-jes" ;="" style="position:fixed; top:0px; left:0px; bottom:0px; right:0px; width:100%; height:100%; border:none; margin:0; padding:0; overflow:hidden; z-index:999999;">
            Your browser doesn't support iframes
</iframe>


How should the URL typically look?

Many thanks!
/David

**Comment by CarsonCook** [comment]
Thanks for clarifying @Dingmans. In this case, it seems as though the bug with with ZLUX, not the APIML, so I am transferring this issue to the ZLUX repo.

**Comment by balhar-jakub** [comment]
@1000TurquoisePogs Could you please take a look and move this to the zlux?

**Comment by 1000TurquoisePogs** [comment]
The iframe html element indicates the problem.
src="https://myhost/zlux/ui/v1/ZLUX/plugins/org.zowe.zlux.bootstrap/web/index.html:7554/ui/v1/explorer-jes" should just be src="https://myhost:7554/ui/v1/explorer-jes"

**Comment by 1000TurquoisePogs** [comment]
Please check the value of ZWE_EXTERNAL_HOSTS and ZOWE_EXPLORER_HOST as they are involved in constructing this URL. They should just be hostnames, not urls.

If that doesnt improve things, try deleting the folder $INSTANCE_DIR/workspace/app-server/pluginDirs
It will be regenerated next start of zowe, and may have fixed values at that time.

**Comment by Dingmans** [comment]
Hello 1000TurquoisePogs,

I tried deleting the pluginDirs folder, unfortunately it didn't resolve the issue.
As of now both ZWE_EXTERNAL_HOSTS and ZOWE_EXPLORER_HOST are just hostnames, and not urls.

Looks more or less like below 
ZOWE_EXPLORER_HOST = test.mycompany.org
ZWE_EXTERNAL_HOSTS = zowe.mycompany.org

Perhaps the reverse proxy we have as a entry point to all exposed services on z/OS somehow causes this(wouldn't be the first time it causes issues), not that you can help on that front, but looking into that as well.

Many thanks!
//David

**Comment by Dingmans** [comment]
Greetings! 

Been on vacation, why no update for a while.

So, I managed to get the JES-explorer working by changing the following in ~/components/explorer-jes/pluginDefinition.json file:

_ä
  "identifier": "org.zowe.explorer-jes",
  "apiVersion": "1.0.0",
  "pluginVersion": "1.0.0",
  "pluginType": "application",
  "webContent": ä
    "framework": "iframe",
    "destination": **"https://myhost/ui/v1/explorer-jes"**  <-- Here I hardcoded the hostname & and no port. proxy handles port
    "launchDefinition": ä                                        
      "pluginShortNameKey": "JES Explorer",
      "pluginShortNameDefault": "JES Explorer",
      "imageSrc": "img/explorer-JES.png"
    å,
    "descriptionKey": "",
    "descriptionDefault": "",
    "isSingleWindowApp": true,
    "defaultWindowStyle": ä
      "width": 1400,
      "height": 800
    å
  å
å_

My question: 
Where is the variables in the original "https://ÅäZOWE_EXTERNAL_HOSTå:ÅäZWE_EXTERNAL_PORT/.... " URL picked up?

That is, where does below parameters/variables get their value?
ZOWE_EXTERNAL_HOST
ZWE_EXTERNAL_PORT


I find it a bit strange that ZOWE_EXTERNAL_HOST resolves to:
**https://myhost/zlux/ui/v1/ZLUX/plugins/org.zowe.zlux.bootstrap/web/index.html** 

But have been unable to locate where those values are initially defined?

Also tried to add ZOWE_EXTERNAL_HOST to instance.env file to try and override the value that way, but it wasn't picked up in the pluginDefinition.json files.

My hope was to be able to change ZOWE_EXTERNAL_HOST & ZWE_EXTERNAL_PORT in a configuration file in the instance libraries, to keep my hands off the product libraries so to speak. 

Best Regards,
David

**Comment by Dingmans** [comment]
Greetings,

Once we circumvented our reverse proxy solution we did no longer get these malformed URLs, so Zowe seems to be working fine.

With that I think we can close this issue.

Many thanks!

Regards,
David

**Comment by balhar-jakub** [comment]
Great. Thanks for letting us know.
