### ISSUE TITLE
Need to be able to clear search history in Editor

### ISSUE THREAD

**Issue by DivergentEuropeans** [zowe/zlux#867]
Can help point to write place for anyone

**Comment by Martin-Zeithaml** [comment]
UI idea:

![image](https://user-images.githubusercontent.com/66114686/187628063-e789f0bc-13c5-4dea-a7df-165434fe38e3.png)

![image](https://user-images.githubusercontent.com/66114686/187628162-9e0bc3ad-f569-4fe7-a47d-523ecbd5552a.png)
