### ISSUE TITLE
Publish our sample apps to jfrog npm!

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#877]
Take the sample angular, iframe, react, and 'node sample' apps, get their .pax files, wrap them in a package.json as seen in  zowe/zowe-install-packaging#2980 and then publish them over to the zowe.jfrog.io npm registry.

Bonus: we should be able to remove these sample apps from the zowe base install at that point. I dont think anyone cares if they are there, but they can grab them from the registry!

**Comment by struga0258** [comment]
All 3 samples have been published on the Zowe Artifactory. You can find them here:
https://zowe.jfrog.io/ui/repos/tree/General/npm-local-release/angular-sample
https://zowe.jfrog.io/ui/repos/tree/General/npm-local-release/iframe-sample
https://zowe.jfrog.io/ui/repos/tree/General/npm-local-release/react-sample
