### ISSUE TITLE
Non-browser specific issues for Editor

### ISSUE THREAD

**Issue by NolanRogers** [zowe/zlux#88]
If the file cannot be opened/read, the Editor should notify the user of this. Current behavior can confuse users because it looks like the untagged file is empty.

Tab scrolling should be only horizontal. It should not expand the editing area. It is desirable to be able to scroll the tabs with the mouse wheel, and not just the scroll bar.

If the opened file has a long name that overlaps close box of the tab, it is difficult or impossible to close the tab.

**Comment by 1000TurquoisePogs** [comment]
I believe all of these have been fixed in staging (so, 1.3.1 or 1.4.0)
