### ISSUE TITLE
[SPIKE] - Evaluate tools used by CLI team to manage Github issues

### ISSUE THREAD

**Issue by DivergentEuropeans** [zowe/zlux#930]
The TSC proposed best practices for squads to follow to clean up their backlog and better review issues in triage that slip through the cracks. CLI team has some automation to help them better manage their workflow and we should see if it's applicable to us, what day values we want to set for triggering certain events, etc. etc.

**Comment by 1000TurquoisePogs** [comment]
We implemented some of the workflows they had (stale bot) and issue templates. They had a changelog workflow that I didnt include though.
