### ISSUE TITLE
Workflows app UI issues in FireFox browser

### ISSUE THREAD

**Issue by NolanRogers** [zowe/zlux#94]
Configuration tab: Port fields do not display correctly.

MyTasks tab: When I click on the icon (3 lines) to expand the work area, I saw some very faint vertical lines. (I tried to capture this but as soon as I did - they disappeared.)

Workflows tab: When you first access this tab, the Description field is very narrow and the title is jumbled. (You can resize the column and then the title is displayed.)

**Comment by DivergentEuropeans** [comment]
Workflows app has been discontinued from core
