### ISSUE TITLE
SAF keyring - blank in CA name is not supported

### ISSUE THREAD

**Issue by m-kubik** [zowe/zlux#948]
Running Zowe 2.4 with SAF keyring and my own CA which uses "blank" in CN name.
e.g. "My CA Company"

This fails with following:
CRITICAL (_zsf.bootstrap,plugin-loader.js:927) unable to get issuer certificate

Looking at specifications how CN can be defined - space is allowed.
Is it known issue?

**Comment by 1000TurquoisePogs** [comment]
This message is saying that the app-server is unable to reach zss. Can you post zss log information? You should find a zssServer log file in the log directory of 2.4
I'd just like to know if zss is all good or if it is encountering an error that the app-server is then just a victim of.

**Comment by m-kubik** [comment]
thank you for help.
I have now a Case with IBM. Closing the issue here

**Comment by Joe-Winchester** [comment]
@1000TurquoisePogs ,  I ran into this problem with a customer this morning running Zowe 2.4.   
Is the suggested fix for them to update their CA label to have no spaces in it, or is there a node version pre-req (the customer was at node v12 so I suggested they went to a newer version).  Cheers !
