### ISSUE TITLE
Wrong handling promise object at `apimlHandler.js`

### ISSUE THREAD

**Issue by pavel-jares-bcm** [zowe/zlux#964]
**Describe the bug**

At the line https://github.com/zowe/zlux-server-framework/blob/v2.x/staging/plugins/sso-auth/lib/apimlHandler.js#LL142C1-L142C1 is very probably a bug:

```java
  authenticate(request, sessionState) {
    if (request.body) {
      this.logger.debug(`Authenticate with body`);
      return new Promise((resolve, reject) => {
        this.doLogin(request, sessionState, false).then(result=> {
          resolve(result);
        }).catch(e=> {
          Promise.resolve({success: false});
        });
      });
    } else if (request.cookies && request.cookies[TOKEN_NAME]) {
      return this.authenticateViaCookie(request, sessionState);
    } else {
      return Promise.resolve({success: false});
    }
  }
```

The code `Promise.resolve({success: false});` creates a new object and the result will disappear. There should be removed part `Promise.` to call the method of lambda.

**Comment by 1000TurquoisePogs** [comment]
Looks like the test case is if you pass some invalid credentials into the desktop login, then you'd like to see success:false (such as on the other side, in webauth.js) but if you see undefined instead, then that's what you're pointing out?

**Comment by hrshkshri** [comment]
The catch block in the if (request.body) clause of the authenticate method returns a new Promise that resolves with an object {success: false}. However, this Promise is not returned from the authenticate method, and therefore, the result will not be used or processed by the calling code.

**Comment by 1000TurquoisePogs** [comment]
Fix merged now, thank you @hrshkshri

**Comment by hrshkshri** [comment]
Happy to Contribute!
