### ISSUE TITLE
Question about dektop apps: explorer-uss/jes/mvs

### ISSUE THREAD

**Issue by wermarc** [zowe/zlux#967]
We have recently started to install zowe desktop on our z/OS environment.

At current stage, we now have zowe running with this configuration:

zowe 2.15
z/OS 2.5
currently we do not use zosmf with zowe (still looking into this on our side), authentication is saf based.
jks based certificates (still looking into getting racf keyrings to work)

We can succesfully login into the desktop application and use some of the provided plugins (api catalog, editor, ip explorer). 

We struggle with the 3 explorer plugins (-uss, -mvs, -jes). When we launch these plugins, we will see a login page. When we try to login, we get an error message.

After some analysis, we think that these plugins don't adress the rest apis correctly. On our environment, we have the gateway listening on port 7554, the app server is running on 7556.

So we do login to the server using a url like this:   https://<server>:7556/
The desktop is running on urls like this: https://<server>:7556/ZLUX/plugins/org.zowe.zlux.bootstrap/web/

When we try to launch explorer-uss for example, we get a login page. When we try to login, we see the following error in the browser console:

POST https://<server>:7556/gateway/api/v1/auth/login [HTTP/1.1 404 ZLUX: unknown resource requested 54ms]

We think that we get an error because the url does not use the correct port, login should be done to the gateway port (7554 in our case) ? Not sure if we missed something during setup or configuration, we do not know how these explorer plugins determine the urls to use to communicate with the rest apis.

Any help with this would be appreciated.

Thanks

(urls in this post have been edited to remove our internal server names)

**Comment by balhar-jakub** [comment]
I am tagging @1000TurquoisePogs for awareness. 

But just looking at the question above, please use the ports for gateway as the login as well as the virtual desktop should be done via API Gateway. 

E.g. for accessing the virtual desktop: https://:7554/zlux/ui/v1 and for login https://:7554/gateway/api/v1/auth/login

**Comment by wermarc** [comment]
Plugins work as expected when accessing desktop through the gateway. Thanks for putting us in the right direction. It was not that obvious for us that access has to be done using the gateway.

**Comment by balhar-jakub** [comment]
@1000TurquoisePogs Should we update something in the docs?

@wermarc Glad it helped, as such after figuring out whether we need to create a new docs issue we will close this issue as resolved.

**Comment by wermarc** [comment]
I think it is actually documented here: https://docs.zowe.org/stable/user-guide/mvd-configuration/#accessing-the-app-server
We did not notice that part, it is clearly stated that the ui should be accessed through the gateway, and access through appserver is not recommended.

**Comment by 1000TurquoisePogs** [comment]
Closing as completed.
