### ISSUE TITLE
Clarification needed for JES explorer hover help text

### ISSUE THREAD

**Issue by jrnewton** [zowe/zlux#972]
**Describe the bug**
The hover help for the JCL "EXPORT" statement contains an unfamiliar technical term 🤣  

The text:
```
EXPORT 
Operation Field Smack it
```

**Steps to Reproduce**

1. Open JES explorer
2. Open a Job
3. Open a JESJCL member containing EXPORT
4. Hover over EXPORT

**Screenshots (if needed)**

![2023-05-19 07_06_26-zowe - T-4135-169-59-184-241 ibmztrialmachines com - Remote Desktop Connection](https://github.com/zowe/zlux/assets/35567232/b2cc18d2-d33d-49f9-a330-08947484e240)

**Describe your environment**
Using Zowe version 2.2.0+20220714 via the Z Trials program

**Comment by 1000TurquoisePogs** [comment]
wow! thanks for reporting that. i'm assuming this hasnt changed in a while and i see it here https://github.com/zowe/explorer-wlp-packaging/blob/e637435ee0794c893efdc442315d2485b608f503/src/main/resources/languages/orion/jcl.json#L26 so i'll discuss it on the team meeting in 15 minutes

**Comment by 1000TurquoisePogs** [comment]
Looking at that file, it also seems we could add some better hover help text in many fields...

**Comment by 1000TurquoisePogs** [comment]
Perhaps the https://www.ibm.com/docs/en/zos/2.4.0?topic=reference-export-statement JCL reference is a good source of more meaningful text

**Comment by jrnewton** [comment]
Is there a non-archived repo that contains the hover help text?  I'd love to submit a PR but had no clue where it was defined.

**Comment by 1000TurquoisePogs** [comment]
I just unarchived https://github.com/zowe/explorer-wlp-packaging because I figure it probably is in there, but when I install explorer-jes locally, and grep around, I don't see the text, so I'm not sure how we're getting it in there.
@AdarshdeepCheema are you aware of how this gets pulled in?

Regarding contribution one way or another, it's best to make a fork on github and then a PR from that fork, so it probably doesnt matter if something's archived or not.

**Comment by 1000TurquoisePogs** [comment]
Spoke too soon, I was just greping wrong:

```
/sgrady/explorer-jes/node_modules> rg --no-ignore "Smack"
orion-editor-component/dist/utilities/jcl.js
41:            EXPORT: 'Operation Field Smack it',

orion-editor-component/src/utilities/jcl.js
36:            EXPORT: 'Operation Field Smack it',
```

**Comment by 1000TurquoisePogs** [comment]
So... it's actually THIS repo: https://github.com/zowe/orion-editor-component/blob/736bf5763baf4c6966f9e1ef835f4fc994a82f39/src/utilities/jcl.js#L36

**Comment by AdarshdeepCheema** [comment]
> I just unarchived https://github.com/zowe/explorer-wlp-packaging because I figure it probably is in there, but when I install explorer-jes locally, and grep around, I don't see the text, so I'm not sure how we're getting it in there. @AdarshdeepCheema are you aware of how this gets pulled in?
> 
> Regarding contribution one way or another, it's best to make a fork on github and then a PR from that fork, so it probably doesnt matter if something's archived or not.

No idea :( , I think it was discussed in the past as well. and when we tried but could not find the source

**Comment by 1000TurquoisePogs** [comment]
Thanks for the PR! It looks good to me so I approved it, but considering the age of that repo I need to figure out how it attaches to the overall build so we can get it in the production build.
Now that I learned about that list of hoverhelp, I'm wondering if we can even add more interesting help there, a few of the strings dont say much.

**Comment by 1000TurquoisePogs** [comment]
That auto-closed. Going to keep open until I know its in the build. Having an issue with the build automation, so checking on that.
