### ISSUE TITLE
IP Explorer dataService returns 500

### ISSUE THREAD

**Issue by skurnevich** [zowe/zlux#974]
IP Explorer does not work correctly for quite some time already, creating an issue just to track it. 
Dataservice constantly returns 500 for some endpoints. 
Issue seems to be related to z/os version. Works fine on z/os 2.4 and does not work on 2.5. 
Could be some headers mismatch for network management interface ([EZBNMIFR](https://www.ibm.com/docs/en/zos/2.5.0?topic=interfaces-tcpip-callable-nmi-ezbnmifr)) However these IBM docs didn't mention any format changes between 2.4 and 2.5

**Comment by 1000TurquoisePogs** [comment]
Which services return the 500s? For me, I got a 500 on both "info" and "port", but on 2.5 I still got the majority of the info in the UI that I expected.

**Comment by pfgdrupalas** [comment]
> Which services return the 500s? For me, I got a 500 on both "info" and "port", but on 2.5 I still got the majority of the info in the UI that I expected.

For us, it is just the reserved IP page of the IP explorer that does not render.  I woks for one instance, but fails for a different one.

**Comment by skurnevich** [comment]
> Which services return the 500s? For me, I got a 500 on both "info" and "port"

Yes it is basically just **/info** and **/ports** 
**Info** should return date stack started and IPv6 status - now it always show "IPv6 is disabled" as default value for the UI.
And **ports** for list of reserved ports.

**Comment by 1000TurquoisePogs** [comment]
OK, I'll take a look and see if I can reproduce the 2.4/2.5 difference too, since it seems like I'm seeing the same issues as you.

**Comment by 1000TurquoisePogs** [comment]
I believe this has been fixed in v2.18 and v3.0, maybe sooner. Simply, there was a fix but the build was broken so zowe was shipping outdated ip explorer.
