### ISSUE TITLE
Version 3 Web UI Squad

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/zlux#975]
Epic for the squad to link all the relevant work that the squad intend to prepare for the V3 release so we can track how far we are.

**Comment by 1000TurquoisePogs** [comment]
Library upgrades:

Breaking:
* Angular (likely angular 16, would be a breaking change to non-iframe plugins)
* (can we get rid of) corejs

Unlikely to be breaking:
* Webpack
* PrimeNG
* Typescript

**Comment by DivergentEuropeans** [comment]
Now, just documentation is left
