### ISSUE TITLE
Critical error ZWED0159E with normal Zowe run

### ISSUE THREAD

**Issue by skurnevich** [zowe/zlux#983]
We are seeing the error message during normal Zowe runs:

`2024-01-22 15:49:04.974 <ZWED:50726767> ZWESVUSR CRITICAL (_zsf.utils,util.js:110) ZWED0159E - Could not read zowe manifest, version unknown`

This message with critical severity confuses customers.

I've printed an error message from the [catch block](https://github.com/zowe/zlux-server-framework/blob/4bf97dd16b4cd0cecb0f5849b0fc01d3d06d1ad5/lib/util.js#L109) and it says

`2024-01-23 10:23:56.345 <ZWED:50727216> ZWESVUSR WARN (_zsf.utils,util.js:110) fsPromises.readFileSync is not a function
`

So there is probably some issue with **fs.promises** module import.

**Comment by 1000TurquoisePogs** [comment]
will be fixed in 2.16
