### ISSUE TITLE
Can't configure app-server in HTTP mode 

### ISSUE THREAD

**Issue by skurnevich** [zowe/zlux#984]
I was reviewing app-server configuration in [HTTP mode](https://docs.zowe.org/stable/user-guide/mvd-configuration/#http) for AT-TLS setup and noticed that if i set `components.app-server.node.http.ipAddresses` the app-server will fail with:

> ZWED0151W - unhandledRejection TypeError: Cannot add property 1, object is not extensible

I've created a [PR](https://github.com/zowe/zlux-server-framework/pull/532) to fix that

**Comment by 1000TurquoisePogs** [comment]
Thank you I've merged it so I guess I can close this. Reopen if needed.
