### ISSUE TITLE
Application Framework AT-TLS configuration 

### ISSUE THREAD

**Issue by skurnevich** [zowe/zlux#989]
The [Configuring Zowe Application Framework](https://docs.zowe.org/stable/user-guide/mvd-configuration) docs page describes how to configure the app framework for HTTP, but it is impossible to disable HTTPS. 

Even if you delete _app-server.node.https_ section the values will be filled from [defaults](https://github.com/zowe/zlux-app-server/blob/v2.x/staging/defaults/serverConfig/defaults.yaml). 
Then it seems that these functions were not updated for ATTLS:  [isServerHttps](https://github.com/zowe/zlux-server-framework/blob/5b6422c25763e4a3084074d87e1a6e064dd339da/lib/util.js#L500) and [getBestPort](https://github.com/zowe/zlux-server-framework/blob/5b6422c25763e4a3084074d87e1a6e064dd339da/lib/util.js#L505C16-L505C27) so if the _app-server.node.https_ section exists it will be used and http setup will be ignored.

**Comment by jalel01** [comment]
Hi Squad, i know of a Zowe user waiting on this fix to move their Zowe instance to production with DB2 UMS. Thank you for looking into it!

**Comment by 1000TurquoisePogs** [comment]
I think the main problem is the app-server defaults override attempts to turn https off these days.
But, that's from a set of conditionals, and one condition we do not have is any way for the users to tell us that they intend to use attls.

Months go we drafted a schema improvement for such a way, simply `zowe.network.server.attls=true` and `components.app-server.zowe.network.server.attls=true` for per-component.

https://github.com/zowe/zowe-install-packaging/pull/3446

Lets revisit this draft, get it in, and then have app-server be its first user, by having a new conditional in app-server by which if attls is set to true, then https is completely turned off.

**Comment by achmelo** [comment]
How does it work in the HA setup when 1 LPAR has AT-TLS and another doesn't?

**Comment by 1000TurquoisePogs** [comment]
In light of 2.18.0+ fully supporting the `zowe.network.server.tls.attls: true` setting, I'm closing this as fixed.

I believe HA accommodates this fine by having that section defined or not within HA blocks of the YAML.
