### ISSUE TITLE
Determine fate of USS/MVS Explorers in V3

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#990]
With the editor being an intended complete replacement of USS/MVS explorers, the explorers have been used less in v2, and recommended less.
Since maintaining things that almost do the same tasks doubles maintenance efforts, finally removing the USS/MVS explorers would be a good long-term goal.
Should we do this in V3?

This has no bearing on the JES explorer, which will remain.

**Comment by 1000TurquoisePogs** [comment]
If people want to popularity vote this, please chime in, thumbs up, thumbs down, or otherwise share thoughts.

**Comment by DivergentEuropeans** [comment]
👍 to removing USS/MVS Explorers for the reasons above

**Comment by DivergentEuropeans** [comment]
We decided to keep them because updating the Editor to V3 requires more work
